import type { TFormFieldPath } from "@sb/form-new";
import { createCallManagerSymbol } from "@sb/call-manager";
import { type IUpdatePlayerDetailsForm } from "./Model/IUpdatePlayerDetailsForm";
import { type IUpdatePlayerPhoneNumberForm } from "./Model/IUpdatePlayerPhoneNumberForm";
import { type IUpdatePlayerEmailForm } from "./Model/IUpdatePlayerEmailForm";

const UPDATE_PLAYER_DETAILS_FORM_NAME = "updatePlayerDetailsForm";

const UPDATE_PLAYER_DETAILS_FORM_NAME_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["name"];
const UPDATE_PLAYER_DETAILS_FORM_SURNAME_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["surname"];
const UPDATE_PLAYER_DETAILS_FORM_IDENTITY_NUMBER_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["identityNumber"];
const UPDATE_PLAYER_DETAILS_FORM_LOGIN_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["login"];
const UPDATE_PLAYER_DETAILS_FORM_EMAIL_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["email"];
const UPDATE_PLAYER_DETAILS_FORM_PHONE_NUMBER_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["phoneNumber"];
const UPDATE_PLAYER_DETAILS_FORM_DATE_OF_BIRTH_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["dateOfBirth"];
const UPDATE_PLAYER_DETAILS_FORM_COUNTRY_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["country"];
const UPDATE_PLAYER_DETAILS_FORM_TOWN_CITY_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["townCity"];
const UPDATE_PLAYER_DETAILS_FORM_ADDRESS_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["address"];
const UPDATE_PLAYER_DETAILS_FORM_POST_CODE_FIELD_PATH: TFormFieldPath<IUpdatePlayerDetailsForm> = ["postcode"];

const UPDATE_PLAYER_PHONE_NUMBER_FORM_NAME = "updatePlayerPhoneNumberForm";
const UPDATE_PLAYER_PHONE_NUMBER_FORM_PHONE_NUMBER_FIELD: TFormFieldPath<IUpdatePlayerPhoneNumberForm> = ["phoneNumber"];
const UPDATE_PLAYER_PHONE_NUMBER_FORM_PASSWORD_FIELD: TFormFieldPath<IUpdatePlayerPhoneNumberForm> = ["password"];
const UPDATE_PLAYER_PHONE_NUMBER_FORM_VERIFICATION_CODE_FIELD: TFormFieldPath<IUpdatePlayerPhoneNumberForm> = ["verificationCode"];

const UPDATE_PLAYER_PHONE_NUMBER_REQUEST_LOADING_SYMBOL = createCallManagerSymbol("UPDATE_PLAYER_PHONE_NUMBER_REQUEST_LOADING_SYMBOL");

const UPDATE_PLAYER_EMAIL_FORM_NAME = "updatePlayerEmailForm";
const UPDATE_PLAYER_EMAIL_FORM_EMAIL_FIELD_PATH: TFormFieldPath<IUpdatePlayerEmailForm> = ["email"];
const UPDATE_PLAYER_EMAIL_FORM_PASSWORD_FIELD_PATH: TFormFieldPath<IUpdatePlayerEmailForm> = ["password"];
const UPDATE_PLAYER_EMAIL_FORM_VERIFICATION_CODE_FIELD_PATH: TFormFieldPath<IUpdatePlayerEmailForm> = ["verificationCode"];

const UPDATE_PLAYER_EMAIL_REQUEST_LOADING_SYMBOL = createCallManagerSymbol("UPDATE_PLAYER_EMAIL_REQUEST_LOADING_SYMBOL");

export {
  UPDATE_PLAYER_DETAILS_FORM_NAME,
  UPDATE_PLAYER_DETAILS_FORM_NAME_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_SURNAME_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_IDENTITY_NUMBER_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_LOGIN_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_EMAIL_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_PHONE_NUMBER_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_DATE_OF_BIRTH_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_COUNTRY_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_TOWN_CITY_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_ADDRESS_FIELD_PATH,
  UPDATE_PLAYER_DETAILS_FORM_POST_CODE_FIELD_PATH,
  UPDATE_PLAYER_PHONE_NUMBER_FORM_NAME,
  UPDATE_PLAYER_PHONE_NUMBER_FORM_PHONE_NUMBER_FIELD,
  UPDATE_PLAYER_PHONE_NUMBER_FORM_PASSWORD_FIELD,
  UPDATE_PLAYER_PHONE_NUMBER_FORM_VERIFICATION_CODE_FIELD,
  UPDATE_PLAYER_PHONE_NUMBER_REQUEST_LOADING_SYMBOL,
  UPDATE_PLAYER_EMAIL_FORM_NAME,
  UPDATE_PLAYER_EMAIL_FORM_EMAIL_FIELD_PATH,
  UPDATE_PLAYER_EMAIL_FORM_PASSWORD_FIELD_PATH,
  UPDATE_PLAYER_EMAIL_FORM_VERIFICATION_CODE_FIELD_PATH,
  UPDATE_PLAYER_EMAIL_REQUEST_LOADING_SYMBOL,
};
