import { createCallManagerSymbol } from "@sb/call-manager";

const GAME_MANAGER_GAME_PAGES_LOADING_SYMBOL = createCallManagerSymbol("gameManagerGamePages");

const GAME_MANAGER_LABEL_GAMES_LOADING_SYMBOL = createCallManagerSymbol("gameManagerLabel");

const GAME_MANAGER_LABEL_GAMES_ADDITIONAL_LOADING_SYMBOL = createCallManagerSymbol("gameManagerLabelAdditional");

const GAME_MANAGER_PROVIDER_GAMES_LOADING_SYMBOL = createCallManagerSymbol("gameManagerProviderGames");

const GAME_MANAGER_PROVIDER_GAMES_ADDITIONAL_LOADING_SYMBOL = createCallManagerSymbol("gameManagerProviderGamesAdditional");

const GAME_MANAGER_SIMILAR_GAMES_LOADING_SYMBOL = createCallManagerSymbol("gameManagerSimilarGames");

const GAME_MANAGER_SEARCH_GAMES_LOADING_SYMBOL = createCallManagerSymbol("gameManagerSearchGames");

const GAME_MANAGER_SEARCH_ADDITIONAL_GAMES_LOADING_SYMBOL = createCallManagerSymbol("gameManagerSearchAdditionalGames");

const GAME_MANAGER_RECENTLY_PLAYED_GAMES_LOADING_SYMBOL = createCallManagerSymbol("GAME_MANAGER_RECENTLY_PLAYED_GAMES_LOADING_SYMBOL");

export {
  GAME_MANAGER_LABEL_GAMES_LOADING_SYMBOL,
  GAME_MANAGER_PROVIDER_GAMES_LOADING_SYMBOL,
  GAME_MANAGER_LABEL_GAMES_ADDITIONAL_LOADING_SYMBOL,
  GAME_MANAGER_GAME_PAGES_LOADING_SYMBOL,
  GAME_MANAGER_PROVIDER_GAMES_ADDITIONAL_LOADING_SYMBOL,
  GAME_MANAGER_SIMILAR_GAMES_LOADING_SYMBOL,
  GAME_MANAGER_SEARCH_GAMES_LOADING_SYMBOL,
  GAME_MANAGER_SEARCH_ADDITIONAL_GAMES_LOADING_SYMBOL,
  GAME_MANAGER_RECENTLY_PLAYED_GAMES_LOADING_SYMBOL,
};
