/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/sdk/typescript/TSErrorMappingGenerator.kt
 */
export enum EGetCashbackSumByPlayerCommandErrorCode {
  bonusNotFound = "bonus.not_found",
  playerBonusCashBackAmountShouldBeGreaterThanZero = "player_bonus.cash_back_amount_should_be_greater_than_zero",
  playerBonusPlayerBalanceShouldBeEqualOrLess = "player_bonus.player_balance_should_be_equal_or_less",
  playerBonusPlayerShouldNotHaveActiveBonuses = "player_bonus.player_should_not_have_active_bonuses",
  playerBonusPlayerShouldNotHaveOpenBets = "player_bonus.player_should_not_have_open_bets",
  playerBonusPlayerShouldNotHaveOpenGameRounds = "player_bonus.player_should_not_have_open_game_rounds",
  playerBonusPlayerShouldNotHaveOpenWithdrawals = "player_bonus.player_should_not_have_open_withdrawals",
}

export interface IBonusNotFoundContext {
  bonusId: string,
  operation: string,
}

export interface IPlayerBonusCashBackAmountShouldBeGreaterThanZeroContext {
}

export interface IPlayerBonusPlayerBalanceShouldBeEqualOrLessContext {
  maxPlayerBalance: string,
}

export interface IPlayerBonusPlayerShouldNotHaveActiveBonusesContext {
}

export interface IPlayerBonusPlayerShouldNotHaveOpenBetsContext {
}

export interface IPlayerBonusPlayerShouldNotHaveOpenGameRoundsContext {
}

export interface IPlayerBonusPlayerShouldNotHaveOpenWithdrawalsContext {
}

export interface IGetCashbackSumByPlayerCommandErrorMapping {
  [EGetCashbackSumByPlayerCommandErrorCode.bonusNotFound]: IBonusNotFoundContext,
  [EGetCashbackSumByPlayerCommandErrorCode.playerBonusCashBackAmountShouldBeGreaterThanZero]: IPlayerBonusCashBackAmountShouldBeGreaterThanZeroContext,
  [EGetCashbackSumByPlayerCommandErrorCode.playerBonusPlayerBalanceShouldBeEqualOrLess]: IPlayerBonusPlayerBalanceShouldBeEqualOrLessContext,
  [EGetCashbackSumByPlayerCommandErrorCode.playerBonusPlayerShouldNotHaveActiveBonuses]: IPlayerBonusPlayerShouldNotHaveActiveBonusesContext,
  [EGetCashbackSumByPlayerCommandErrorCode.playerBonusPlayerShouldNotHaveOpenBets]: IPlayerBonusPlayerShouldNotHaveOpenBetsContext,
  [EGetCashbackSumByPlayerCommandErrorCode.playerBonusPlayerShouldNotHaveOpenGameRounds]: IPlayerBonusPlayerShouldNotHaveOpenGameRoundsContext,
  [EGetCashbackSumByPlayerCommandErrorCode.playerBonusPlayerShouldNotHaveOpenWithdrawals]: IPlayerBonusPlayerShouldNotHaveOpenWithdrawalsContext,
}
