// Set false ONLY if you want to switch off this feature EVERYWHERE. This flag DOESN'T change BE behavior

import { isDev, isE2E } from "@sb/utils";

const COMMON_VERIFY_DEVICE_ENABLE = !isE2E && !isDev && true;

// Switch UI and Epics per theme. This flag DOESN'T change BE behavior.
const STARZBET_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;
const BAYWIN_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;
const BYCASINO_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;
const ZLOT_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;
const BETPUBLIC_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;
const BETWIZ_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;
const BETORSPIN_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;
const STARZBET_IN_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;
const LIGOBET_VERIFY_DEVICE_ENABLE = COMMON_VERIFY_DEVICE_ENABLE && true;

export {
  STARZBET_VERIFY_DEVICE_ENABLE,
  BAYWIN_VERIFY_DEVICE_ENABLE,
  BYCASINO_VERIFY_DEVICE_ENABLE,
  COMMON_VERIFY_DEVICE_ENABLE,
  ZLOT_VERIFY_DEVICE_ENABLE,
  BETPUBLIC_VERIFY_DEVICE_ENABLE,
  BETWIZ_VERIFY_DEVICE_ENABLE,
  BETORSPIN_VERIFY_DEVICE_ENABLE,
  STARZBET_IN_VERIFY_DEVICE_ENABLE,
  LIGOBET_VERIFY_DEVICE_ENABLE,
};
