import {
  shared_country_afghanistan,
  shared_country_alandIslands,
  shared_country_albania,
  shared_country_algeria,
  shared_country_americanSamoa,
  shared_country_andorra,
  shared_country_angola,
  shared_country_anguilla,
  shared_country_antarctica,
  shared_country_antiguaAndBarbuda,
  shared_country_argentina,
  shared_country_armenia,
  shared_country_aruba,
  shared_country_australia,
  shared_country_austria,
  shared_country_azerbaijan,
  shared_country_bahamas,
  shared_country_bahrain,
  shared_country_bangladesh,
  shared_country_barbados,
  shared_country_belarus,
  shared_country_belgium,
  shared_country_belize,
  shared_country_benin,
  shared_country_bermuda,
  shared_country_bhutan,
  shared_country_bolivia,
  shared_country_bonaireSintEustatiusAndSaba,
  shared_country_bosniaAndHerzegovina,
  shared_country_botswana,
  shared_country_bouvetIsland,
  shared_country_brazil,
  shared_country_britishIndianOceanTerritory,
  shared_country_bruneiDarussalam,
  shared_country_bulgaria,
  shared_country_burkinaFaso,
  shared_country_burundi,
  shared_country_caboVerde,
  shared_country_cambodia,
  shared_country_cameroon,
  shared_country_canada,
  shared_country_caymanIslands,
  shared_country_centralAfricanRepublic,
  shared_country_chad,
  shared_country_chile,
  shared_country_china,
  shared_country_christmasIsland,
  shared_country_cocosKeelingIslands,
  shared_country_colombia,
  shared_country_comoros,
  shared_country_congo,
  shared_country_congoDemocraticRepublicOfThe,
  shared_country_cookIslands,
  shared_country_costaRica,
  shared_country_coteDIvoire,
  shared_country_croatia,
  shared_country_cuba,
  shared_country_curacao,
  shared_country_cyprus,
  shared_country_czechia,
  shared_country_denmark,
  shared_country_djibouti,
  shared_country_dominica,
  shared_country_dominicanRepublic,
  shared_country_ecuador,
  shared_country_egypt,
  shared_country_elSalvador,
  shared_country_equatorialGuinea,
  shared_country_eritrea,
  shared_country_estonia,
  shared_country_eswatini,
  shared_country_ethiopia,
  shared_country_falklandIslandsMalvinas,
  shared_country_faroeIslands,
  shared_country_fiji,
  shared_country_finland,
  shared_country_france,
  shared_country_frenchGuiana,
  shared_country_frenchPolynesia,
  shared_country_frenchSouthernTerritories,
  shared_country_gabon,
  shared_country_gambia,
  shared_country_georgia,
  shared_country_germany,
  shared_country_ghana,
  shared_country_gibraltar,
  shared_country_greece,
  shared_country_greenland,
  shared_country_grenada,
  shared_country_guadeloupe,
  shared_country_guam,
  shared_country_guatemala,
  shared_country_guernsey,
  shared_country_guinea,
  shared_country_guineaBissau,
  shared_country_guyana,
  shared_country_haiti,
  shared_country_heardIslandAndMcDonaldIslands,
  shared_country_holySee,
  shared_country_honduras,
  shared_country_hongKong,
  shared_country_hungary,
  shared_country_iceland,
  shared_country_india,
  shared_country_indonesia,
  shared_country_iran,
  shared_country_iraq,
  shared_country_ireland,
  shared_country_isleOfMan,
  shared_country_israel,
  shared_country_italy,
  shared_country_jamaica,
  shared_country_japan,
  shared_country_jersey,
  shared_country_jordan,
  shared_country_kazakhstan,
  shared_country_kenya,
  shared_country_kiribati,
  shared_country_koreaDemocraticPeoplesRepublicOf,
  shared_country_koreaRepublicOf,
  shared_country_kosovo,
  shared_country_kuwait,
  shared_country_kyrgyzstan,
  shared_country_laoPeoplesDemocraticRepublic,
  shared_country_latvia,
  shared_country_lebanon,
  shared_country_lesotho,
  shared_country_liberia,
  shared_country_libya,
  shared_country_liechtenstein,
  shared_country_lithuania,
  shared_country_luxembourg,
  shared_country_macao,
  shared_country_madagascar,
  shared_country_malawi,
  shared_country_malaysia,
  shared_country_maldives,
  shared_country_mali,
  shared_country_malta,
  shared_country_marshallIslands,
  shared_country_martinique,
  shared_country_mauritania,
  shared_country_mauritius,
  shared_country_mayotte,
  shared_country_mexico,
  shared_country_micronesia,
  shared_country_moldova,
  shared_country_monaco,
  shared_country_mongolia,
  shared_country_montenegro,
  shared_country_montserrat,
  shared_country_morocco,
  shared_country_mozambique,
  shared_country_myanmar,
  shared_country_namibia,
  shared_country_nauru,
  shared_country_nepal,
  shared_country_netherlands,
  shared_country_newCaledonia,
  shared_country_newZealand,
  shared_country_nicaragua,
  shared_country_niger,
  shared_country_nigeria,
  shared_country_niue,
  shared_country_norfolkIsland,
  shared_country_northernMarianaIslands,
  shared_country_northMacedonia,
  shared_country_norway,
  shared_country_oman,
  shared_country_pakistan,
  shared_country_palau,
  shared_country_palestineStateOf,
  shared_country_panama,
  shared_country_papuaNewGuinea,
  shared_country_paraguay,
  shared_country_peru,
  shared_country_philippines,
  shared_country_pitcairn,
  shared_country_poland,
  shared_country_portugal,
  shared_country_puertoRico,
  shared_country_qatar,
  shared_country_reunion,
  shared_country_romania,
  shared_country_russianFederation,
  shared_country_rwanda,
  shared_country_saintBarthelemy,
  shared_country_saintHelenaAscensionAndTristanDaCunha,
  shared_country_saintKittsAndNevis,
  shared_country_saintLucia,
  shared_country_saintMartinFrenchPart,
  shared_country_saintPierreAndMiquelon,
  shared_country_saintVincentAndTheGrenadines,
  shared_country_samoa,
  shared_country_sanMarino,
  shared_country_saoTomeAndPrincipe,
  shared_country_saudiArabia,
  shared_country_senegal,
  shared_country_serbia,
  shared_country_seychelles,
  shared_country_sierraLeone,
  shared_country_singapore,
  shared_country_sintMaartenDutchPart,
  shared_country_slovakia,
  shared_country_slovenia,
  shared_country_solomonIslands,
  shared_country_somalia,
  shared_country_southAfrica,
  shared_country_southGeorgiaAndTheSouthSandwichIslands,
  shared_country_southSudan,
  shared_country_spain,
  shared_country_sriLanka,
  shared_country_sudan,
  shared_country_suriname,
  shared_country_svalbardAndJanMayen,
  shared_country_sweden,
  shared_country_switzerland,
  shared_country_syrianArabRepublic,
  shared_country_taiwan,
  shared_country_tajikistan,
  shared_country_tanzania,
  shared_country_thailand,
  shared_country_timorLeste,
  shared_country_togo,
  shared_country_tokelau,
  shared_country_tonga,
  shared_country_trinidadAndTobago,
  shared_country_tunisia,
  shared_country_turkey,
  shared_country_turkmenistan,
  shared_country_turksAndCaicosIslands,
  shared_country_tuvalu,
  shared_country_uganda,
  shared_country_ukraine,
  shared_country_unitedArabEmirates,
  shared_country_unitedKingdomOfGreatBritainAndNorthernIreland,
  shared_country_unitedStatesMinorOutlyingIslands,
  shared_country_unitedStatesOfAmerica,
  shared_country_uruguay,
  shared_country_uzbekistan,
  shared_country_vanuatu,
  shared_country_venezuela,
  shared_country_vietnam,
  shared_country_virginIslandsBritish,
  shared_country_virginIslandsUnitedStates,
  shared_country_wallisAndFutuna,
  shared_country_westernSahara,
  shared_country_yemen,
  shared_country_zambia,
  shared_country_zimbabwe,
  TSharedKey,
} from "@sb/translates/shared/SharedTKeys";
import { EAlpha3Code } from "@sb/utils";

const alpha3CodeTKeys: Record<EAlpha3Code, TSharedKey> = {
  [EAlpha3Code.ABW]: shared_country_aruba,
  [EAlpha3Code.AFG]: shared_country_afghanistan,
  [EAlpha3Code.AGO]: shared_country_angola,
  [EAlpha3Code.AIA]: shared_country_anguilla,
  [EAlpha3Code.ALA]: shared_country_alandIslands,
  [EAlpha3Code.ALB]: shared_country_albania,
  [EAlpha3Code.AND]: shared_country_andorra,
  [EAlpha3Code.ARE]: shared_country_unitedArabEmirates,
  [EAlpha3Code.ARG]: shared_country_argentina,
  [EAlpha3Code.ARM]: shared_country_armenia,
  [EAlpha3Code.ASM]: shared_country_americanSamoa,
  [EAlpha3Code.ATA]: shared_country_antarctica,
  [EAlpha3Code.ATF]: shared_country_frenchSouthernTerritories,
  [EAlpha3Code.ATG]: shared_country_antiguaAndBarbuda,
  [EAlpha3Code.AUS]: shared_country_australia,
  [EAlpha3Code.AUT]: shared_country_austria,
  [EAlpha3Code.AZE]: shared_country_azerbaijan,
  [EAlpha3Code.BDI]: shared_country_burundi,
  [EAlpha3Code.BEL]: shared_country_belgium,
  [EAlpha3Code.BEN]: shared_country_benin,
  [EAlpha3Code.BES]: shared_country_bonaireSintEustatiusAndSaba,
  [EAlpha3Code.BFA]: shared_country_burkinaFaso,
  [EAlpha3Code.BGD]: shared_country_bangladesh,
  [EAlpha3Code.BGR]: shared_country_bulgaria,
  [EAlpha3Code.BHR]: shared_country_bahrain,
  [EAlpha3Code.BHS]: shared_country_bahamas,
  [EAlpha3Code.BIH]: shared_country_bosniaAndHerzegovina,
  [EAlpha3Code.BLM]: shared_country_saintBarthelemy,
  [EAlpha3Code.BLR]: shared_country_belarus,
  [EAlpha3Code.BLZ]: shared_country_belize,
  [EAlpha3Code.BMU]: shared_country_bermuda,
  [EAlpha3Code.BOL]: shared_country_bolivia,
  [EAlpha3Code.BRA]: shared_country_brazil,
  [EAlpha3Code.BRB]: shared_country_barbados,
  [EAlpha3Code.BRN]: shared_country_bruneiDarussalam,
  [EAlpha3Code.BTN]: shared_country_bhutan,
  [EAlpha3Code.BVT]: shared_country_bouvetIsland,
  [EAlpha3Code.BWA]: shared_country_botswana,
  [EAlpha3Code.CAF]: shared_country_centralAfricanRepublic,
  [EAlpha3Code.CAN]: shared_country_canada,
  [EAlpha3Code.CCK]: shared_country_cocosKeelingIslands,
  [EAlpha3Code.CHE]: shared_country_switzerland,
  [EAlpha3Code.CHL]: shared_country_chile,
  [EAlpha3Code.CHN]: shared_country_china,
  [EAlpha3Code.CIV]: shared_country_coteDIvoire,
  [EAlpha3Code.CMR]: shared_country_cameroon,
  [EAlpha3Code.COD]: shared_country_congoDemocraticRepublicOfThe,
  [EAlpha3Code.COG]: shared_country_congo,
  [EAlpha3Code.COK]: shared_country_cookIslands,
  [EAlpha3Code.COL]: shared_country_colombia,
  [EAlpha3Code.COM]: shared_country_comoros,
  [EAlpha3Code.CPV]: shared_country_caboVerde,
  [EAlpha3Code.CRI]: shared_country_costaRica,
  [EAlpha3Code.CUB]: shared_country_cuba,
  [EAlpha3Code.CUW]: shared_country_curacao,
  [EAlpha3Code.CXR]: shared_country_christmasIsland,
  [EAlpha3Code.CYM]: shared_country_caymanIslands,
  [EAlpha3Code.CYP]: shared_country_cyprus,
  [EAlpha3Code.CZE]: shared_country_czechia,
  [EAlpha3Code.DEU]: shared_country_germany,
  [EAlpha3Code.DJI]: shared_country_djibouti,
  [EAlpha3Code.DMA]: shared_country_dominica,
  [EAlpha3Code.DNK]: shared_country_denmark,
  [EAlpha3Code.DOM]: shared_country_dominicanRepublic,
  [EAlpha3Code.DZA]: shared_country_algeria,
  [EAlpha3Code.ECU]: shared_country_ecuador,
  [EAlpha3Code.EGY]: shared_country_egypt,
  [EAlpha3Code.ERI]: shared_country_eritrea,
  [EAlpha3Code.ESH]: shared_country_westernSahara,
  [EAlpha3Code.ESP]: shared_country_spain,
  [EAlpha3Code.EST]: shared_country_estonia,
  [EAlpha3Code.ETH]: shared_country_ethiopia,
  [EAlpha3Code.FIN]: shared_country_finland,
  [EAlpha3Code.FJI]: shared_country_fiji,
  [EAlpha3Code.FLK]: shared_country_falklandIslandsMalvinas,
  [EAlpha3Code.FRA]: shared_country_france,
  [EAlpha3Code.FRO]: shared_country_faroeIslands,
  [EAlpha3Code.FSM]: shared_country_micronesia,
  [EAlpha3Code.GAB]: shared_country_gabon,
  [EAlpha3Code.GBR]: shared_country_unitedKingdomOfGreatBritainAndNorthernIreland,
  [EAlpha3Code.GEO]: shared_country_georgia,
  [EAlpha3Code.GGY]: shared_country_guernsey,
  [EAlpha3Code.GHA]: shared_country_ghana,
  [EAlpha3Code.GIB]: shared_country_gibraltar,
  [EAlpha3Code.GIN]: shared_country_guinea,
  [EAlpha3Code.GLP]: shared_country_guadeloupe,
  [EAlpha3Code.GMB]: shared_country_gambia,
  [EAlpha3Code.GNB]: shared_country_guineaBissau,
  [EAlpha3Code.GNQ]: shared_country_equatorialGuinea,
  [EAlpha3Code.GRC]: shared_country_greece,
  [EAlpha3Code.GRD]: shared_country_grenada,
  [EAlpha3Code.GRL]: shared_country_greenland,
  [EAlpha3Code.GTM]: shared_country_guatemala,
  [EAlpha3Code.GUF]: shared_country_frenchGuiana,
  [EAlpha3Code.GUM]: shared_country_guam,
  [EAlpha3Code.GUY]: shared_country_guyana,
  [EAlpha3Code.HKG]: shared_country_hongKong,
  [EAlpha3Code.HMD]: shared_country_heardIslandAndMcDonaldIslands,
  [EAlpha3Code.HND]: shared_country_honduras,
  [EAlpha3Code.HRV]: shared_country_croatia,
  [EAlpha3Code.HTI]: shared_country_haiti,
  [EAlpha3Code.HUN]: shared_country_hungary,
  [EAlpha3Code.IDN]: shared_country_indonesia,
  [EAlpha3Code.IMN]: shared_country_isleOfMan,
  [EAlpha3Code.IND]: shared_country_india,
  [EAlpha3Code.IOT]: shared_country_britishIndianOceanTerritory,
  [EAlpha3Code.IRL]: shared_country_ireland,
  [EAlpha3Code.IRN]: shared_country_iran,
  [EAlpha3Code.IRQ]: shared_country_iraq,
  [EAlpha3Code.ISL]: shared_country_iceland,
  [EAlpha3Code.ISR]: shared_country_israel,
  [EAlpha3Code.ITA]: shared_country_italy,
  [EAlpha3Code.JAM]: shared_country_jamaica,
  [EAlpha3Code.JEY]: shared_country_jersey,
  [EAlpha3Code.JOR]: shared_country_jordan,
  [EAlpha3Code.JPN]: shared_country_japan,
  [EAlpha3Code.KAZ]: shared_country_kazakhstan,
  [EAlpha3Code.KEN]: shared_country_kenya,
  [EAlpha3Code.KGZ]: shared_country_kyrgyzstan,
  [EAlpha3Code.KHM]: shared_country_cambodia,
  [EAlpha3Code.KIR]: shared_country_kiribati,
  [EAlpha3Code.KNA]: shared_country_saintKittsAndNevis,
  [EAlpha3Code.KOR]: shared_country_koreaRepublicOf,
  [EAlpha3Code.KWT]: shared_country_kuwait,
  [EAlpha3Code.LAO]: shared_country_laoPeoplesDemocraticRepublic,
  [EAlpha3Code.LBN]: shared_country_lebanon,
  [EAlpha3Code.LBR]: shared_country_liberia,
  [EAlpha3Code.LBY]: shared_country_libya,
  [EAlpha3Code.LCA]: shared_country_saintLucia,
  [EAlpha3Code.LIE]: shared_country_liechtenstein,
  [EAlpha3Code.LKA]: shared_country_sriLanka,
  [EAlpha3Code.LSO]: shared_country_lesotho,
  [EAlpha3Code.LTU]: shared_country_lithuania,
  [EAlpha3Code.LUX]: shared_country_luxembourg,
  [EAlpha3Code.LVA]: shared_country_latvia,
  [EAlpha3Code.MAC]: shared_country_macao,
  [EAlpha3Code.MAF]: shared_country_saintMartinFrenchPart,
  [EAlpha3Code.MAR]: shared_country_morocco,
  [EAlpha3Code.MCO]: shared_country_monaco,
  [EAlpha3Code.MDA]: shared_country_moldova,
  [EAlpha3Code.MDG]: shared_country_madagascar,
  [EAlpha3Code.MDV]: shared_country_maldives,
  [EAlpha3Code.MEX]: shared_country_mexico,
  [EAlpha3Code.MHL]: shared_country_marshallIslands,
  [EAlpha3Code.MKD]: shared_country_northMacedonia,
  [EAlpha3Code.MLI]: shared_country_mali,
  [EAlpha3Code.MLT]: shared_country_malta,
  [EAlpha3Code.MMR]: shared_country_myanmar,
  [EAlpha3Code.MNE]: shared_country_montenegro,
  [EAlpha3Code.MNG]: shared_country_mongolia,
  [EAlpha3Code.MNP]: shared_country_northernMarianaIslands,
  [EAlpha3Code.MOZ]: shared_country_mozambique,
  [EAlpha3Code.MRT]: shared_country_mauritania,
  [EAlpha3Code.MSR]: shared_country_montserrat,
  [EAlpha3Code.MTQ]: shared_country_martinique,
  [EAlpha3Code.MUS]: shared_country_mauritius,
  [EAlpha3Code.MWI]: shared_country_malawi,
  [EAlpha3Code.MYS]: shared_country_malaysia,
  [EAlpha3Code.MYT]: shared_country_mayotte,
  [EAlpha3Code.NAM]: shared_country_namibia,
  [EAlpha3Code.NCL]: shared_country_newCaledonia,
  [EAlpha3Code.NER]: shared_country_niger,
  [EAlpha3Code.NFK]: shared_country_norfolkIsland,
  [EAlpha3Code.NGA]: shared_country_nigeria,
  [EAlpha3Code.NIC]: shared_country_nicaragua,
  [EAlpha3Code.NIU]: shared_country_niue,
  [EAlpha3Code.NLD]: shared_country_netherlands,
  [EAlpha3Code.NOR]: shared_country_norway,
  [EAlpha3Code.NPL]: shared_country_nepal,
  [EAlpha3Code.NRU]: shared_country_nauru,
  [EAlpha3Code.NZL]: shared_country_newZealand,
  [EAlpha3Code.OMN]: shared_country_oman,
  [EAlpha3Code.PAK]: shared_country_pakistan,
  [EAlpha3Code.PAN]: shared_country_panama,
  [EAlpha3Code.PCN]: shared_country_pitcairn,
  [EAlpha3Code.PER]: shared_country_peru,
  [EAlpha3Code.PHL]: shared_country_philippines,
  [EAlpha3Code.PLW]: shared_country_palau,
  [EAlpha3Code.PNG]: shared_country_papuaNewGuinea,
  [EAlpha3Code.POL]: shared_country_poland,
  [EAlpha3Code.PRI]: shared_country_puertoRico,
  [EAlpha3Code.PRK]: shared_country_koreaDemocraticPeoplesRepublicOf,
  [EAlpha3Code.PRT]: shared_country_portugal,
  [EAlpha3Code.PRY]: shared_country_paraguay,
  [EAlpha3Code.PSE]: shared_country_palestineStateOf,
  [EAlpha3Code.PYF]: shared_country_frenchPolynesia,
  [EAlpha3Code.QAT]: shared_country_qatar,
  [EAlpha3Code.REU]: shared_country_reunion,
  [EAlpha3Code.ROU]: shared_country_romania,
  [EAlpha3Code.RUS]: shared_country_russianFederation,
  [EAlpha3Code.RWA]: shared_country_rwanda,
  [EAlpha3Code.SAU]: shared_country_saudiArabia,
  [EAlpha3Code.SDN]: shared_country_sudan,
  [EAlpha3Code.SEN]: shared_country_senegal,
  [EAlpha3Code.SGP]: shared_country_singapore,
  [EAlpha3Code.SGS]: shared_country_southGeorgiaAndTheSouthSandwichIslands,
  [EAlpha3Code.SHN]: shared_country_saintHelenaAscensionAndTristanDaCunha,
  [EAlpha3Code.SJM]: shared_country_svalbardAndJanMayen,
  [EAlpha3Code.SLB]: shared_country_solomonIslands,
  [EAlpha3Code.SLE]: shared_country_sierraLeone,
  [EAlpha3Code.SLV]: shared_country_elSalvador,
  [EAlpha3Code.SMR]: shared_country_sanMarino,
  [EAlpha3Code.SOM]: shared_country_somalia,
  [EAlpha3Code.SPM]: shared_country_saintPierreAndMiquelon,
  [EAlpha3Code.SRB]: shared_country_serbia,
  [EAlpha3Code.SSD]: shared_country_southSudan,
  [EAlpha3Code.STP]: shared_country_saoTomeAndPrincipe,
  [EAlpha3Code.SUR]: shared_country_suriname,
  [EAlpha3Code.SVK]: shared_country_slovakia,
  [EAlpha3Code.SVN]: shared_country_slovenia,
  [EAlpha3Code.SWE]: shared_country_sweden,
  [EAlpha3Code.SWZ]: shared_country_eswatini,
  [EAlpha3Code.SXM]: shared_country_sintMaartenDutchPart,
  [EAlpha3Code.SYC]: shared_country_seychelles,
  [EAlpha3Code.SYR]: shared_country_syrianArabRepublic,
  [EAlpha3Code.TCA]: shared_country_turksAndCaicosIslands,
  [EAlpha3Code.TCD]: shared_country_chad,
  [EAlpha3Code.TGO]: shared_country_togo,
  [EAlpha3Code.THA]: shared_country_thailand,
  [EAlpha3Code.TJK]: shared_country_tajikistan,
  [EAlpha3Code.TKL]: shared_country_tokelau,
  [EAlpha3Code.TKM]: shared_country_turkmenistan,
  [EAlpha3Code.TLS]: shared_country_timorLeste,
  [EAlpha3Code.TON]: shared_country_tonga,
  [EAlpha3Code.TTO]: shared_country_trinidadAndTobago,
  [EAlpha3Code.TUN]: shared_country_tunisia,
  [EAlpha3Code.TUR]: shared_country_turkey,
  [EAlpha3Code.TUV]: shared_country_tuvalu,
  [EAlpha3Code.TWN]: shared_country_taiwan,
  [EAlpha3Code.TZA]: shared_country_tanzania,
  [EAlpha3Code.UGA]: shared_country_uganda,
  [EAlpha3Code.UKR]: shared_country_ukraine,
  [EAlpha3Code.UMI]: shared_country_unitedStatesMinorOutlyingIslands,
  [EAlpha3Code.URY]: shared_country_uruguay,
  [EAlpha3Code.USA]: shared_country_unitedStatesOfAmerica,
  [EAlpha3Code.UZB]: shared_country_uzbekistan,
  [EAlpha3Code.VAT]: shared_country_holySee,
  [EAlpha3Code.VCT]: shared_country_saintVincentAndTheGrenadines,
  [EAlpha3Code.VEN]: shared_country_venezuela,
  [EAlpha3Code.VGB]: shared_country_virginIslandsBritish,
  [EAlpha3Code.VIR]: shared_country_virginIslandsUnitedStates,
  [EAlpha3Code.VNM]: shared_country_vietnam,
  [EAlpha3Code.VUT]: shared_country_vanuatu,
  [EAlpha3Code.WLF]: shared_country_wallisAndFutuna,
  [EAlpha3Code.WSM]: shared_country_samoa,
  [EAlpha3Code.YEM]: shared_country_yemen,
  [EAlpha3Code.ZAF]: shared_country_southAfrica,
  [EAlpha3Code.ZMB]: shared_country_zambia,
  [EAlpha3Code.ZWE]: shared_country_zimbabwe,
  [EAlpha3Code.XXK]: shared_country_kosovo,
};

export { alpha3CodeTKeys };
