import type { TSharedKey } from "@sb/translates/shared/SharedTKeys";
import {
  shared_marketColor_red,
  shared_marketColor_black,
  shared_marketColor_green,
  shared_marketColor_yellow,
  shared_marketColor_blue,
} from "@sb/translates/shared/SharedTKeys";
import { EMarketColor } from "../EMarketColor";

/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptMapGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.MarketColorSource
 */
export const marketColorTKeys: Record<EMarketColor, TSharedKey> = {
  [EMarketColor.red]: shared_marketColor_red,
  [EMarketColor.black]: shared_marketColor_black,
  [EMarketColor.green]: shared_marketColor_green,
  [EMarketColor.yellow]: shared_marketColor_yellow,
  [EMarketColor.blue]: shared_marketColor_blue,
};
