import type { TSharedKey } from "@sb/translates/shared/SharedTKeys";
import {
  shared_market_score_12,
  shared_market_score_some_lose_first_set_and_win_match_yes_no,
  shared_market_score_some_set_clean_win_in_match_yes_no,
  shared_market_score_highest_scopes_score,
  shared_market_score_cs,
  shared_market_score_odd_even,
  shared_market_game_odd_even,
  shared_market_score_ou,
  shared_market_game_ou,
  shared_market_score_ah,
  shared_market_game_ah,
  shared_market_score_ou_team,
  shared_market_game_ou_team,
  shared_market_score_odd_even_team,
  shared_market_game_odd_even_team,
  shared_market_game_u_win_team,
  shared_market_game_o_win_team,
  shared_market_score_to_score_first,
  shared_market_score_to_score_last,
  shared_market_score_highest_scope_score,
  shared_market_score_to_win_all_scopes_team_yes_no,
  shared_market_score_team_to_win_both_halves_yes_no_team,
  shared_market_score_team_win_first_half_and_match_yes_no_team,
  shared_market_score_team_win_first_quarter_and_match_yes_no_team,
  shared_market_score_overtime_yes_no,
  shared_market_score_winning_margin,
  shared_market_score_12_score,
  shared_market_score_odd_even_high_low,
  shared_market_score_longest_consecutive,
  shared_market_score_to_score_race,
  shared_market_score_exact_number,
  shared_market_point_odd_even,
  shared_market_point_ou,
  shared_market_point_ah,
  shared_market_point_ou_team,
  shared_market_point_odd_even_team,
  shared_market_point_o_win_team,
  shared_market_point_u_win_team,
  shared_market_score_1x2,
  shared_market_score_interval_1x2,
  shared_market_score_dc,
  shared_market_score_interval_ah,
  shared_market_score_interval_ou,
  shared_market_score_interval_ou_team,
  shared_market_score_interval_dc,
  shared_market_score_u_win_team,
  shared_market_score_o_win_draw_team,
  shared_market_score_o_win_team,
  shared_market_score_win_to_nil_team,
  shared_market_score_range_number,
  shared_market_score_range_number_team,
  shared_market_score_range_number_yes_no,
  shared_market_score_range_number_yes_no_team,
  shared_market_score_ht_ft,
  shared_market_score_draw,
  shared_market_score_both_to_score_yes_no,
  shared_market_score_exact_number_team,
  shared_market_score_exact_number_yes_no,
  shared_market_score_exact_number_yes_no_team,
  shared_market_score_win_most_periods,
  shared_market_score_triple_result,
  shared_market_yellow_card_1x2,
  shared_market_red_card_1x2,
  shared_market_corner_1x2,
  shared_market_offside_1x2,
  shared_market_foul_1x2,
  shared_market_shot_on_goal_1x2,
  shared_market_score_1x2_ou,
  shared_market_score_1x2_teams_to_score,
  shared_market_score_1x2_early_payout,
  shared_market_yellow_card_dc,
  shared_market_red_card_dc,
  shared_market_corner_dc,
  shared_market_offside_dc,
  shared_market_foul_dc,
  shared_market_shot_on_goal_dc,
  shared_market_yellow_card_ah,
  shared_market_red_card_ah,
  shared_market_corner_ah,
  shared_market_offside_ah,
  shared_market_foul_ah,
  shared_market_shot_on_goal_ah,
  shared_market_yellow_card_ou,
  shared_market_red_card_ou,
  shared_market_corner_ou,
  shared_market_offside_ou,
  shared_market_foul_ou,
  shared_market_shot_on_goal_ou,
  shared_market_yellow_card_ou_team,
  shared_market_red_card_ou_team,
  shared_market_corner_ou_team,
  shared_market_offside_ou_team,
  shared_market_foul_ou_team,
  shared_market_shot_on_goal_ou_team,
  shared_market_yellow_card_cs,
  shared_market_red_card_cs,
  shared_market_corner_cs,
  shared_market_offside_cs,
  shared_market_foul_cs,
  shared_market_shot_on_goal_cs,
  shared_market_yellow_card_odd_even,
  shared_market_red_card_odd_even,
  shared_market_corner_odd_even,
  shared_market_offside_odd_even,
  shared_market_foul_odd_even,
  shared_market_shot_on_goal_odd_even,
  shared_market_yellow_card_odd_even_team,
  shared_market_red_card_odd_even_team,
  shared_market_corner_odd_even_team,
  shared_market_offside_odd_even_team,
  shared_market_foul_odd_even_team,
  shared_market_shot_on_goal_odd_even_team,
  shared_market_yellow_card_u_win_team,
  shared_market_red_card_u_win_team,
  shared_market_corner_u_win_team,
  shared_market_offside_u_win_team,
  shared_market_foul_u_win_team,
  shared_market_shot_on_goal_u_win_team,
  shared_market_yellow_card_o_win_team,
  shared_market_red_card_o_win_team,
  shared_market_corner_o_win_team,
  shared_market_offside_o_win_team,
  shared_market_foul_o_win_team,
  shared_market_shot_on_goal_o_win_team,
  shared_market_yellow_card_o_win_draw_team,
  shared_market_red_card_o_win_draw_team,
  shared_market_corner_o_win_draw_team,
  shared_market_offside_o_win_draw_team,
  shared_market_foul_o_win_draw_team,
  shared_market_shot_on_goal_o_win_draw_team,
  shared_market_score_u_win_draw_team,
  shared_market_yellow_card_u_win_draw_team,
  shared_market_red_card_u_win_draw_team,
  shared_market_corner_u_win_draw_team,
  shared_market_offside_u_win_draw_team,
  shared_market_foul_u_win_draw_team,
  shared_market_shot_on_goal_u_win_draw_team,
  shared_market_score_u_draw,
  shared_market_yellow_card_u_draw,
  shared_market_red_card_u_draw,
  shared_market_corner_u_draw,
  shared_market_offside_u_draw,
  shared_market_foul_u_draw,
  shared_market_shot_on_goal_u_draw,
  shared_market_score_o_draw,
  shared_market_yellow_card_o_draw,
  shared_market_red_card_o_draw,
  shared_market_corner_o_draw,
  shared_market_offside_o_draw,
  shared_market_foul_o_draw,
  shared_market_shot_on_goal_o_draw,
  shared_market_yellow_card_win_to_nil_team,
  shared_market_red_card_win_to_nil_team,
  shared_market_corner_win_to_nil_team,
  shared_market_offside_win_to_nil_team,
  shared_market_foul_win_to_nil_team,
  shared_market_shot_on_goal_win_to_nil_team,
  shared_market_yellow_card_range_number,
  shared_market_red_card_range_number,
  shared_market_corner_range_number,
  shared_market_offside_range_number,
  shared_market_foul_range_number,
  shared_market_shot_on_goal_range_number,
  shared_market_yellow_card_range_number_team,
  shared_market_red_card_range_number_team,
  shared_market_corner_range_number_team,
  shared_market_offside_range_number_team,
  shared_market_foul_range_number_team,
  shared_market_shot_on_goal_range_number_team,
  shared_market_yellow_card_range_number_yes_no,
  shared_market_red_card_range_number_yes_no,
  shared_market_corner_range_number_yes_no,
  shared_market_offside_range_number_yes_no,
  shared_market_foul_range_number_yes_no,
  shared_market_shot_on_goal_range_number_yes_no,
  shared_market_yellow_card_range_number_yes_no_team,
  shared_market_red_card_range_number_yes_no_team,
  shared_market_corner_range_number_yes_no_team,
  shared_market_offside_range_number_yes_no_team,
  shared_market_foul_range_number_yes_no_team,
  shared_market_shot_on_goal_range_number_yes_no_team,
  shared_market_yellow_card_ht_ft,
  shared_market_red_card_ht_ft,
  shared_market_corner_ht_ft,
  shared_market_offside_ht_ft,
  shared_market_foul_ht_ft,
  shared_market_shot_on_goal_ht_ft,
  shared_market_yellow_card_draw,
  shared_market_red_card_draw,
  shared_market_corner_draw,
  shared_market_offside_draw,
  shared_market_foul_draw,
  shared_market_shot_on_goal_draw,
  shared_market_yellow_card_both_to_score_yes_no,
  shared_market_red_card_both_to_score_yes_no,
  shared_market_corner_both_to_score_yes_no,
  shared_market_offside_both_to_score_yes_no,
  shared_market_foul_both_to_score_yes_no,
  shared_market_shot_on_goal_both_to_score_yes_no,
  shared_market_yellow_card_exact_number,
  shared_market_red_card_exact_number,
  shared_market_corner_exact_number,
  shared_market_offside_exact_number,
  shared_market_foul_exact_number,
  shared_market_shot_on_goal_exact_number,
  shared_market_yellow_card_exact_number_team,
  shared_market_red_card_exact_number_team,
  shared_market_corner_exact_number_team,
  shared_market_offside_exact_number_team,
  shared_market_foul_exact_number_team,
  shared_market_shot_on_goal_exact_number_team,
  shared_market_yellow_card_exact_number_yes_no,
  shared_market_red_card_exact_number_yes_no,
  shared_market_corner_exact_number_yes_no,
  shared_market_offside_exact_number_yes_no,
  shared_market_foul_exact_number_yes_no,
  shared_market_shot_on_goal_exact_number_yes_no,
  shared_market_yellow_card_exact_number_yes_no_team,
  shared_market_red_card_exact_number_yes_no_team,
  shared_market_corner_exact_number_yes_no_team,
  shared_market_offside_exact_number_yes_no_team,
  shared_market_foul_exact_number_yes_no_team,
  shared_market_shot_on_goal_exact_number_yes_no_team,
  shared_market_score_team_to_score_yes_no_team,
  shared_market_yellow_card_team_to_score_yes_no_team,
  shared_market_red_card_team_to_score_yes_no_team,
  shared_market_corner_team_to_score_yes_no_team,
  shared_market_offside_team_to_score_yes_no_team,
  shared_market_foul_team_to_score_yes_no_team,
  shared_market_shot_on_goal_team_to_score_yes_no_team,
  shared_market_score_both_to_score_and_o_yes_no,
  shared_market_yellow_card_both_to_score_and_o_yes_no,
  shared_market_red_card_both_to_score_and_o_yes_no,
  shared_market_corner_both_to_score_and_o_yes_no,
  shared_market_offside_both_to_score_and_o_yes_no,
  shared_market_foul_both_to_score_and_o_yes_no,
  shared_market_shot_on_goal_both_to_score_and_o_yes_no,
  shared_market_score_both_to_score_and_u_yes_no,
  shared_market_yellow_card_both_to_score_and_u_yes_no,
  shared_market_red_card_both_to_score_and_u_yes_no,
  shared_market_corner_both_to_score_and_u_yes_no,
  shared_market_offside_both_to_score_and_u_yes_no,
  shared_market_foul_both_to_score_and_u_yes_no,
  shared_market_shot_on_goal_both_to_score_and_u_yes_no,
  shared_market_score_team_to_score_in_both_halves_yes_no_team,
  shared_market_yellow_card_team_to_score_in_both_halves_yes_no_team,
  shared_market_red_card_team_to_score_in_both_halves_yes_no_team,
  shared_market_corner_team_to_score_in_both_halves_yes_no_team,
  shared_market_offside_team_to_score_in_both_halves_yes_no_team,
  shared_market_foul_team_to_score_in_both_halves_yes_no_team,
  shared_market_shot_on_goal_team_to_score_in_both_halves_yes_no_team,
  shared_market_yellow_card_team_to_win_both_halves_yes_no_team,
  shared_market_red_card_team_to_win_both_halves_yes_no_team,
  shared_market_corner_team_to_win_both_halves_yes_no_team,
  shared_market_offside_team_to_win_both_halves_yes_no_team,
  shared_market_foul_team_to_win_both_halves_yes_no_team,
  shared_market_shot_on_goal_team_to_win_both_halves_yes_no_team,
  shared_market_score_team_to_win_either_half_yes_no_team,
  shared_market_yellow_card_team_to_win_either_half_yes_no_team,
  shared_market_red_card_team_to_win_either_half_yes_no_team,
  shared_market_corner_team_to_win_either_half_yes_no_team,
  shared_market_offside_team_to_win_either_half_yes_no_team,
  shared_market_foul_team_to_win_either_half_yes_no_team,
  shared_market_shot_on_goal_team_to_win_either_half_yes_no_team,
  shared_market_score_team_to_win_by_exact_number_yes_no_team,
  shared_market_yellow_card_team_to_win_by_exact_number_yes_no_team,
  shared_market_red_card_team_to_win_by_exact_number_yes_no_team,
  shared_market_corner_team_to_win_by_exact_number_yes_no_team,
  shared_market_offside_team_to_win_by_exact_number_yes_no_team,
  shared_market_foul_team_to_win_by_exact_number_yes_no_team,
  shared_market_shot_on_goal_team_to_win_by_exact_number_yes_no_team,
  shared_market_score_team_to_win_by_exact_number_or_draw_yes_no_team,
  shared_market_yellow_card_team_to_win_by_exact_number_or_draw_yes_no_team,
  shared_market_red_card_team_to_win_by_exact_number_or_draw_yes_no_team,
  shared_market_corner_team_to_win_by_exact_number_or_draw_yes_no_team,
  shared_market_offside_team_to_win_by_exact_number_or_draw_yes_no_team,
  shared_market_foul_team_to_win_by_exact_number_or_draw_yes_no_team,
  shared_market_shot_on_goal_team_to_win_by_exact_number_or_draw_yes_no_team,
  shared_market_score_team_win_first_half_and_not_to_lose_yes_no_team,
  shared_market_yellow_card_team_win_first_half_and_not_to_lose_yes_no_team,
  shared_market_red_card_team_win_first_half_and_not_to_lose_yes_no_team,
  shared_market_corner_team_win_first_half_and_not_to_lose_yes_no_team,
  shared_market_offside_team_win_first_half_and_not_to_lose_yes_no_team,
  shared_market_foul_team_win_first_half_and_not_to_lose_yes_no_team,
  shared_market_shot_on_goal_team_win_first_half_and_not_to_lose_yes_no_team,
  shared_market_yellow_card_to_score_first,
  shared_market_red_card_to_score_first,
  shared_market_corner_to_score_first,
  shared_market_offside_to_score_first,
  shared_market_foul_to_score_first,
  shared_market_shot_on_goal_to_score_first,
  shared_market_score_to_score_x_in_range,
  shared_market_yellow_card_to_score_x_in_range,
  shared_market_red_card_to_score_x_in_range,
  shared_market_corner_to_score_x_in_range,
  shared_market_offside_to_score_x_in_range,
  shared_market_foul_to_score_x_in_range,
  shared_market_shot_on_goal_to_score_x_in_range,
  shared_market_yellow_card_to_score_last,
  shared_market_red_card_to_score_last,
  shared_market_corner_to_score_last,
  shared_market_offside_to_score_last,
  shared_market_foul_to_score_last,
  shared_market_shot_on_goal_to_score_last,
  shared_market_score_to_score_in_range,
  shared_market_yellow_card_to_score_in_range,
  shared_market_red_card_to_score_in_range,
  shared_market_corner_to_score_in_range,
  shared_market_offside_to_score_in_range,
  shared_market_foul_to_score_in_range,
  shared_market_shot_on_goal_to_score_in_range,
  shared_market_score_to_score_in_range_team,
  shared_market_yellow_card_to_score_in_range_team,
  shared_market_red_card_to_score_in_range_team,
  shared_market_corner_to_score_in_range_team,
  shared_market_offside_to_score_in_range_team,
  shared_market_foul_to_score_in_range_team,
  shared_market_shot_on_goal_to_score_in_range_team,
  shared_market_yellow_card_interval_1x2,
  shared_market_red_card_interval_1x2,
  shared_market_corner_interval_1x2,
  shared_market_offside_interval_1x2,
  shared_market_foul_interval_1x2,
  shared_market_shot_on_goal_interval_1x2,
  shared_market_yellow_card_interval_ah,
  shared_market_red_card_interval_ah,
  shared_market_corner_interval_ah,
  shared_market_offside_interval_ah,
  shared_market_foul_interval_ah,
  shared_market_shot_on_goal_interval_ah,
  shared_market_yellow_card_interval_ou,
  shared_market_red_card_interval_ou,
  shared_market_corner_interval_ou,
  shared_market_offside_interval_ou,
  shared_market_foul_interval_ou,
  shared_market_shot_on_goal_interval_ou,
  shared_market_yellow_card_interval_ou_team,
  shared_market_red_card_interval_ou_team,
  shared_market_corner_interval_ou_team,
  shared_market_offside_interval_ou_team,
  shared_market_foul_interval_ou_team,
  shared_market_shot_on_goal_interval_ou_team,
  shared_market_yellow_card_interval_dc,
  shared_market_red_card_interval_dc,
  shared_market_corner_interval_dc,
  shared_market_offside_interval_dc,
  shared_market_foul_interval_dc,
  shared_market_shot_on_goal_interval_dc,
  shared_market_score_to_score_x,
  shared_market_yellow_card_to_score_x,
  shared_market_red_card_to_score_x,
  shared_market_corner_to_score_x,
  shared_market_offside_to_score_x,
  shared_market_foul_to_score_x,
  shared_market_shot_on_goal_to_score_x,
  shared_market_score_both_to_score_and_win_team_yes_no,
  shared_market_yellow_card_both_to_score_and_win_team_yes_no,
  shared_market_red_card_both_to_score_and_win_team_yes_no,
  shared_market_corner_both_to_score_and_win_team_yes_no,
  shared_market_offside_both_to_score_and_win_team_yes_no,
  shared_market_foul_both_to_score_and_win_team_yes_no,
  shared_market_shot_on_goal_both_to_score_and_win_team_yes_no,
  shared_market_fact_custom,
  shared_market_fact_extra_inning_yes_no,
  shared_market_place_number_race_winner,
  shared_market_place_number_race_place,
  shared_market_place_number_race_show,
  shared_market_place_number_race_forecast,
  shared_market_place_number_race_reverse_forecast,
  shared_market_place_number_race_tricast,
  shared_market_place_number_race_reverse_tricast,
  shared_market_place_number_race_quarter,
  shared_market_place_number_race_swinger,
  shared_market_winner_number_race_odd_even_high_low,
  shared_market_winner_number_race_odd_even,
  shared_market_winner_number_race_high_low,
  shared_market_winner_number_race_pairs,
  shared_market_score_scopes_with_result,
  shared_market_score_scopes_with_total,
  shared_market_score_score_count,
  shared_market_score_roulette_odd_even,
  shared_market_score_roulette_red_black,
  shared_market_score_roulette_numbers,
  shared_market_place_number_racing_roulette_first,
  shared_market_place_number_racing_roulette_first_second,
  shared_market_place_number_racing_roulette_first_second_third,
  shared_market_place_number_racing_roulette_in_first_three,
  shared_market_place_number_racing_roulette_two_from_three,
  shared_market_score_keno_subset_in_set,
  shared_market_score_keno_heads_tails,
  shared_market_score_lucky_loot_first_balls,
  shared_market_score_lucky_loot_first_color,
  shared_market_score_lucky_loot_colors_count,
  shared_market_score_lucky_loot_sum_odd_even,
  shared_market_score_lucky_loot_sum_high_low,
  shared_market_score_lucky_loot_subset_in_set_strict,
} from "@sb/translates/shared/SharedTKeys";
import { EMarketType } from "../MarketType";

/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptMapGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.schema.sportsbook.SportsbookSchema
 */
export const marketTypeTKeys: Record<EMarketType, TSharedKey> = {
  [EMarketType.score_12]: shared_market_score_12,
  [EMarketType.score_some_lose_first_set_and_win_match_yes_no]: shared_market_score_some_lose_first_set_and_win_match_yes_no,
  [EMarketType.score_some_set_clean_win_in_match_yes_no]: shared_market_score_some_set_clean_win_in_match_yes_no,
  [EMarketType.score_highest_scopes_score]: shared_market_score_highest_scopes_score,
  [EMarketType.score_cs]: shared_market_score_cs,
  [EMarketType.score_odd_even]: shared_market_score_odd_even,
  [EMarketType.game_odd_even]: shared_market_game_odd_even,
  [EMarketType.score_ou]: shared_market_score_ou,
  [EMarketType.game_ou]: shared_market_game_ou,
  [EMarketType.score_ah]: shared_market_score_ah,
  [EMarketType.game_ah]: shared_market_game_ah,
  [EMarketType.score_ou_team]: shared_market_score_ou_team,
  [EMarketType.game_ou_team]: shared_market_game_ou_team,
  [EMarketType.score_odd_even_team]: shared_market_score_odd_even_team,
  [EMarketType.game_odd_even_team]: shared_market_game_odd_even_team,
  [EMarketType.game_u_win_team]: shared_market_game_u_win_team,
  [EMarketType.game_o_win_team]: shared_market_game_o_win_team,
  [EMarketType.score_to_score_first]: shared_market_score_to_score_first,
  [EMarketType.score_to_score_last]: shared_market_score_to_score_last,
  [EMarketType.score_highest_scope_score]: shared_market_score_highest_scope_score,
  [EMarketType.score_to_win_all_scopes_team_yes_no]: shared_market_score_to_win_all_scopes_team_yes_no,
  [EMarketType.score_team_to_win_both_halves_yes_no_team]: shared_market_score_team_to_win_both_halves_yes_no_team,
  [EMarketType.score_team_win_first_half_and_match_yes_no_team]: shared_market_score_team_win_first_half_and_match_yes_no_team,
  [EMarketType.score_team_win_first_quarter_and_match_yes_no_team]: shared_market_score_team_win_first_quarter_and_match_yes_no_team,
  [EMarketType.score_overtime_yes_no]: shared_market_score_overtime_yes_no,
  [EMarketType.score_winning_margin]: shared_market_score_winning_margin,
  [EMarketType.score_12_score]: shared_market_score_12_score,
  [EMarketType.score_odd_even_high_low]: shared_market_score_odd_even_high_low,
  [EMarketType.score_longest_consecutive]: shared_market_score_longest_consecutive,
  [EMarketType.score_to_score_race]: shared_market_score_to_score_race,
  [EMarketType.score_exact_number]: shared_market_score_exact_number,
  [EMarketType.point_odd_even]: shared_market_point_odd_even,
  [EMarketType.point_ou]: shared_market_point_ou,
  [EMarketType.point_ah]: shared_market_point_ah,
  [EMarketType.point_ou_team]: shared_market_point_ou_team,
  [EMarketType.point_odd_even_team]: shared_market_point_odd_even_team,
  [EMarketType.point_o_win_team]: shared_market_point_o_win_team,
  [EMarketType.point_u_win_team]: shared_market_point_u_win_team,
  [EMarketType.score_1x2]: shared_market_score_1x2,
  [EMarketType.score_interval_1x2]: shared_market_score_interval_1x2,
  [EMarketType.score_dc]: shared_market_score_dc,
  [EMarketType.score_interval_ah]: shared_market_score_interval_ah,
  [EMarketType.score_interval_ou]: shared_market_score_interval_ou,
  [EMarketType.score_interval_ou_team]: shared_market_score_interval_ou_team,
  [EMarketType.score_interval_dc]: shared_market_score_interval_dc,
  [EMarketType.score_u_win_team]: shared_market_score_u_win_team,
  [EMarketType.score_o_win_draw_team]: shared_market_score_o_win_draw_team,
  [EMarketType.score_o_win_team]: shared_market_score_o_win_team,
  [EMarketType.score_win_to_nil_team]: shared_market_score_win_to_nil_team,
  [EMarketType.score_range_number]: shared_market_score_range_number,
  [EMarketType.score_range_number_team]: shared_market_score_range_number_team,
  [EMarketType.score_range_number_yes_no]: shared_market_score_range_number_yes_no,
  [EMarketType.score_range_number_yes_no_team]: shared_market_score_range_number_yes_no_team,
  [EMarketType.score_ht_ft]: shared_market_score_ht_ft,
  [EMarketType.score_draw]: shared_market_score_draw,
  [EMarketType.score_both_to_score_yes_no]: shared_market_score_both_to_score_yes_no,
  [EMarketType.score_exact_number_team]: shared_market_score_exact_number_team,
  [EMarketType.score_exact_number_yes_no]: shared_market_score_exact_number_yes_no,
  [EMarketType.score_exact_number_yes_no_team]: shared_market_score_exact_number_yes_no_team,
  [EMarketType.score_win_most_periods]: shared_market_score_win_most_periods,
  [EMarketType.score_triple_result]: shared_market_score_triple_result,
  [EMarketType.yellow_card_1x2]: shared_market_yellow_card_1x2,
  [EMarketType.red_card_1x2]: shared_market_red_card_1x2,
  [EMarketType.corner_1x2]: shared_market_corner_1x2,
  [EMarketType.offside_1x2]: shared_market_offside_1x2,
  [EMarketType.foul_1x2]: shared_market_foul_1x2,
  [EMarketType.shot_on_goal_1x2]: shared_market_shot_on_goal_1x2,
  [EMarketType.score_1x2_ou]: shared_market_score_1x2_ou,
  [EMarketType.score_1x2_teams_to_score]: shared_market_score_1x2_teams_to_score,
  [EMarketType.score_1x2_early_payout]: shared_market_score_1x2_early_payout,
  [EMarketType.yellow_card_dc]: shared_market_yellow_card_dc,
  [EMarketType.red_card_dc]: shared_market_red_card_dc,
  [EMarketType.corner_dc]: shared_market_corner_dc,
  [EMarketType.offside_dc]: shared_market_offside_dc,
  [EMarketType.foul_dc]: shared_market_foul_dc,
  [EMarketType.shot_on_goal_dc]: shared_market_shot_on_goal_dc,
  [EMarketType.yellow_card_ah]: shared_market_yellow_card_ah,
  [EMarketType.red_card_ah]: shared_market_red_card_ah,
  [EMarketType.corner_ah]: shared_market_corner_ah,
  [EMarketType.offside_ah]: shared_market_offside_ah,
  [EMarketType.foul_ah]: shared_market_foul_ah,
  [EMarketType.shot_on_goal_ah]: shared_market_shot_on_goal_ah,
  [EMarketType.yellow_card_ou]: shared_market_yellow_card_ou,
  [EMarketType.red_card_ou]: shared_market_red_card_ou,
  [EMarketType.corner_ou]: shared_market_corner_ou,
  [EMarketType.offside_ou]: shared_market_offside_ou,
  [EMarketType.foul_ou]: shared_market_foul_ou,
  [EMarketType.shot_on_goal_ou]: shared_market_shot_on_goal_ou,
  [EMarketType.yellow_card_ou_team]: shared_market_yellow_card_ou_team,
  [EMarketType.red_card_ou_team]: shared_market_red_card_ou_team,
  [EMarketType.corner_ou_team]: shared_market_corner_ou_team,
  [EMarketType.offside_ou_team]: shared_market_offside_ou_team,
  [EMarketType.foul_ou_team]: shared_market_foul_ou_team,
  [EMarketType.shot_on_goal_ou_team]: shared_market_shot_on_goal_ou_team,
  [EMarketType.yellow_card_cs]: shared_market_yellow_card_cs,
  [EMarketType.red_card_cs]: shared_market_red_card_cs,
  [EMarketType.corner_cs]: shared_market_corner_cs,
  [EMarketType.offside_cs]: shared_market_offside_cs,
  [EMarketType.foul_cs]: shared_market_foul_cs,
  [EMarketType.shot_on_goal_cs]: shared_market_shot_on_goal_cs,
  [EMarketType.yellow_card_odd_even]: shared_market_yellow_card_odd_even,
  [EMarketType.red_card_odd_even]: shared_market_red_card_odd_even,
  [EMarketType.corner_odd_even]: shared_market_corner_odd_even,
  [EMarketType.offside_odd_even]: shared_market_offside_odd_even,
  [EMarketType.foul_odd_even]: shared_market_foul_odd_even,
  [EMarketType.shot_on_goal_odd_even]: shared_market_shot_on_goal_odd_even,
  [EMarketType.yellow_card_odd_even_team]: shared_market_yellow_card_odd_even_team,
  [EMarketType.red_card_odd_even_team]: shared_market_red_card_odd_even_team,
  [EMarketType.corner_odd_even_team]: shared_market_corner_odd_even_team,
  [EMarketType.offside_odd_even_team]: shared_market_offside_odd_even_team,
  [EMarketType.foul_odd_even_team]: shared_market_foul_odd_even_team,
  [EMarketType.shot_on_goal_odd_even_team]: shared_market_shot_on_goal_odd_even_team,
  [EMarketType.yellow_card_u_win_team]: shared_market_yellow_card_u_win_team,
  [EMarketType.red_card_u_win_team]: shared_market_red_card_u_win_team,
  [EMarketType.corner_u_win_team]: shared_market_corner_u_win_team,
  [EMarketType.offside_u_win_team]: shared_market_offside_u_win_team,
  [EMarketType.foul_u_win_team]: shared_market_foul_u_win_team,
  [EMarketType.shot_on_goal_u_win_team]: shared_market_shot_on_goal_u_win_team,
  [EMarketType.yellow_card_o_win_team]: shared_market_yellow_card_o_win_team,
  [EMarketType.red_card_o_win_team]: shared_market_red_card_o_win_team,
  [EMarketType.corner_o_win_team]: shared_market_corner_o_win_team,
  [EMarketType.offside_o_win_team]: shared_market_offside_o_win_team,
  [EMarketType.foul_o_win_team]: shared_market_foul_o_win_team,
  [EMarketType.shot_on_goal_o_win_team]: shared_market_shot_on_goal_o_win_team,
  [EMarketType.yellow_card_o_win_draw_team]: shared_market_yellow_card_o_win_draw_team,
  [EMarketType.red_card_o_win_draw_team]: shared_market_red_card_o_win_draw_team,
  [EMarketType.corner_o_win_draw_team]: shared_market_corner_o_win_draw_team,
  [EMarketType.offside_o_win_draw_team]: shared_market_offside_o_win_draw_team,
  [EMarketType.foul_o_win_draw_team]: shared_market_foul_o_win_draw_team,
  [EMarketType.shot_on_goal_o_win_draw_team]: shared_market_shot_on_goal_o_win_draw_team,
  [EMarketType.score_u_win_draw_team]: shared_market_score_u_win_draw_team,
  [EMarketType.yellow_card_u_win_draw_team]: shared_market_yellow_card_u_win_draw_team,
  [EMarketType.red_card_u_win_draw_team]: shared_market_red_card_u_win_draw_team,
  [EMarketType.corner_u_win_draw_team]: shared_market_corner_u_win_draw_team,
  [EMarketType.offside_u_win_draw_team]: shared_market_offside_u_win_draw_team,
  [EMarketType.foul_u_win_draw_team]: shared_market_foul_u_win_draw_team,
  [EMarketType.shot_on_goal_u_win_draw_team]: shared_market_shot_on_goal_u_win_draw_team,
  [EMarketType.score_u_draw]: shared_market_score_u_draw,
  [EMarketType.yellow_card_u_draw]: shared_market_yellow_card_u_draw,
  [EMarketType.red_card_u_draw]: shared_market_red_card_u_draw,
  [EMarketType.corner_u_draw]: shared_market_corner_u_draw,
  [EMarketType.offside_u_draw]: shared_market_offside_u_draw,
  [EMarketType.foul_u_draw]: shared_market_foul_u_draw,
  [EMarketType.shot_on_goal_u_draw]: shared_market_shot_on_goal_u_draw,
  [EMarketType.score_o_draw]: shared_market_score_o_draw,
  [EMarketType.yellow_card_o_draw]: shared_market_yellow_card_o_draw,
  [EMarketType.red_card_o_draw]: shared_market_red_card_o_draw,
  [EMarketType.corner_o_draw]: shared_market_corner_o_draw,
  [EMarketType.offside_o_draw]: shared_market_offside_o_draw,
  [EMarketType.foul_o_draw]: shared_market_foul_o_draw,
  [EMarketType.shot_on_goal_o_draw]: shared_market_shot_on_goal_o_draw,
  [EMarketType.yellow_card_win_to_nil_team]: shared_market_yellow_card_win_to_nil_team,
  [EMarketType.red_card_win_to_nil_team]: shared_market_red_card_win_to_nil_team,
  [EMarketType.corner_win_to_nil_team]: shared_market_corner_win_to_nil_team,
  [EMarketType.offside_win_to_nil_team]: shared_market_offside_win_to_nil_team,
  [EMarketType.foul_win_to_nil_team]: shared_market_foul_win_to_nil_team,
  [EMarketType.shot_on_goal_win_to_nil_team]: shared_market_shot_on_goal_win_to_nil_team,
  [EMarketType.yellow_card_range_number]: shared_market_yellow_card_range_number,
  [EMarketType.red_card_range_number]: shared_market_red_card_range_number,
  [EMarketType.corner_range_number]: shared_market_corner_range_number,
  [EMarketType.offside_range_number]: shared_market_offside_range_number,
  [EMarketType.foul_range_number]: shared_market_foul_range_number,
  [EMarketType.shot_on_goal_range_number]: shared_market_shot_on_goal_range_number,
  [EMarketType.yellow_card_range_number_team]: shared_market_yellow_card_range_number_team,
  [EMarketType.red_card_range_number_team]: shared_market_red_card_range_number_team,
  [EMarketType.corner_range_number_team]: shared_market_corner_range_number_team,
  [EMarketType.offside_range_number_team]: shared_market_offside_range_number_team,
  [EMarketType.foul_range_number_team]: shared_market_foul_range_number_team,
  [EMarketType.shot_on_goal_range_number_team]: shared_market_shot_on_goal_range_number_team,
  [EMarketType.yellow_card_range_number_yes_no]: shared_market_yellow_card_range_number_yes_no,
  [EMarketType.red_card_range_number_yes_no]: shared_market_red_card_range_number_yes_no,
  [EMarketType.corner_range_number_yes_no]: shared_market_corner_range_number_yes_no,
  [EMarketType.offside_range_number_yes_no]: shared_market_offside_range_number_yes_no,
  [EMarketType.foul_range_number_yes_no]: shared_market_foul_range_number_yes_no,
  [EMarketType.shot_on_goal_range_number_yes_no]: shared_market_shot_on_goal_range_number_yes_no,
  [EMarketType.yellow_card_range_number_yes_no_team]: shared_market_yellow_card_range_number_yes_no_team,
  [EMarketType.red_card_range_number_yes_no_team]: shared_market_red_card_range_number_yes_no_team,
  [EMarketType.corner_range_number_yes_no_team]: shared_market_corner_range_number_yes_no_team,
  [EMarketType.offside_range_number_yes_no_team]: shared_market_offside_range_number_yes_no_team,
  [EMarketType.foul_range_number_yes_no_team]: shared_market_foul_range_number_yes_no_team,
  [EMarketType.shot_on_goal_range_number_yes_no_team]: shared_market_shot_on_goal_range_number_yes_no_team,
  [EMarketType.yellow_card_ht_ft]: shared_market_yellow_card_ht_ft,
  [EMarketType.red_card_ht_ft]: shared_market_red_card_ht_ft,
  [EMarketType.corner_ht_ft]: shared_market_corner_ht_ft,
  [EMarketType.offside_ht_ft]: shared_market_offside_ht_ft,
  [EMarketType.foul_ht_ft]: shared_market_foul_ht_ft,
  [EMarketType.shot_on_goal_ht_ft]: shared_market_shot_on_goal_ht_ft,
  [EMarketType.yellow_card_draw]: shared_market_yellow_card_draw,
  [EMarketType.red_card_draw]: shared_market_red_card_draw,
  [EMarketType.corner_draw]: shared_market_corner_draw,
  [EMarketType.offside_draw]: shared_market_offside_draw,
  [EMarketType.foul_draw]: shared_market_foul_draw,
  [EMarketType.shot_on_goal_draw]: shared_market_shot_on_goal_draw,
  [EMarketType.yellow_card_both_to_score_yes_no]: shared_market_yellow_card_both_to_score_yes_no,
  [EMarketType.red_card_both_to_score_yes_no]: shared_market_red_card_both_to_score_yes_no,
  [EMarketType.corner_both_to_score_yes_no]: shared_market_corner_both_to_score_yes_no,
  [EMarketType.offside_both_to_score_yes_no]: shared_market_offside_both_to_score_yes_no,
  [EMarketType.foul_both_to_score_yes_no]: shared_market_foul_both_to_score_yes_no,
  [EMarketType.shot_on_goal_both_to_score_yes_no]: shared_market_shot_on_goal_both_to_score_yes_no,
  [EMarketType.yellow_card_exact_number]: shared_market_yellow_card_exact_number,
  [EMarketType.red_card_exact_number]: shared_market_red_card_exact_number,
  [EMarketType.corner_exact_number]: shared_market_corner_exact_number,
  [EMarketType.offside_exact_number]: shared_market_offside_exact_number,
  [EMarketType.foul_exact_number]: shared_market_foul_exact_number,
  [EMarketType.shot_on_goal_exact_number]: shared_market_shot_on_goal_exact_number,
  [EMarketType.yellow_card_exact_number_team]: shared_market_yellow_card_exact_number_team,
  [EMarketType.red_card_exact_number_team]: shared_market_red_card_exact_number_team,
  [EMarketType.corner_exact_number_team]: shared_market_corner_exact_number_team,
  [EMarketType.offside_exact_number_team]: shared_market_offside_exact_number_team,
  [EMarketType.foul_exact_number_team]: shared_market_foul_exact_number_team,
  [EMarketType.shot_on_goal_exact_number_team]: shared_market_shot_on_goal_exact_number_team,
  [EMarketType.yellow_card_exact_number_yes_no]: shared_market_yellow_card_exact_number_yes_no,
  [EMarketType.red_card_exact_number_yes_no]: shared_market_red_card_exact_number_yes_no,
  [EMarketType.corner_exact_number_yes_no]: shared_market_corner_exact_number_yes_no,
  [EMarketType.offside_exact_number_yes_no]: shared_market_offside_exact_number_yes_no,
  [EMarketType.foul_exact_number_yes_no]: shared_market_foul_exact_number_yes_no,
  [EMarketType.shot_on_goal_exact_number_yes_no]: shared_market_shot_on_goal_exact_number_yes_no,
  [EMarketType.yellow_card_exact_number_yes_no_team]: shared_market_yellow_card_exact_number_yes_no_team,
  [EMarketType.red_card_exact_number_yes_no_team]: shared_market_red_card_exact_number_yes_no_team,
  [EMarketType.corner_exact_number_yes_no_team]: shared_market_corner_exact_number_yes_no_team,
  [EMarketType.offside_exact_number_yes_no_team]: shared_market_offside_exact_number_yes_no_team,
  [EMarketType.foul_exact_number_yes_no_team]: shared_market_foul_exact_number_yes_no_team,
  [EMarketType.shot_on_goal_exact_number_yes_no_team]: shared_market_shot_on_goal_exact_number_yes_no_team,
  [EMarketType.score_team_to_score_yes_no_team]: shared_market_score_team_to_score_yes_no_team,
  [EMarketType.yellow_card_team_to_score_yes_no_team]: shared_market_yellow_card_team_to_score_yes_no_team,
  [EMarketType.red_card_team_to_score_yes_no_team]: shared_market_red_card_team_to_score_yes_no_team,
  [EMarketType.corner_team_to_score_yes_no_team]: shared_market_corner_team_to_score_yes_no_team,
  [EMarketType.offside_team_to_score_yes_no_team]: shared_market_offside_team_to_score_yes_no_team,
  [EMarketType.foul_team_to_score_yes_no_team]: shared_market_foul_team_to_score_yes_no_team,
  [EMarketType.shot_on_goal_team_to_score_yes_no_team]: shared_market_shot_on_goal_team_to_score_yes_no_team,
  [EMarketType.score_both_to_score_and_o_yes_no]: shared_market_score_both_to_score_and_o_yes_no,
  [EMarketType.yellow_card_both_to_score_and_o_yes_no]: shared_market_yellow_card_both_to_score_and_o_yes_no,
  [EMarketType.red_card_both_to_score_and_o_yes_no]: shared_market_red_card_both_to_score_and_o_yes_no,
  [EMarketType.corner_both_to_score_and_o_yes_no]: shared_market_corner_both_to_score_and_o_yes_no,
  [EMarketType.offside_both_to_score_and_o_yes_no]: shared_market_offside_both_to_score_and_o_yes_no,
  [EMarketType.foul_both_to_score_and_o_yes_no]: shared_market_foul_both_to_score_and_o_yes_no,
  [EMarketType.shot_on_goal_both_to_score_and_o_yes_no]: shared_market_shot_on_goal_both_to_score_and_o_yes_no,
  [EMarketType.score_both_to_score_and_u_yes_no]: shared_market_score_both_to_score_and_u_yes_no,
  [EMarketType.yellow_card_both_to_score_and_u_yes_no]: shared_market_yellow_card_both_to_score_and_u_yes_no,
  [EMarketType.red_card_both_to_score_and_u_yes_no]: shared_market_red_card_both_to_score_and_u_yes_no,
  [EMarketType.corner_both_to_score_and_u_yes_no]: shared_market_corner_both_to_score_and_u_yes_no,
  [EMarketType.offside_both_to_score_and_u_yes_no]: shared_market_offside_both_to_score_and_u_yes_no,
  [EMarketType.foul_both_to_score_and_u_yes_no]: shared_market_foul_both_to_score_and_u_yes_no,
  [EMarketType.shot_on_goal_both_to_score_and_u_yes_no]: shared_market_shot_on_goal_both_to_score_and_u_yes_no,
  [EMarketType.score_team_to_score_in_both_halves_yes_no_team]: shared_market_score_team_to_score_in_both_halves_yes_no_team,
  [EMarketType.yellow_card_team_to_score_in_both_halves_yes_no_team]: shared_market_yellow_card_team_to_score_in_both_halves_yes_no_team,
  [EMarketType.red_card_team_to_score_in_both_halves_yes_no_team]: shared_market_red_card_team_to_score_in_both_halves_yes_no_team,
  [EMarketType.corner_team_to_score_in_both_halves_yes_no_team]: shared_market_corner_team_to_score_in_both_halves_yes_no_team,
  [EMarketType.offside_team_to_score_in_both_halves_yes_no_team]: shared_market_offside_team_to_score_in_both_halves_yes_no_team,
  [EMarketType.foul_team_to_score_in_both_halves_yes_no_team]: shared_market_foul_team_to_score_in_both_halves_yes_no_team,
  [EMarketType.shot_on_goal_team_to_score_in_both_halves_yes_no_team]: shared_market_shot_on_goal_team_to_score_in_both_halves_yes_no_team,
  [EMarketType.yellow_card_team_to_win_both_halves_yes_no_team]: shared_market_yellow_card_team_to_win_both_halves_yes_no_team,
  [EMarketType.red_card_team_to_win_both_halves_yes_no_team]: shared_market_red_card_team_to_win_both_halves_yes_no_team,
  [EMarketType.corner_team_to_win_both_halves_yes_no_team]: shared_market_corner_team_to_win_both_halves_yes_no_team,
  [EMarketType.offside_team_to_win_both_halves_yes_no_team]: shared_market_offside_team_to_win_both_halves_yes_no_team,
  [EMarketType.foul_team_to_win_both_halves_yes_no_team]: shared_market_foul_team_to_win_both_halves_yes_no_team,
  [EMarketType.shot_on_goal_team_to_win_both_halves_yes_no_team]: shared_market_shot_on_goal_team_to_win_both_halves_yes_no_team,
  [EMarketType.score_team_to_win_either_half_yes_no_team]: shared_market_score_team_to_win_either_half_yes_no_team,
  [EMarketType.yellow_card_team_to_win_either_half_yes_no_team]: shared_market_yellow_card_team_to_win_either_half_yes_no_team,
  [EMarketType.red_card_team_to_win_either_half_yes_no_team]: shared_market_red_card_team_to_win_either_half_yes_no_team,
  [EMarketType.corner_team_to_win_either_half_yes_no_team]: shared_market_corner_team_to_win_either_half_yes_no_team,
  [EMarketType.offside_team_to_win_either_half_yes_no_team]: shared_market_offside_team_to_win_either_half_yes_no_team,
  [EMarketType.foul_team_to_win_either_half_yes_no_team]: shared_market_foul_team_to_win_either_half_yes_no_team,
  [EMarketType.shot_on_goal_team_to_win_either_half_yes_no_team]: shared_market_shot_on_goal_team_to_win_either_half_yes_no_team,
  [EMarketType.score_team_to_win_by_exact_number_yes_no_team]: shared_market_score_team_to_win_by_exact_number_yes_no_team,
  [EMarketType.yellow_card_team_to_win_by_exact_number_yes_no_team]: shared_market_yellow_card_team_to_win_by_exact_number_yes_no_team,
  [EMarketType.red_card_team_to_win_by_exact_number_yes_no_team]: shared_market_red_card_team_to_win_by_exact_number_yes_no_team,
  [EMarketType.corner_team_to_win_by_exact_number_yes_no_team]: shared_market_corner_team_to_win_by_exact_number_yes_no_team,
  [EMarketType.offside_team_to_win_by_exact_number_yes_no_team]: shared_market_offside_team_to_win_by_exact_number_yes_no_team,
  [EMarketType.foul_team_to_win_by_exact_number_yes_no_team]: shared_market_foul_team_to_win_by_exact_number_yes_no_team,
  [EMarketType.shot_on_goal_team_to_win_by_exact_number_yes_no_team]: shared_market_shot_on_goal_team_to_win_by_exact_number_yes_no_team,
  [EMarketType.score_team_to_win_by_exact_number_or_draw_yes_no_team]: shared_market_score_team_to_win_by_exact_number_or_draw_yes_no_team,
  [EMarketType.yellow_card_team_to_win_by_exact_number_or_draw_yes_no_team]: shared_market_yellow_card_team_to_win_by_exact_number_or_draw_yes_no_team,
  [EMarketType.red_card_team_to_win_by_exact_number_or_draw_yes_no_team]: shared_market_red_card_team_to_win_by_exact_number_or_draw_yes_no_team,
  [EMarketType.corner_team_to_win_by_exact_number_or_draw_yes_no_team]: shared_market_corner_team_to_win_by_exact_number_or_draw_yes_no_team,
  [EMarketType.offside_team_to_win_by_exact_number_or_draw_yes_no_team]: shared_market_offside_team_to_win_by_exact_number_or_draw_yes_no_team,
  [EMarketType.foul_team_to_win_by_exact_number_or_draw_yes_no_team]: shared_market_foul_team_to_win_by_exact_number_or_draw_yes_no_team,
  [EMarketType.shot_on_goal_team_to_win_by_exact_number_or_draw_yes_no_team]: shared_market_shot_on_goal_team_to_win_by_exact_number_or_draw_yes_no_team,
  [EMarketType.score_team_win_first_half_and_not_to_lose_yes_no_team]: shared_market_score_team_win_first_half_and_not_to_lose_yes_no_team,
  [EMarketType.yellow_card_team_win_first_half_and_not_to_lose_yes_no_team]: shared_market_yellow_card_team_win_first_half_and_not_to_lose_yes_no_team,
  [EMarketType.red_card_team_win_first_half_and_not_to_lose_yes_no_team]: shared_market_red_card_team_win_first_half_and_not_to_lose_yes_no_team,
  [EMarketType.corner_team_win_first_half_and_not_to_lose_yes_no_team]: shared_market_corner_team_win_first_half_and_not_to_lose_yes_no_team,
  [EMarketType.offside_team_win_first_half_and_not_to_lose_yes_no_team]: shared_market_offside_team_win_first_half_and_not_to_lose_yes_no_team,
  [EMarketType.foul_team_win_first_half_and_not_to_lose_yes_no_team]: shared_market_foul_team_win_first_half_and_not_to_lose_yes_no_team,
  [EMarketType.shot_on_goal_team_win_first_half_and_not_to_lose_yes_no_team]: shared_market_shot_on_goal_team_win_first_half_and_not_to_lose_yes_no_team,
  [EMarketType.yellow_card_to_score_first]: shared_market_yellow_card_to_score_first,
  [EMarketType.red_card_to_score_first]: shared_market_red_card_to_score_first,
  [EMarketType.corner_to_score_first]: shared_market_corner_to_score_first,
  [EMarketType.offside_to_score_first]: shared_market_offside_to_score_first,
  [EMarketType.foul_to_score_first]: shared_market_foul_to_score_first,
  [EMarketType.shot_on_goal_to_score_first]: shared_market_shot_on_goal_to_score_first,
  [EMarketType.score_to_score_x_in_range]: shared_market_score_to_score_x_in_range,
  [EMarketType.yellow_card_to_score_x_in_range]: shared_market_yellow_card_to_score_x_in_range,
  [EMarketType.red_card_to_score_x_in_range]: shared_market_red_card_to_score_x_in_range,
  [EMarketType.corner_to_score_x_in_range]: shared_market_corner_to_score_x_in_range,
  [EMarketType.offside_to_score_x_in_range]: shared_market_offside_to_score_x_in_range,
  [EMarketType.foul_to_score_x_in_range]: shared_market_foul_to_score_x_in_range,
  [EMarketType.shot_on_goal_to_score_x_in_range]: shared_market_shot_on_goal_to_score_x_in_range,
  [EMarketType.yellow_card_to_score_last]: shared_market_yellow_card_to_score_last,
  [EMarketType.red_card_to_score_last]: shared_market_red_card_to_score_last,
  [EMarketType.corner_to_score_last]: shared_market_corner_to_score_last,
  [EMarketType.offside_to_score_last]: shared_market_offside_to_score_last,
  [EMarketType.foul_to_score_last]: shared_market_foul_to_score_last,
  [EMarketType.shot_on_goal_to_score_last]: shared_market_shot_on_goal_to_score_last,
  [EMarketType.score_to_score_in_range]: shared_market_score_to_score_in_range,
  [EMarketType.yellow_card_to_score_in_range]: shared_market_yellow_card_to_score_in_range,
  [EMarketType.red_card_to_score_in_range]: shared_market_red_card_to_score_in_range,
  [EMarketType.corner_to_score_in_range]: shared_market_corner_to_score_in_range,
  [EMarketType.offside_to_score_in_range]: shared_market_offside_to_score_in_range,
  [EMarketType.foul_to_score_in_range]: shared_market_foul_to_score_in_range,
  [EMarketType.shot_on_goal_to_score_in_range]: shared_market_shot_on_goal_to_score_in_range,
  [EMarketType.score_to_score_in_range_team]: shared_market_score_to_score_in_range_team,
  [EMarketType.yellow_card_to_score_in_range_team]: shared_market_yellow_card_to_score_in_range_team,
  [EMarketType.red_card_to_score_in_range_team]: shared_market_red_card_to_score_in_range_team,
  [EMarketType.corner_to_score_in_range_team]: shared_market_corner_to_score_in_range_team,
  [EMarketType.offside_to_score_in_range_team]: shared_market_offside_to_score_in_range_team,
  [EMarketType.foul_to_score_in_range_team]: shared_market_foul_to_score_in_range_team,
  [EMarketType.shot_on_goal_to_score_in_range_team]: shared_market_shot_on_goal_to_score_in_range_team,
  [EMarketType.yellow_card_interval_1x2]: shared_market_yellow_card_interval_1x2,
  [EMarketType.red_card_interval_1x2]: shared_market_red_card_interval_1x2,
  [EMarketType.corner_interval_1x2]: shared_market_corner_interval_1x2,
  [EMarketType.offside_interval_1x2]: shared_market_offside_interval_1x2,
  [EMarketType.foul_interval_1x2]: shared_market_foul_interval_1x2,
  [EMarketType.shot_on_goal_interval_1x2]: shared_market_shot_on_goal_interval_1x2,
  [EMarketType.yellow_card_interval_ah]: shared_market_yellow_card_interval_ah,
  [EMarketType.red_card_interval_ah]: shared_market_red_card_interval_ah,
  [EMarketType.corner_interval_ah]: shared_market_corner_interval_ah,
  [EMarketType.offside_interval_ah]: shared_market_offside_interval_ah,
  [EMarketType.foul_interval_ah]: shared_market_foul_interval_ah,
  [EMarketType.shot_on_goal_interval_ah]: shared_market_shot_on_goal_interval_ah,
  [EMarketType.yellow_card_interval_ou]: shared_market_yellow_card_interval_ou,
  [EMarketType.red_card_interval_ou]: shared_market_red_card_interval_ou,
  [EMarketType.corner_interval_ou]: shared_market_corner_interval_ou,
  [EMarketType.offside_interval_ou]: shared_market_offside_interval_ou,
  [EMarketType.foul_interval_ou]: shared_market_foul_interval_ou,
  [EMarketType.shot_on_goal_interval_ou]: shared_market_shot_on_goal_interval_ou,
  [EMarketType.yellow_card_interval_ou_team]: shared_market_yellow_card_interval_ou_team,
  [EMarketType.red_card_interval_ou_team]: shared_market_red_card_interval_ou_team,
  [EMarketType.corner_interval_ou_team]: shared_market_corner_interval_ou_team,
  [EMarketType.offside_interval_ou_team]: shared_market_offside_interval_ou_team,
  [EMarketType.foul_interval_ou_team]: shared_market_foul_interval_ou_team,
  [EMarketType.shot_on_goal_interval_ou_team]: shared_market_shot_on_goal_interval_ou_team,
  [EMarketType.yellow_card_interval_dc]: shared_market_yellow_card_interval_dc,
  [EMarketType.red_card_interval_dc]: shared_market_red_card_interval_dc,
  [EMarketType.corner_interval_dc]: shared_market_corner_interval_dc,
  [EMarketType.offside_interval_dc]: shared_market_offside_interval_dc,
  [EMarketType.foul_interval_dc]: shared_market_foul_interval_dc,
  [EMarketType.shot_on_goal_interval_dc]: shared_market_shot_on_goal_interval_dc,
  [EMarketType.score_to_score_x]: shared_market_score_to_score_x,
  [EMarketType.yellow_card_to_score_x]: shared_market_yellow_card_to_score_x,
  [EMarketType.red_card_to_score_x]: shared_market_red_card_to_score_x,
  [EMarketType.corner_to_score_x]: shared_market_corner_to_score_x,
  [EMarketType.offside_to_score_x]: shared_market_offside_to_score_x,
  [EMarketType.foul_to_score_x]: shared_market_foul_to_score_x,
  [EMarketType.shot_on_goal_to_score_x]: shared_market_shot_on_goal_to_score_x,
  [EMarketType.score_both_to_score_and_win_team_yes_no]: shared_market_score_both_to_score_and_win_team_yes_no,
  [EMarketType.yellow_card_both_to_score_and_win_team_yes_no]: shared_market_yellow_card_both_to_score_and_win_team_yes_no,
  [EMarketType.red_card_both_to_score_and_win_team_yes_no]: shared_market_red_card_both_to_score_and_win_team_yes_no,
  [EMarketType.corner_both_to_score_and_win_team_yes_no]: shared_market_corner_both_to_score_and_win_team_yes_no,
  [EMarketType.offside_both_to_score_and_win_team_yes_no]: shared_market_offside_both_to_score_and_win_team_yes_no,
  [EMarketType.foul_both_to_score_and_win_team_yes_no]: shared_market_foul_both_to_score_and_win_team_yes_no,
  [EMarketType.shot_on_goal_both_to_score_and_win_team_yes_no]: shared_market_shot_on_goal_both_to_score_and_win_team_yes_no,
  [EMarketType.fact_custom]: shared_market_fact_custom,
  [EMarketType.fact_extra_inning_yes_no]: shared_market_fact_extra_inning_yes_no,
  [EMarketType.place_number_race_winner]: shared_market_place_number_race_winner,
  [EMarketType.place_number_race_place]: shared_market_place_number_race_place,
  [EMarketType.place_number_race_show]: shared_market_place_number_race_show,
  [EMarketType.place_number_race_forecast]: shared_market_place_number_race_forecast,
  [EMarketType.place_number_race_reverse_forecast]: shared_market_place_number_race_reverse_forecast,
  [EMarketType.place_number_race_tricast]: shared_market_place_number_race_tricast,
  [EMarketType.place_number_race_reverse_tricast]: shared_market_place_number_race_reverse_tricast,
  [EMarketType.place_number_race_quarter]: shared_market_place_number_race_quarter,
  [EMarketType.place_number_race_swinger]: shared_market_place_number_race_swinger,
  [EMarketType.winner_number_race_odd_even_high_low]: shared_market_winner_number_race_odd_even_high_low,
  [EMarketType.winner_number_race_odd_even]: shared_market_winner_number_race_odd_even,
  [EMarketType.winner_number_race_high_low]: shared_market_winner_number_race_high_low,
  [EMarketType.winner_number_race_pairs]: shared_market_winner_number_race_pairs,
  [EMarketType.score_scopes_with_result]: shared_market_score_scopes_with_result,
  [EMarketType.score_scopes_with_total]: shared_market_score_scopes_with_total,
  [EMarketType.score_score_count]: shared_market_score_score_count,
  [EMarketType.score_roulette_odd_even]: shared_market_score_roulette_odd_even,
  [EMarketType.score_roulette_red_black]: shared_market_score_roulette_red_black,
  [EMarketType.score_roulette_numbers]: shared_market_score_roulette_numbers,
  [EMarketType.place_number_racing_roulette_first]: shared_market_place_number_racing_roulette_first,
  [EMarketType.place_number_racing_roulette_first_second]: shared_market_place_number_racing_roulette_first_second,
  [EMarketType.place_number_racing_roulette_first_second_third]: shared_market_place_number_racing_roulette_first_second_third,
  [EMarketType.place_number_racing_roulette_in_first_three]: shared_market_place_number_racing_roulette_in_first_three,
  [EMarketType.place_number_racing_roulette_two_from_three]: shared_market_place_number_racing_roulette_two_from_three,
  [EMarketType.score_keno_subset_in_set]: shared_market_score_keno_subset_in_set,
  [EMarketType.score_keno_heads_tails]: shared_market_score_keno_heads_tails,
  [EMarketType.score_lucky_loot_first_balls]: shared_market_score_lucky_loot_first_balls,
  [EMarketType.score_lucky_loot_first_color]: shared_market_score_lucky_loot_first_color,
  [EMarketType.score_lucky_loot_colors_count]: shared_market_score_lucky_loot_colors_count,
  [EMarketType.score_lucky_loot_sum_odd_even]: shared_market_score_lucky_loot_sum_odd_even,
  [EMarketType.score_lucky_loot_sum_high_low]: shared_market_score_lucky_loot_sum_high_low,
  [EMarketType.score_lucky_loot_subset_in_set_strict]: shared_market_score_lucky_loot_subset_in_set_strict,
};
