/* eslint-disable */
// @ts-nocheck
import { TCashOutAvailableMarketsMap } from "./TCashOutAvailableMarketsMap";

/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptJsonGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.CashOutAvailableMarketsSource
 */
const cashOutAvailableMarkets: TCashOutAvailableMarketsMap = {
  "d6934640-cf1d-11e9-864b-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ou",
      "score_dc",
      "score_ou_team",
      "score_ah"
    ]
  },
  "d69250c8-cf1d-11e9-b1d7-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_ou_team"
    ]
  },
  "d693645e-cf1d-11e9-82b4-0242ac13000a": {
    "full_event": [
      "score_12",
      "point_ah",
      "score_ah",
      "point_ou",
      "score_ou"
    ]
  }
};

export { cashOutAvailableMarkets };
