/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.platform.callrequest.api.model.CallOptionName
 */
export enum ECallOptionName {
  MOBILE = "MOBILE",
  FACEBOOK = "FACEBOOK",
  INSTAGRAM = "INSTAGRAM",
  SIGNAL = "SIGNAL",
  SKYPE = "SKYPE",
  TELEGRAM = "TELEGRAM",
  TWITTER = "TWITTER",
  WHATSAPP = "WHATSAPP",
  GOOGLE_MEET = "GOOGLE_MEET",
  FACE_TIME = "FACE_TIME",
}
