/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.ChangeTypeSource
 */
export enum EChangeType {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  REMOVE = "REMOVE",
}
