/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.EventStatusSource
 */
export enum EEventStatus {
  not_started = "not_started",
  in_progress = "in_progress",
  finished = "finished",
  cancelled = "cancelled",
  interrupted = "interrupted",
  postponed = "postponed",
  retired = "retired",
  corrupted = "corrupted",
}
