/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.gamepage.GamePage
 */
export enum EGamePage {
  LIVE_CASINO = "LIVE_CASINO",
  CASINO = "CASINO",
  GAMES = "GAMES",
  VIRTUAL = "VIRTUAL",
}
