/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.MarketParameterSource
 */
export enum EMarketParameter {
  interval_from = "interval_from",
  interval_to = "interval_to",
  from = "from",
  to = "to",
  handicap = "handicap",
  total = "total",
  team = "team",
  score = "score",
  number = "number",
  predicate = "predicate",
  scopeType = "scopeType",
  color = "color",
  id = "id",
  rp = "rp",
  sd = "sd",
}
