/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.MarketColorSource
 */
export enum EMarketColor {
  red = "red",
  black = "black",
  green = "green",
  yellow = "yellow",
  blue = "blue",
}
