/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.OutcomeEnumValueSource
 */
export enum EOutcomeEnumValue {
  draw = "draw",
  no_draw = "no_draw",
  yes = "yes",
  no = "no",
  over = "over",
  under = "under",
  even = "even",
  odd = "odd",
  draw_over = "draw_over",
  draw_under = "draw_under",
  high = "high",
  low = "low",
  odd_low = "odd_low",
  odd_high = "odd_high",
  even_low = "even_low",
  even_high = "even_high",
  red = "red",
  black = "black",
  green = "green",
  yellow = "yellow",
  blue = "blue",
  heads = "heads",
  tails = "tails",
  evens = "evens",
  equal = "equal",
  draw_both = "draw_both",
  draw_none = "draw_none",
  both = "both",
}
