/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.OutcomeResultSource
 */
export enum EOutcomeResult {
  no_result = "no_result",
  win = "win",
  loss = "loss",
  half_win = "half_win",
  half_loss = "half_loss",
  void = "void",
  _return = "_return",
  partial_win = "partial_win",
}
