/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.OutcomeKindSource
 */
export enum EOutcomeKind {
  id = "id",
  enum = "enum",
  id_enum = "id_enum",
  key_id = "key_id",
  value = "value",
  multi_value = "multi_value",
  htft = "htft",
  range = "range",
  _name = "_name",
  id_sequence = "id_sequence",
  id_sequence_double = "id_sequence_double",
  id_sequence_triple = "id_sequence_triple",
  period123 = "period123",
  value_sequence = "value_sequence",
  id_id = "id_id",
  custom = "custom",
}
