/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.OutrightTypeSource
 */
export enum EOutrightType {
  winner = "winner",
  winner_yes_no = "winner_yes_no",
}
