/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.ParticipantShortIdSource
 */
export enum EParticipantShortId {
  p1 = "p1",
  p2 = "p2",
  p3 = "p3",
  p4 = "p4",
  p5 = "p5",
  p6 = "p6",
  p7 = "p7",
  p8 = "p8",
  p9 = "p9",
  p10 = "p10",
  p11 = "p11",
  p12 = "p12",
  p13 = "p13",
  p14 = "p14",
  p15 = "p15",
  p16 = "p16",
  p17 = "p17",
  p18 = "p18",
  p19 = "p19",
  p20 = "p20",
}
