/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.ParticipantTypeSource
 */
export enum EParticipantType {
  team1 = "team1",
  team2 = "team2",
  team3 = "team3",
  team4 = "team4",
  team5 = "team5",
  team6 = "team6",
  team7 = "team7",
  team8 = "team8",
  team9 = "team9",
  team10 = "team10",
  team11 = "team11",
  team12 = "team12",
  team13 = "team13",
  team14 = "team14",
  team15 = "team15",
  team16 = "team16",
  team17 = "team17",
  team18 = "team18",
  team19 = "team19",
  team20 = "team20",
}
