/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.provider.ProductCode
 */
export enum EProductCode {
  SPORTS = "SPORTS",
  ESPORTS = "ESPORTS",
  VIRTUAL = "VIRTUAL",
  GAMES = "GAMES",
  LIVE_CASINO = "LIVE_CASINO",
  CASINO = "CASINO",
  BET_EXCHANGE = "BET_EXCHANGE",
  PAYMENT = "PAYMENT",
  BONUS = "BONUS",
  AFFILIATE = "AFFILIATE",
  VIP_CLUB = "VIP_CLUB",
  RAIN = "RAIN",
  AGENT = "AGENT",
  TOURNAMENT = "TOURNAMENT",
}
