/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.ScopeTypeSource
 */
export enum EScopeType {
  unknown = "unknown",
  half = "half",
  full_event = "full_event",
  normal_time = "normal_time",
  period = "period",
  over_times = "over_times",
  over_time = "over_time",
  penalties = "penalties",
  penalty = "penalty",
  quarter = "quarter",
  set = "set",
  game = "game",
  frame = "frame",
  round = "round",
  inning = "inning",
  sudden_death = "sudden_death",
  kicking_competition = "kicking_competition",
  half_time = "half_time",
  half_time_overtime = "half_time_overtime",
  end_break = "end_break",
  set_break = "set_break",
  time_out = "time_out",
  technical_time_out = "technical_time_out",
  medical_time_out = "medical_time_out",
  quarter_break = "quarter_break",
  overtime_break = "overtime_break",
  intermission = "intermission",
  pause = "pause",
  interval = "interval",
  lunch_break = "lunch_break",
  tea_break = "tea_break",
  break = "break",
  rest = "rest",
  change_ends = "change_ends",
  map = "map",
  extra_inning = "extra_inning",
}
