/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.ScoreTypeSource
 */
export enum EScoreType {
  score = "score",
  yellow_card = "yellow_card",
  red_card = "red_card",
  corner = "corner",
  offside = "offside",
  time = "time",
  point = "point",
  game = "game",
  shot_on_goal = "shot_on_goal",
  foul = "foul",
  winner_number = "winner_number",
  place_number = "place_number",
  fact = "fact",
}
