/* eslint-disable */
// @ts-nocheck
/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptJsonGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.schema.mainline.MainLineSchema
 */
const mainLineSchema = {
  "d691b7ee-cf1d-11e9-a00f-0242ac13000a": {},
  "d691ecc8-cf1d-11e9-a78c-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d691f9fc-cf1d-11e9-b13b-0242ac13000a": {},
  "d69204f6-cf1d-11e9-9123-0242ac13000a": {
    "full_event": [
      "score_12"
    ]
  },
  "d6921df6-cf1d-11e9-8d12-0242ac13000a": {},
  "d6922ab2-cf1d-11e9-9ad4-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d69239b2-cf1d-11e9-90e6-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d6924664-cf1d-11e9-848a-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d69250c8-cf1d-11e9-b1d7-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d6925dc0-cf1d-11e9-b60e-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d69267de-cf1d-11e9-b8ad-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d69271f2-cf1d-11e9-84d6-0242ac13000a": {},
  "d6927b52-cf1d-11e9-a4a2-0242ac13000a": {},
  "d6928606-cf1d-11e9-878b-0242ac13000a": {},
  "d6929204-cf1d-11e9-aed5-0242ac13000a": {
    "full_event": [
      "score_12"
    ]
  },
  "d6929b82-cf1d-11e9-a89e-0242ac13000a": {},
  "d692a4ec-cf1d-11e9-91b2-0242ac13000a": {},
  "d692af28-cf1d-11e9-9790-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d692b93c-cf1d-11e9-a996-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d692c346-cf1d-11e9-b5fb-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d692cd5a-cf1d-11e9-b9d7-0242ac13000a": {},
  "d692d764-cf1d-11e9-90f1-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d692e16e-cf1d-11e9-bfdf-0242ac13000a": {},
  "d692eb78-cf1d-11e9-b183-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d692f582-cf1d-11e9-a815-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d692ff96-cf1d-11e9-a3f3-0242ac13000a": {},
  "d69309a0-cf1d-11e9-bfa6-0242ac13000a": {},
  "d69313aa-cf1d-11e9-adb0-0242ac13000a": {},
  "d6931db4-cf1d-11e9-af54-0242ac13000a": {
    "normal_time": [
      "score_1x2"
    ]
  },
  "d6933222-cf1d-11e9-890c-0242ac13000a": {},
  "d6933c2c-cf1d-11e9-9e86-0242ac13000a": {
    "full_event": [
      "score_1x2",
      "score_ou",
      "score_dc"
    ]
  },
  "d6934640-cf1d-11e9-864b-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d693504a-cf1d-11e9-b002-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d6935a54-cf1d-11e9-978e-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d693645e-cf1d-11e9-82b4-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d6936e72-cf1d-11e9-bfab-0242ac13000a": {
    "full_event": [
      "score_12",
      "score_ah",
      "score_ou",
      "score_odd_even"
    ]
  },
  "d693787c-cf1d-11e9-9c02-0242ac13000a": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "d6938286-cf1d-11e9-9e37-0242ac13000a": {},
  "d6938c90-cf1d-11e9-b350-0242ac13000a": {},
  "d69396a4-cf1d-11e9-90ca-0242ac13000a": {},
  "d693a0b8-cf1d-11e9-8886-0242ac13000a": {},
  "d693aac2-cf1d-11e9-89ff-0242ac13000a": {},
  "d693b5bc-cf1d-11e9-9d1e-0242ac13000a": {},
  "d693c048-cf1d-11e9-8032-0242ac13000a": {},
  "d693cab6-cf1d-11e9-8f30-0242ac13000a": {},
  "d693d4e8-cf1d-11e9-b511-0242ac13000a": {},
  "d693df60-cf1d-11e9-9269-0242ac13000a": {},
  "f07966d8-1922-467d-96fb-727929358052": {},
  "d693ea0a-cf1d-11e9-af98-0242ac13000a": {},
  "d693f428-cf1d-11e9-a2d1-0242ac13000a": {},
  "d693fe32-cf1d-11e9-9774-0242ac13000a": {},
  "d6940882-cf1d-11e9-9415-0242ac13000a": {},
  "d6941296-cf1d-11e9-9be5-0242ac13000a": {},
  "d6941ca0-cf1d-11e9-a9a1-0242ac13000a": {},
  "d69426b4-cf1d-11e9-85be-0242ac13000a": {},
  "d69430be-cf1d-11e9-85f7-0242ac13000a": {},
  "d6943ad2-cf1d-11e9-b058-0242ac13000a": {},
  "d69444dc-cf1d-11e9-9192-0242ac13000a": {},
  "d6944ef0-cf1d-11e9-b474-0242ac13000a": {},
  "d6945936-cf1d-11e9-9307-0242ac13000a": {},
  "d69463a4-cf1d-11e9-b57b-0242ac13000a": {},
  "d6946dd6-cf1d-11e9-a550-0242ac13000a": {},
  "d69477e0-cf1d-11e9-8a21-0242ac13000a": {},
  "d69481ea-cf1d-11e9-80a0-0242ac13000a": {},
  "d6948c08-cf1d-11e9-880f-0242ac13000a": {},
  "d6949612-cf1d-11e9-a369-0242ac13000a": {},
  "52f52572-f67f-11e9-9a01-f01898ec59ee": {},
  "52f52608-f67f-11e9-9a01-f01898ec59ee": {},
  "2009e404-f67f-11e9-a05a-f01898ec59ee": {},
  "200a0d94-f67f-11e9-a10f-f01898ec59ee": {},
  "4a2c3ff7-cf0c-4438-bc3a-01ab75b6d4ec": {
    "full_event": [
      "score_1x2"
    ]
  },
  "8db46e9b-b252-423b-a07f-b8379c9799eb": {
    "full_event": [
      "score_12"
    ]
  },
  "4dc3ac2f-c8ab-4aef-a369-6700a72ea63d": {
    "full_event": [
      "score_1x2"
    ]
  },
  "d15083fa-81ac-4395-be69-54ff56a3ef59": {
    "full_event": [
      "score_12"
    ]
  },
  "ac3afc6b-4cc5-44f7-9742-5722942bd651": {
    "full_event": [
      "score_12"
    ]
  },
  "4be04662-eba6-4a45-8ff9-4866869215da": {
    "full_event": [
      "score_12"
    ]
  },
  "82c462f6-5e53-4b43-ae41-c53865311439": {
    "full_event": [
      "score_12"
    ]
  },
  "bbe839ec-3e55-4746-9de4-56bf367dd3c9": {
    "full_event": [
      "score_12"
    ]
  },
  "27cbd9ad-fd35-420d-9ccd-ea2c04eb50cf": {
    "full_event": [
      "score_12"
    ]
  },
  "5b926879-bb7d-4c28-b0bd-742107ec02ba": {
    "full_event": [
      "score_12"
    ]
  },
  "9f4b280e-d19d-43df-bfaa-ff500b221294": {
    "normal_time": [
      "score_1x2"
    ]
  },
  "fb6d3b06-0c0d-4a9e-b612-2c41bf08807f": {
    "full_event": [
      "score_12"
    ]
  },
  "d81efba4-608f-4b4e-be63-d93732f5cb96": {
    "normal_time": [
      "score_1x2"
    ]
  },
  "4e8d5ce3-97e2-4035-a4ed-3b81eab2c31b": {
    "full_event": [
      "score_12"
    ]
  },
  "6c7d15b9-1c79-4ba4-8a40-9b5e55c5a8da": {
    "full_event": [
      "score_12"
    ]
  },
  "befda60a-c8d7-4dc4-94e9-23ad059d164c": {
    "full_event": [
      "winner_number_race_odd_even",
      "winner_number_race_high_low",
      "winner_number_race_odd_even_high_low"
    ]
  },
  "29d699ca-38ef-4ec6-8ddd-08a890ec13ba": {
    "full_event": [
      "winner_number_race_odd_even",
      "winner_number_race_high_low",
      "winner_number_race_odd_even_high_low"
    ]
  },
  "43f82846-eed2-485b-87b6-bfc8de5b9854": {
    "full_event": [
      "winner_number_race_odd_even",
      "winner_number_race_high_low",
      "winner_number_race_odd_even_high_low"
    ]
  },
  "14282c50-32ea-4ae5-aecf-15b907ce751e": {
    "full_event": [
      "winner_number_race_odd_even",
      "winner_number_race_high_low",
      "winner_number_race_odd_even_high_low"
    ]
  },
  "c0bd7cd7-2f15-4e10-bbec-fd699be5d296": {
    "full_event": [
      "winner_number_race_odd_even",
      "winner_number_race_high_low",
      "winner_number_race_odd_even_high_low"
    ]
  },
  "60b9e9c2-8952-4663-8cc1-121c6828b61e": {
    "normal_time": [
      "score_1x2",
      "score_ah",
      "score_ou",
      "score_dc",
      "score_odd_even"
    ]
  },
  "520ab8f7-87b4-41bd-b004-3667e46d1789": {
    "normal_time": [
      "score_1x2",
      "score_ou"
    ],
    "full_event": [
      "score_12"
    ]
  },
  "e1e78fb9-0e4e-4f70-9f56-f2495516e513": {
    "full_event": [
      "score_12",
      "score_12_score"
    ]
  },
  "1da0f5f1-daf2-4c69-baf5-4ae2f266e5f4": {
    "normal_time": [
      "score_12"
    ]
  },
  "cf0cb942-1ee0-4526-9b48-d4eb54a7720a": {
    "normal_time": [
      "score_1x2"
    ]
  },
  "4a8f699c-296e-4ff0-8aeb-a3f67c1bb91f": {},
  "27d667e3-8260-4afb-9ee3-d520c825940d": {},
  "5da5ed87-b43e-4918-be12-e567a02028ca": {},
  "d3c5e46d-072c-404c-af61-30e5418023af": {},
  "8e0f34e5-7b4f-4319-9288-2a568259c668": {
    "full_event": [
      "score_12"
    ]
  }
};

export { mainLineSchema };
