const PRIVATE_REGISTRATION_FORM_NAME = "privateRegistration";
const REGISTRATION_FORM_NAME = "registration";
const BRAZIL_REGISTRATION_FORM_NAME = "brazilRegistration";

export { PRIVATE_REGISTRATION_FORM_NAME, REGISTRATION_FORM_NAME, BRAZIL_REGISTRATION_FORM_NAME };
