/* eslint-disable */
// @ts-nocheck
import { EAlpha3Code } from "./EAlpha3Code";
import { ICountry } from "./ICountry";

/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptJsonGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.codegenerator.model.source.CountrySource
 */
const countryByAlfa3Map: Record<EAlpha3Code, ICountry> = {
  "AND": {
    "id": "ceb47490-cf21-11e9-883c-0242ac13000a",
    "name": "Andorra",
    "alpha2": "AD",
    "alpha3": "AND"
  },
  "ARE": {
    "id": "ceb4b57c-cf21-11e9-8ee6-0242ac13000a",
    "name": "United Arab Emirates",
    "alpha2": "AE",
    "alpha3": "ARE"
  },
  "AFG": {
    "id": "ceb4e81c-cf21-11e9-a4a6-0242ac13000a",
    "name": "Afghanistan",
    "alpha2": "AF",
    "alpha3": "AFG"
  },
  "ATG": {
    "id": "ceb4f23a-cf21-11e9-8b5d-0242ac13000a",
    "name": "Antigua and Barbuda",
    "alpha2": "AG",
    "alpha3": "ATG"
  },
  "AIA": {
    "id": "ceb4fc4e-cf21-11e9-8537-0242ac13000a",
    "name": "Anguilla",
    "alpha2": "AI",
    "alpha3": "AIA"
  },
  "ALB": {
    "id": "ceb50658-cf21-11e9-a446-0242ac13000a",
    "name": "Albania",
    "alpha2": "AL",
    "alpha3": "ALB"
  },
  "ARM": {
    "id": "ceb510f8-cf21-11e9-9e95-0242ac13000a",
    "name": "Armenia",
    "alpha2": "AM",
    "alpha3": "ARM"
  },
  "AGO": {
    "id": "ceb51e18-cf21-11e9-aa0a-0242ac13000a",
    "name": "Angola",
    "alpha2": "AO",
    "alpha3": "AGO"
  },
  "ATA": {
    "id": "ceb529b2-cf21-11e9-b8f2-0242ac13000a",
    "name": "Antarctica",
    "alpha2": "AQ",
    "alpha3": "ATA"
  },
  "ARG": {
    "id": "ceb533f8-cf21-11e9-8873-0242ac13000a",
    "name": "Argentina",
    "alpha2": "AR",
    "alpha3": "ARG"
  },
  "ASM": {
    "id": "ceb54370-cf21-11e9-8a0f-0242ac13000a",
    "name": "American Samoa",
    "alpha2": "AS",
    "alpha3": "ASM"
  },
  "AUT": {
    "id": "ceb552ac-cf21-11e9-9cb6-0242ac13000a",
    "name": "Austria",
    "alpha2": "AT",
    "alpha3": "AUT"
  },
  "AUS": {
    "id": "ceb55fc2-cf21-11e9-a987-0242ac13000a",
    "name": "Australia",
    "alpha2": "AU",
    "alpha3": "AUS"
  },
  "ABW": {
    "id": "ceb56de6-cf21-11e9-b78d-0242ac13000a",
    "name": "Aruba",
    "alpha2": "AW",
    "alpha3": "ABW"
  },
  "ALA": {
    "id": "ceb57eb2-cf21-11e9-9319-0242ac13000a",
    "name": "Åland Islands",
    "alpha2": "AX",
    "alpha3": "ALA"
  },
  "AZE": {
    "id": "ceb58b82-cf21-11e9-94d2-0242ac13000a",
    "name": "Azerbaijan",
    "alpha2": "AZ",
    "alpha3": "AZE"
  },
  "BIH": {
    "id": "ceb59852-cf21-11e9-9807-0242ac13000a",
    "name": "Bosnia and Herzegovina",
    "alpha2": "BA",
    "alpha3": "BIH"
  },
  "BRB": {
    "id": "ceb5a518-cf21-11e9-b50d-0242ac13000a",
    "name": "Barbados",
    "alpha2": "BB",
    "alpha3": "BRB"
  },
  "BGD": {
    "id": "ceb5b1de-cf21-11e9-93cb-0242ac13000a",
    "name": "Bangladesh",
    "alpha2": "BD",
    "alpha3": "BGD"
  },
  "BEL": {
    "id": "ceb5bf1c-cf21-11e9-a244-0242ac13000a",
    "name": "Belgium",
    "alpha2": "BE",
    "alpha3": "BEL"
  },
  "BFA": {
    "id": "ceb5cd04-cf21-11e9-8077-0242ac13000a",
    "name": "Burkina Faso",
    "alpha2": "BF",
    "alpha3": "BFA"
  },
  "BGR": {
    "id": "ceb5da56-cf21-11e9-bfb2-0242ac13000a",
    "name": "Bulgaria",
    "alpha2": "BG",
    "alpha3": "BGR"
  },
  "BHR": {
    "id": "ceb5e758-cf21-11e9-918b-0242ac13000a",
    "name": "Bahrain",
    "alpha2": "BH",
    "alpha3": "BHR"
  },
  "BDI": {
    "id": "ceb5f1e4-cf21-11e9-85ea-0242ac13000a",
    "name": "Burundi",
    "alpha2": "BI",
    "alpha3": "BDI"
  },
  "BEN": {
    "id": "ceb5fbda-cf21-11e9-b050-0242ac13000a",
    "name": "Benin",
    "alpha2": "BJ",
    "alpha3": "BEN"
  },
  "BLM": {
    "id": "ceb605c6-cf21-11e9-acef-0242ac13000a",
    "name": "Saint Barthélemy",
    "alpha2": "BL",
    "alpha3": "BLM"
  },
  "BMU": {
    "id": "ceb60fb2-cf21-11e9-87c7-0242ac13000a",
    "name": "Bermuda",
    "alpha2": "BM",
    "alpha3": "BMU"
  },
  "BRN": {
    "id": "ceb6199e-cf21-11e9-b4e2-0242ac13000a",
    "name": "Brunei Darussalam",
    "alpha2": "BN",
    "alpha3": "BRN"
  },
  "BOL": {
    "id": "ceb62380-cf21-11e9-b727-0242ac13000a",
    "name": "Bolivia, Plurinational State of",
    "alpha2": "BO",
    "alpha3": "BOL"
  },
  "BES": {
    "id": "ceb62d6c-cf21-11e9-a580-0242ac13000a",
    "name": "Bonaire, Sint Eustatius and Saba",
    "alpha2": "BQ",
    "alpha3": "BES"
  },
  "BRA": {
    "id": "ceb6374e-cf21-11e9-811b-0242ac13000a",
    "name": "Brazil",
    "alpha2": "BR",
    "alpha3": "BRA"
  },
  "BHS": {
    "id": "ceb6413a-cf21-11e9-b0c1-0242ac13000a",
    "name": "Bahamas",
    "alpha2": "BS",
    "alpha3": "BHS"
  },
  "BTN": {
    "id": "ceb64c66-cf21-11e9-a394-0242ac13000a",
    "name": "Bhutan",
    "alpha2": "BT",
    "alpha3": "BTN"
  },
  "BVT": {
    "id": "ceb65666-cf21-11e9-927d-0242ac13000a",
    "name": "Bouvet Island",
    "alpha2": "BV",
    "alpha3": "BVT"
  },
  "BWA": {
    "id": "ceb66156-cf21-11e9-b769-0242ac13000a",
    "name": "Botswana",
    "alpha2": "BW",
    "alpha3": "BWA"
  },
  "BLR": {
    "id": "ceb66c00-cf21-11e9-aa68-0242ac13000a",
    "name": "Belarus",
    "alpha2": "BY",
    "alpha3": "BLR"
  },
  "BLZ": {
    "id": "ceb675ec-cf21-11e9-898c-0242ac13000a",
    "name": "Belize",
    "alpha2": "BZ",
    "alpha3": "BLZ"
  },
  "CAN": {
    "id": "ceb67fce-cf21-11e9-af0d-0242ac13000a",
    "name": "Canada",
    "alpha2": "CA",
    "alpha3": "CAN"
  },
  "CCK": {
    "id": "ceb68b7c-cf21-11e9-924e-0242ac13000a",
    "name": "Cocos (Keeling) Islands",
    "alpha2": "CC",
    "alpha3": "CCK"
  },
  "COD": {
    "id": "ceb696a8-cf21-11e9-b6f6-0242ac13000a",
    "name": "Congo, the Democratic Republic of the",
    "alpha2": "CD",
    "alpha3": "COD"
  },
  "CAF": {
    "id": "ceb6a152-cf21-11e9-bb46-0242ac13000a",
    "name": "Central African Republic",
    "alpha2": "CF",
    "alpha3": "CAF"
  },
  "COG": {
    "id": "ceb6acb0-cf21-11e9-97ca-0242ac13000a",
    "name": "Congo",
    "alpha2": "CG",
    "alpha3": "COG"
  },
  "CHE": {
    "id": "ceb6b840-cf21-11e9-95be-0242ac13000a",
    "name": "Switzerland",
    "alpha2": "CH",
    "alpha3": "CHE"
  },
  "CIV": {
    "id": "ceb6c286-cf21-11e9-ba35-0242ac13000a",
    "name": "Côte d'Ivoire",
    "alpha2": "CI",
    "alpha3": "CIV"
  },
  "COK": {
    "id": "ceb6cc72-cf21-11e9-b755-0242ac13000a",
    "name": "Cook Islands",
    "alpha2": "CK",
    "alpha3": "COK"
  },
  "CHL": {
    "id": "ceb6d654-cf21-11e9-ab2f-0242ac13000a",
    "name": "Chile",
    "alpha2": "CL",
    "alpha3": "CHL"
  },
  "CMR": {
    "id": "ceb6e036-cf21-11e9-abfb-0242ac13000a",
    "name": "Cameroon",
    "alpha2": "CM",
    "alpha3": "CMR"
  },
  "CHN": {
    "id": "ceb6ea0e-cf21-11e9-b67e-0242ac13000a",
    "name": "China",
    "alpha2": "CN",
    "alpha3": "CHN"
  },
  "COL": {
    "id": "ceb6f3f0-cf21-11e9-8f42-0242ac13000a",
    "name": "Colombia",
    "alpha2": "CO",
    "alpha3": "COL"
  },
  "CRI": {
    "id": "ceb6fdc8-cf21-11e9-8283-0242ac13000a",
    "name": "Costa Rica",
    "alpha2": "CR",
    "alpha3": "CRI"
  },
  "CUB": {
    "id": "ceb70804-cf21-11e9-bea8-0242ac13000a",
    "name": "Cuba",
    "alpha2": "CU",
    "alpha3": "CUB"
  },
  "CPV": {
    "id": "ceb711dc-cf21-11e9-a71a-0242ac13000a",
    "name": "Cabo Verde",
    "alpha2": "CV",
    "alpha3": "CPV"
  },
  "CUW": {
    "id": "ceb71bbe-cf21-11e9-a079-0242ac13000a",
    "name": "Curaçao",
    "alpha2": "CW",
    "alpha3": "CUW"
  },
  "CXR": {
    "id": "ceb72596-cf21-11e9-9b9d-0242ac13000a",
    "name": "Christmas Island",
    "alpha2": "CX",
    "alpha3": "CXR"
  },
  "CYP": {
    "id": "ceb72f64-cf21-11e9-870a-0242ac13000a",
    "name": "Cyprus",
    "alpha2": "CY",
    "alpha3": "CYP"
  },
  "CZE": {
    "id": "ceb7393c-cf21-11e9-ae6b-0242ac13000a",
    "name": "Czech Republic",
    "alpha2": "CZ",
    "alpha3": "CZE"
  },
  "DEU": {
    "id": "ceb74314-cf21-11e9-b16e-0242ac13000a",
    "name": "Germany",
    "alpha2": "DE",
    "alpha3": "DEU"
  },
  "DJI": {
    "id": "ceb74cec-cf21-11e9-be37-0242ac13000a",
    "name": "Djibouti",
    "alpha2": "DJ",
    "alpha3": "DJI"
  },
  "DNK": {
    "id": "ceb756c4-cf21-11e9-b266-0242ac13000a",
    "name": "Denmark",
    "alpha2": "DK",
    "alpha3": "DNK"
  },
  "DMA": {
    "id": "ceb7609c-cf21-11e9-9239-0242ac13000a",
    "name": "Dominica",
    "alpha2": "DM",
    "alpha3": "DMA"
  },
  "DOM": {
    "id": "ceb76a9c-cf21-11e9-9713-0242ac13000a",
    "name": "Dominican Republic",
    "alpha2": "DO",
    "alpha3": "DOM"
  },
  "DZA": {
    "id": "ceb77474-cf21-11e9-9ac1-0242ac13000a",
    "name": "Algeria",
    "alpha2": "DZ",
    "alpha3": "DZA"
  },
  "ECU": {
    "id": "ceb77e4c-cf21-11e9-bcfd-0242ac13000a",
    "name": "Ecuador",
    "alpha2": "EC",
    "alpha3": "ECU"
  },
  "EST": {
    "id": "ceb7881a-cf21-11e9-961a-0242ac13000a",
    "name": "Estonia",
    "alpha2": "EE",
    "alpha3": "EST"
  },
  "EGY": {
    "id": "ceb791f2-cf21-11e9-8f62-0242ac13000a",
    "name": "Egypt",
    "alpha2": "EG",
    "alpha3": "EGY"
  },
  "ESH": {
    "id": "ceb79c10-cf21-11e9-815e-0242ac13000a",
    "name": "Western Sahara",
    "alpha2": "EH",
    "alpha3": "ESH"
  },
  "ERI": {
    "id": "ceb7a5fc-cf21-11e9-8070-0242ac13000a",
    "name": "Eritrea",
    "alpha2": "ER",
    "alpha3": "ERI"
  },
  "ESP": {
    "id": "ceb7afd4-cf21-11e9-8b04-0242ac13000a",
    "name": "Spain",
    "alpha2": "ES",
    "alpha3": "ESP"
  },
  "ETH": {
    "id": "ceb7b9ac-cf21-11e9-96cb-0242ac13000a",
    "name": "Ethiopia",
    "alpha2": "ET",
    "alpha3": "ETH"
  },
  "FIN": {
    "id": "ceb7c384-cf21-11e9-9ec7-0242ac13000a",
    "name": "Finland",
    "alpha2": "FI",
    "alpha3": "FIN"
  },
  "FJI": {
    "id": "ceb7cf78-cf21-11e9-be8a-0242ac13000a",
    "name": "Fiji",
    "alpha2": "FJ",
    "alpha3": "FJI"
  },
  "FLK": {
    "id": "ceb7db6c-cf21-11e9-9e5b-0242ac13000a",
    "name": "Falkland Islands (Malvinas)",
    "alpha2": "FK",
    "alpha3": "FLK"
  },
  "FSM": {
    "id": "ceb7e576-cf21-11e9-949e-0242ac13000a",
    "name": "Micronesia, Federated States of",
    "alpha2": "FM",
    "alpha3": "FSM"
  },
  "FRO": {
    "id": "ceb7ef62-cf21-11e9-b885-0242ac13000a",
    "name": "Faroe Islands",
    "alpha2": "FO",
    "alpha3": "FRO"
  },
  "FRA": {
    "id": "ceb7f944-cf21-11e9-bda0-0242ac13000a",
    "name": "France",
    "alpha2": "FR",
    "alpha3": "FRA"
  },
  "GAB": {
    "id": "ceb8039e-cf21-11e9-9161-0242ac13000a",
    "name": "Gabon",
    "alpha2": "GA",
    "alpha3": "GAB"
  },
  "GBR": {
    "id": "ceb80d8a-cf21-11e9-b2a7-0242ac13000a",
    "name": "United Kingdom",
    "alpha2": "GB",
    "alpha3": "GBR"
  },
  "GRD": {
    "id": "ceb8176c-cf21-11e9-bd8e-0242ac13000a",
    "name": "Grenada",
    "alpha2": "GD",
    "alpha3": "GRD"
  },
  "GEO": {
    "id": "ceb82194-cf21-11e9-992e-0242ac13000a",
    "name": "Georgia",
    "alpha2": "GE",
    "alpha3": "GEO"
  },
  "GUF": {
    "id": "ceb82b8a-cf21-11e9-a8e0-0242ac13000a",
    "name": "French Guiana",
    "alpha2": "GF",
    "alpha3": "GUF"
  },
  "GGY": {
    "id": "ceb83562-cf21-11e9-a93e-0242ac13000a",
    "name": "Guernsey",
    "alpha2": "GG",
    "alpha3": "GGY"
  },
  "GHA": {
    "id": "ceb83f9e-cf21-11e9-9f47-0242ac13000a",
    "name": "Ghana",
    "alpha2": "GH",
    "alpha3": "GHA"
  },
  "GIB": {
    "id": "ceb84976-cf21-11e9-9922-0242ac13000a",
    "name": "Gibraltar",
    "alpha2": "GI",
    "alpha3": "GIB"
  },
  "GRL": {
    "id": "ceb8534e-cf21-11e9-bc1b-0242ac13000a",
    "name": "Greenland",
    "alpha2": "GL",
    "alpha3": "GRL"
  },
  "GMB": {
    "id": "ceb85d58-cf21-11e9-976e-0242ac13000a",
    "name": "Gambia",
    "alpha2": "GM",
    "alpha3": "GMB"
  },
  "GIN": {
    "id": "ceb867e4-cf21-11e9-8ac2-0242ac13000a",
    "name": "Guinea",
    "alpha2": "GN",
    "alpha3": "GIN"
  },
  "GLP": {
    "id": "ceb871d0-cf21-11e9-ae2f-0242ac13000a",
    "name": "Guadeloupe",
    "alpha2": "GP",
    "alpha3": "GLP"
  },
  "GNQ": {
    "id": "ceb87bb2-cf21-11e9-8da9-0242ac13000a",
    "name": "Equatorial Guinea",
    "alpha2": "GQ",
    "alpha3": "GNQ"
  },
  "GRC": {
    "id": "ceb88594-cf21-11e9-9e11-0242ac13000a",
    "name": "Greece",
    "alpha2": "GR",
    "alpha3": "GRC"
  },
  "SGS": {
    "id": "ceb88f6c-cf21-11e9-82ea-0242ac13000a",
    "name": "South Georgia and the South Sandwich Islands",
    "alpha2": "GS",
    "alpha3": "SGS"
  },
  "GTM": {
    "id": "ceb89b06-cf21-11e9-b0fd-0242ac13000a",
    "name": "Guatemala",
    "alpha2": "GT",
    "alpha3": "GTM"
  },
  "GUM": {
    "id": "ceb8a826-cf21-11e9-92f6-0242ac13000a",
    "name": "Guam",
    "alpha2": "GU",
    "alpha3": "GUM"
  },
  "GNB": {
    "id": "ceb8b3b6-cf21-11e9-9388-0242ac13000a",
    "name": "Guinea-Bissau",
    "alpha2": "GW",
    "alpha3": "GNB"
  },
  "GUY": {
    "id": "ceb8bda2-cf21-11e9-bd67-0242ac13000a",
    "name": "Guyana",
    "alpha2": "GY",
    "alpha3": "GUY"
  },
  "HKG": {
    "id": "ceb8c784-cf21-11e9-a905-0242ac13000a",
    "name": "Hong Kong",
    "alpha2": "HK",
    "alpha3": "HKG"
  },
  "HMD": {
    "id": "ceb8d166-cf21-11e9-9a0a-0242ac13000a",
    "name": "Heard Island and McDonald Islands",
    "alpha2": "HM",
    "alpha3": "HMD"
  },
  "HND": {
    "id": "ceb8db7a-cf21-11e9-8c21-0242ac13000a",
    "name": "Honduras",
    "alpha2": "HN",
    "alpha3": "HND"
  },
  "HRV": {
    "id": "ceb8e552-cf21-11e9-8d7c-0242ac13000a",
    "name": "Croatia",
    "alpha2": "HR",
    "alpha3": "HRV"
  },
  "HTI": {
    "id": "ceb8ef2a-cf21-11e9-b2c5-0242ac13000a",
    "name": "Haiti",
    "alpha2": "HT",
    "alpha3": "HTI"
  },
  "HUN": {
    "id": "ceb8f902-cf21-11e9-a365-0242ac13000a",
    "name": "Hungary",
    "alpha2": "HU",
    "alpha3": "HUN"
  },
  "IDN": {
    "id": "ceb902da-cf21-11e9-83b6-0242ac13000a",
    "name": "Indonesia",
    "alpha2": "ID",
    "alpha3": "IDN"
  },
  "IRL": {
    "id": "ceb90ca8-cf21-11e9-bf1a-0242ac13000a",
    "name": "Ireland",
    "alpha2": "IE",
    "alpha3": "IRL"
  },
  "ISR": {
    "id": "ceb91680-cf21-11e9-b015-0242ac13000a",
    "name": "Israel",
    "alpha2": "IL",
    "alpha3": "ISR"
  },
  "IMN": {
    "id": "ceb92058-cf21-11e9-9b3b-0242ac13000a",
    "name": "Isle of Man",
    "alpha2": "IM",
    "alpha3": "IMN"
  },
  "IND": {
    "id": "ceb92a26-cf21-11e9-bcbd-0242ac13000a",
    "name": "India",
    "alpha2": "IN",
    "alpha3": "IND"
  },
  "IOT": {
    "id": "ceb933fe-cf21-11e9-b303-0242ac13000a",
    "name": "British Indian Ocean Territory",
    "alpha2": "IO",
    "alpha3": "IOT"
  },
  "IRQ": {
    "id": "ceb93dd6-cf21-11e9-a869-0242ac13000a",
    "name": "Iraq",
    "alpha2": "IQ",
    "alpha3": "IRQ"
  },
  "IRN": {
    "id": "ceb947ae-cf21-11e9-9af5-0242ac13000a",
    "name": "Iran, Islamic Republic of",
    "alpha2": "IR",
    "alpha3": "IRN"
  },
  "ISL": {
    "id": "ceb95190-cf21-11e9-ab76-0242ac13000a",
    "name": "Iceland",
    "alpha2": "IS",
    "alpha3": "ISL"
  },
  "ITA": {
    "id": "ceb95b5e-cf21-11e9-a327-0242ac13000a",
    "name": "Italy",
    "alpha2": "IT",
    "alpha3": "ITA"
  },
  "JEY": {
    "id": "ceb96536-cf21-11e9-93a4-0242ac13000a",
    "name": "Jersey",
    "alpha2": "JE",
    "alpha3": "JEY"
  },
  "JAM": {
    "id": "ceb96f0e-cf21-11e9-9624-0242ac13000a",
    "name": "Jamaica",
    "alpha2": "JM",
    "alpha3": "JAM"
  },
  "JOR": {
    "id": "ceb97940-cf21-11e9-ab1d-0242ac13000a",
    "name": "Jordan",
    "alpha2": "JO",
    "alpha3": "JOR"
  },
  "JPN": {
    "id": "ceb98318-cf21-11e9-b163-0242ac13000a",
    "name": "Japan",
    "alpha2": "JP",
    "alpha3": "JPN"
  },
  "KEN": {
    "id": "ceb98cf0-cf21-11e9-8762-0242ac13000a",
    "name": "Kenya",
    "alpha2": "KE",
    "alpha3": "KEN"
  },
  "KGZ": {
    "id": "ceb996c8-cf21-11e9-b7d1-0242ac13000a",
    "name": "Kyrgyzstan",
    "alpha2": "KG",
    "alpha3": "KGZ"
  },
  "KHM": {
    "id": "ceb9a10e-cf21-11e9-a4c2-0242ac13000a",
    "name": "Cambodia",
    "alpha2": "KH",
    "alpha3": "KHM"
  },
  "KIR": {
    "id": "ceb9aa6e-cf21-11e9-be12-0242ac13000a",
    "name": "Kiribati",
    "alpha2": "KI",
    "alpha3": "KIR"
  },
  "COM": {
    "id": "ceb9b3e2-cf21-11e9-bd8a-0242ac13000a",
    "name": "Comoros",
    "alpha2": "KM",
    "alpha3": "COM"
  },
  "KNA": {
    "id": "ceb9bd42-cf21-11e9-a755-0242ac13000a",
    "name": "Saint Kitts and Nevis",
    "alpha2": "KN",
    "alpha3": "KNA"
  },
  "PRK": {
    "id": "ceb9c6ac-cf21-11e9-ba82-0242ac13000a",
    "name": "Korea, Democratic People's Republic of",
    "alpha2": "KP",
    "alpha3": "PRK"
  },
  "KOR": {
    "id": "ceb9d016-cf21-11e9-828f-0242ac13000a",
    "name": "Korea, Republic of",
    "alpha2": "KR",
    "alpha3": "KOR"
  },
  "KWT": {
    "id": "ceb9d980-cf21-11e9-a161-0242ac13000a",
    "name": "Kuwait",
    "alpha2": "KW",
    "alpha3": "KWT"
  },
  "CYM": {
    "id": "ceb9e2ea-cf21-11e9-8e11-0242ac13000a",
    "name": "Cayman Islands",
    "alpha2": "KY",
    "alpha3": "CYM"
  },
  "KAZ": {
    "id": "ceb9ec54-cf21-11e9-819e-0242ac13000a",
    "name": "Kazakhstan",
    "alpha2": "KZ",
    "alpha3": "KAZ"
  },
  "LAO": {
    "id": "ceb9f5b4-cf21-11e9-8000-0242ac13000a",
    "name": "Lao People's Democratic Republic",
    "alpha2": "LA",
    "alpha3": "LAO"
  },
  "LBN": {
    "id": "ceb9ff1e-cf21-11e9-9e29-0242ac13000a",
    "name": "Lebanon",
    "alpha2": "LB",
    "alpha3": "LBN"
  },
  "LCA": {
    "id": "ceba0888-cf21-11e9-aa9e-0242ac13000a",
    "name": "Saint Lucia",
    "alpha2": "LC",
    "alpha3": "LCA"
  },
  "LIE": {
    "id": "ceba147c-cf21-11e9-9205-0242ac13000a",
    "name": "Liechtenstein",
    "alpha2": "LI",
    "alpha3": "LIE"
  },
  "LKA": {
    "id": "ceba1e18-cf21-11e9-be9f-0242ac13000a",
    "name": "Sri Lanka",
    "alpha2": "LK",
    "alpha3": "LKA"
  },
  "LBR": {
    "id": "ceba2782-cf21-11e9-8673-0242ac13000a",
    "name": "Liberia",
    "alpha2": "LR",
    "alpha3": "LBR"
  },
  "LSO": {
    "id": "ceba30ec-cf21-11e9-9d44-0242ac13000a",
    "name": "Lesotho",
    "alpha2": "LS",
    "alpha3": "LSO"
  },
  "LTU": {
    "id": "ceba3a56-cf21-11e9-920a-0242ac13000a",
    "name": "Lithuania",
    "alpha2": "LT",
    "alpha3": "LTU"
  },
  "LUX": {
    "id": "ceba43b6-cf21-11e9-aec0-0242ac13000a",
    "name": "Luxembourg",
    "alpha2": "LU",
    "alpha3": "LUX"
  },
  "LVA": {
    "id": "ceba4d20-cf21-11e9-9935-0242ac13000a",
    "name": "Latvia",
    "alpha2": "LV",
    "alpha3": "LVA"
  },
  "LBY": {
    "id": "ceba5784-cf21-11e9-aeca-0242ac13000a",
    "name": "Libya",
    "alpha2": "LY",
    "alpha3": "LBY"
  },
  "MAR": {
    "id": "ceba63e6-cf21-11e9-a137-0242ac13000a",
    "name": "Morocco",
    "alpha2": "MA",
    "alpha3": "MAR"
  },
  "MCO": {
    "id": "ceba6d50-cf21-11e9-a09b-0242ac13000a",
    "name": "Monaco",
    "alpha2": "MC",
    "alpha3": "MCO"
  },
  "MDA": {
    "id": "ceba76ba-cf21-11e9-b993-0242ac13000a",
    "name": "Moldova",
    "alpha2": "MD",
    "alpha3": "MDA"
  },
  "MNE": {
    "id": "ceba801a-cf21-11e9-a012-0242ac13000a",
    "name": "Montenegro",
    "alpha2": "ME",
    "alpha3": "MNE"
  },
  "MAF": {
    "id": "ceba8984-cf21-11e9-9ef7-0242ac13000a",
    "name": "Saint Martin (French part)",
    "alpha2": "MF",
    "alpha3": "MAF"
  },
  "MDG": {
    "id": "ceba92ee-cf21-11e9-b6d7-0242ac13000a",
    "name": "Madagascar",
    "alpha2": "MG",
    "alpha3": "MDG"
  },
  "MHL": {
    "id": "ceba9c58-cf21-11e9-a2c3-0242ac13000a",
    "name": "Marshall Islands",
    "alpha2": "MH",
    "alpha3": "MHL"
  },
  "MKD": {
    "id": "cebaa5b8-cf21-11e9-adc6-0242ac13000a",
    "name": "Macedonia, the former Yugoslav Republic of",
    "alpha2": "MK",
    "alpha3": "MKD"
  },
  "MLI": {
    "id": "cebab134-cf21-11e9-a147-0242ac13000a",
    "name": "Mali",
    "alpha2": "ML",
    "alpha3": "MLI"
  },
  "MMR": {
    "id": "cebaba9e-cf21-11e9-958e-0242ac13000a",
    "name": "Myanmar",
    "alpha2": "MM",
    "alpha3": "MMR"
  },
  "MNG": {
    "id": "cebac408-cf21-11e9-a5b9-0242ac13000a",
    "name": "Mongolia",
    "alpha2": "MN",
    "alpha3": "MNG"
  },
  "MAC": {
    "id": "cebacd68-cf21-11e9-bb9d-0242ac13000a",
    "name": "Macao",
    "alpha2": "MO",
    "alpha3": "MAC"
  },
  "MNP": {
    "id": "cebad6d2-cf21-11e9-8ece-0242ac13000a",
    "name": "Northern Mariana Islands",
    "alpha2": "MP",
    "alpha3": "MNP"
  },
  "MTQ": {
    "id": "cebae032-cf21-11e9-8510-0242ac13000a",
    "name": "Martinique",
    "alpha2": "MQ",
    "alpha3": "MTQ"
  },
  "MRT": {
    "id": "cebae99c-cf21-11e9-b442-0242ac13000a",
    "name": "Mauritania",
    "alpha2": "MR",
    "alpha3": "MRT"
  },
  "MSR": {
    "id": "cebaf31a-cf21-11e9-bd11-0242ac13000a",
    "name": "Montserrat",
    "alpha2": "MS",
    "alpha3": "MSR"
  },
  "MLT": {
    "id": "cebafc84-cf21-11e9-a4c3-0242ac13000a",
    "name": "Malta",
    "alpha2": "MT",
    "alpha3": "MLT"
  },
  "MUS": {
    "id": "cebb05ee-cf21-11e9-a631-0242ac13000a",
    "name": "Mauritius",
    "alpha2": "MU",
    "alpha3": "MUS"
  },
  "MDV": {
    "id": "cebb0f58-cf21-11e9-b2ca-0242ac13000a",
    "name": "Maldives",
    "alpha2": "MV",
    "alpha3": "MDV"
  },
  "MWI": {
    "id": "cebb18c2-cf21-11e9-b41b-0242ac13000a",
    "name": "Malawi",
    "alpha2": "MW",
    "alpha3": "MWI"
  },
  "MEX": {
    "id": "cebb2222-cf21-11e9-8dca-0242ac13000a",
    "name": "Mexico",
    "alpha2": "MX",
    "alpha3": "MEX"
  },
  "MYS": {
    "id": "cebb2b8c-cf21-11e9-b755-0242ac13000a",
    "name": "Malaysia",
    "alpha2": "MY",
    "alpha3": "MYS"
  },
  "MOZ": {
    "id": "cebb34ec-cf21-11e9-b1dd-0242ac13000a",
    "name": "Mozambique",
    "alpha2": "MZ",
    "alpha3": "MOZ"
  },
  "NAM": {
    "id": "cebb3e56-cf21-11e9-b9d7-0242ac13000a",
    "name": "Namibia",
    "alpha2": "NA",
    "alpha3": "NAM"
  },
  "NCL": {
    "id": "cebb4914-cf21-11e9-afed-0242ac13000a",
    "name": "New Caledonia",
    "alpha2": "NC",
    "alpha3": "NCL"
  },
  "NER": {
    "id": "cebb527e-cf21-11e9-8cba-0242ac13000a",
    "name": "Niger",
    "alpha2": "NE",
    "alpha3": "NER"
  },
  "NFK": {
    "id": "cebb5be8-cf21-11e9-ab75-0242ac13000a",
    "name": "Norfolk Island",
    "alpha2": "NF",
    "alpha3": "NFK"
  },
  "NGA": {
    "id": "cebb6552-cf21-11e9-9f7c-0242ac13000a",
    "name": "Nigeria",
    "alpha2": "NG",
    "alpha3": "NGA"
  },
  "NIC": {
    "id": "cebb6eb2-cf21-11e9-a648-0242ac13000a",
    "name": "Nicaragua",
    "alpha2": "NI",
    "alpha3": "NIC"
  },
  "NLD": {
    "id": "cebb781c-cf21-11e9-8748-0242ac13000a",
    "name": "Netherlands",
    "alpha2": "NL",
    "alpha3": "NLD"
  },
  "NOR": {
    "id": "cebb8186-cf21-11e9-8cb9-0242ac13000a",
    "name": "Norway",
    "alpha2": "NO",
    "alpha3": "NOR"
  },
  "NPL": {
    "id": "cebb8ae6-cf21-11e9-a0af-0242ac13000a",
    "name": "Nepal",
    "alpha2": "NP",
    "alpha3": "NPL"
  },
  "NRU": {
    "id": "cebb9450-cf21-11e9-9a18-0242ac13000a",
    "name": "Nauru",
    "alpha2": "NR",
    "alpha3": "NRU"
  },
  "NIU": {
    "id": "cebb9db0-cf21-11e9-956c-0242ac13000a",
    "name": "Niue",
    "alpha2": "NU",
    "alpha3": "NIU"
  },
  "NZL": {
    "id": "cebba71a-cf21-11e9-bbb8-0242ac13000a",
    "name": "New Zealand",
    "alpha2": "NZ",
    "alpha3": "NZL"
  },
  "OMN": {
    "id": "cebbb07a-cf21-11e9-81c9-0242ac13000a",
    "name": "Oman",
    "alpha2": "OM",
    "alpha3": "OMN"
  },
  "PAN": {
    "id": "cebbb9e4-cf21-11e9-b095-0242ac13000a",
    "name": "Panama",
    "alpha2": "PA",
    "alpha3": "PAN"
  },
  "PER": {
    "id": "cebbc4f2-cf21-11e9-a030-0242ac13000a",
    "name": "Peru",
    "alpha2": "PE",
    "alpha3": "PER"
  },
  "PYF": {
    "id": "cebbd014-cf21-11e9-99c5-0242ac13000a",
    "name": "French Polynesia",
    "alpha2": "PF",
    "alpha3": "PYF"
  },
  "PNG": {
    "id": "cebbd974-cf21-11e9-948e-0242ac13000a",
    "name": "Papua New Guinea",
    "alpha2": "PG",
    "alpha3": "PNG"
  },
  "PHL": {
    "id": "cebbe428-cf21-11e9-96e8-0242ac13000a",
    "name": "Philippines",
    "alpha2": "PH",
    "alpha3": "PHL"
  },
  "PAK": {
    "id": "cebbed92-cf21-11e9-ac94-0242ac13000a",
    "name": "Pakistan",
    "alpha2": "PK",
    "alpha3": "PAK"
  },
  "POL": {
    "id": "cebbf6fc-cf21-11e9-b599-0242ac13000a",
    "name": "Poland",
    "alpha2": "PL",
    "alpha3": "POL"
  },
  "SPM": {
    "id": "cebc0066-cf21-11e9-a210-0242ac13000a",
    "name": "Saint Pierre and Miquelon",
    "alpha2": "PM",
    "alpha3": "SPM"
  },
  "PCN": {
    "id": "cebc09c6-cf21-11e9-91ac-0242ac13000a",
    "name": "Pitcairn",
    "alpha2": "PN",
    "alpha3": "PCN"
  },
  "PRI": {
    "id": "cebc1330-cf21-11e9-81ae-0242ac13000a",
    "name": "Puerto Rico",
    "alpha2": "PR",
    "alpha3": "PRI"
  },
  "PSE": {
    "id": "cebc1c9a-cf21-11e9-ac88-0242ac13000a",
    "name": "Palestine, State of",
    "alpha2": "PS",
    "alpha3": "PSE"
  },
  "PRT": {
    "id": "cebc25fa-cf21-11e9-9039-0242ac13000a",
    "name": "Portugal",
    "alpha2": "PT",
    "alpha3": "PRT"
  },
  "PLW": {
    "id": "cebc2f64-cf21-11e9-b4a4-0242ac13000a",
    "name": "Palau",
    "alpha2": "PW",
    "alpha3": "PLW"
  },
  "PRY": {
    "id": "cebc38c4-cf21-11e9-ae04-0242ac13000a",
    "name": "Paraguay",
    "alpha2": "PY",
    "alpha3": "PRY"
  },
  "QAT": {
    "id": "cebc422e-cf21-11e9-b559-0242ac13000a",
    "name": "Qatar",
    "alpha2": "QA",
    "alpha3": "QAT"
  },
  "REU": {
    "id": "cebc4b98-cf21-11e9-a997-0242ac13000a",
    "name": "Réunion",
    "alpha2": "RE",
    "alpha3": "REU"
  },
  "ROU": {
    "id": "cebc578c-cf21-11e9-89c1-0242ac13000a",
    "name": "Romania",
    "alpha2": "RO",
    "alpha3": "ROU"
  },
  "SRB": {
    "id": "cebc60f6-cf21-11e9-bf83-0242ac13000a",
    "name": "Serbia",
    "alpha2": "RS",
    "alpha3": "SRB"
  },
  "RUS": {
    "id": "cebc6a60-cf21-11e9-9af0-0242ac13000a",
    "name": "Russian Federation",
    "alpha2": "RU",
    "alpha3": "RUS"
  },
  "RWA": {
    "id": "cebc73ca-cf21-11e9-988a-0242ac13000a",
    "name": "Rwanda",
    "alpha2": "RW",
    "alpha3": "RWA"
  },
  "SAU": {
    "id": "cebc7d2a-cf21-11e9-9372-0242ac13000a",
    "name": "Saudi Arabia",
    "alpha2": "SA",
    "alpha3": "SAU"
  },
  "SLB": {
    "id": "cebc8892-cf21-11e9-b649-0242ac13000a",
    "name": "Solomon Islands",
    "alpha2": "SB",
    "alpha3": "SLB"
  },
  "SYC": {
    "id": "cebc91f2-cf21-11e9-982b-0242ac13000a",
    "name": "Seychelles",
    "alpha2": "SC",
    "alpha3": "SYC"
  },
  "SDN": {
    "id": "cebc9b5c-cf21-11e9-ab24-0242ac13000a",
    "name": "Sudan",
    "alpha2": "SD",
    "alpha3": "SDN"
  },
  "SWE": {
    "id": "cebca4bc-cf21-11e9-95fe-0242ac13000a",
    "name": "Sweden",
    "alpha2": "SE",
    "alpha3": "SWE"
  },
  "SGP": {
    "id": "cebcae26-cf21-11e9-af96-0242ac13000a",
    "name": "Singapore",
    "alpha2": "SG",
    "alpha3": "SGP"
  },
  "SHN": {
    "id": "cebcb790-cf21-11e9-a627-0242ac13000a",
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "alpha2": "SH",
    "alpha3": "SHN"
  },
  "SVN": {
    "id": "cebcc0f0-cf21-11e9-9164-0242ac13000a",
    "name": "Slovenia",
    "alpha2": "SI",
    "alpha3": "SVN"
  },
  "SJM": {
    "id": "cebcca5a-cf21-11e9-8fa2-0242ac13000a",
    "name": "Svalbard and Jan Mayen",
    "alpha2": "SJ",
    "alpha3": "SJM"
  },
  "SVK": {
    "id": "cebcd3ba-cf21-11e9-baff-0242ac13000a",
    "name": "Slovakia",
    "alpha2": "SK",
    "alpha3": "SVK"
  },
  "SLE": {
    "id": "cebcdd24-cf21-11e9-8890-0242ac13000a",
    "name": "Sierra Leone",
    "alpha2": "SL",
    "alpha3": "SLE"
  },
  "SMR": {
    "id": "cebce68e-cf21-11e9-afd9-0242ac13000a",
    "name": "San Marino",
    "alpha2": "SM",
    "alpha3": "SMR"
  },
  "SEN": {
    "id": "cebcefee-cf21-11e9-9aa4-0242ac13000a",
    "name": "Senegal",
    "alpha2": "SN",
    "alpha3": "SEN"
  },
  "SOM": {
    "id": "cebcf958-cf21-11e9-966d-0242ac13000a",
    "name": "Somalia",
    "alpha2": "SO",
    "alpha3": "SOM"
  },
  "SUR": {
    "id": "cebd02c2-cf21-11e9-8b72-0242ac13000a",
    "name": "Suriname",
    "alpha2": "SR",
    "alpha3": "SUR"
  },
  "SSD": {
    "id": "cebd0c22-cf21-11e9-8ac7-0242ac13000a",
    "name": "South Sudan",
    "alpha2": "SS",
    "alpha3": "SSD"
  },
  "STP": {
    "id": "cebd1a1e-cf21-11e9-96a2-0242ac13000a",
    "name": "Sao Tome and Principe",
    "alpha2": "ST",
    "alpha3": "STP"
  },
  "SLV": {
    "id": "cebd2388-cf21-11e9-b848-0242ac13000a",
    "name": "El Salvador",
    "alpha2": "SV",
    "alpha3": "SLV"
  },
  "SXM": {
    "id": "cebd2cf2-cf21-11e9-bc55-0242ac13000a",
    "name": "Sint Maarten (Dutch part)",
    "alpha2": "SX",
    "alpha3": "SXM"
  },
  "SYR": {
    "id": "cebd365c-cf21-11e9-bcd2-0242ac13000a",
    "name": "Syrian Arab Republic",
    "alpha2": "SY",
    "alpha3": "SYR"
  },
  "SWZ": {
    "id": "cebd3fbc-cf21-11e9-8b6b-0242ac13000a",
    "name": "Eswatini",
    "alpha2": "SZ",
    "alpha3": "SWZ"
  },
  "TCA": {
    "id": "cebd4ca0-cf21-11e9-86b5-0242ac13000a",
    "name": "Turks and Caicos Islands",
    "alpha2": "TC",
    "alpha3": "TCA"
  },
  "TCD": {
    "id": "cebd560a-cf21-11e9-9450-0242ac13000a",
    "name": "Chad",
    "alpha2": "TD",
    "alpha3": "TCD"
  },
  "ATF": {
    "id": "cebd5f6a-cf21-11e9-8ef7-0242ac13000a",
    "name": "French Southern Territories",
    "alpha2": "TF",
    "alpha3": "ATF"
  },
  "TGO": {
    "id": "cebd68d4-cf21-11e9-8a19-0242ac13000a",
    "name": "Togo",
    "alpha2": "TG",
    "alpha3": "TGO"
  },
  "THA": {
    "id": "cebd723e-cf21-11e9-a15c-0242ac13000a",
    "name": "Thailand",
    "alpha2": "TH",
    "alpha3": "THA"
  },
  "TJK": {
    "id": "cebd7b9e-cf21-11e9-ab6c-0242ac13000a",
    "name": "Tajikistan",
    "alpha2": "TJ",
    "alpha3": "TJK"
  },
  "TKL": {
    "id": "cebd8508-cf21-11e9-8fc0-0242ac13000a",
    "name": "Tokelau",
    "alpha2": "TK",
    "alpha3": "TKL"
  },
  "TLS": {
    "id": "cebd8e68-cf21-11e9-9e14-0242ac13000a",
    "name": "Timor-Leste",
    "alpha2": "TL",
    "alpha3": "TLS"
  },
  "TKM": {
    "id": "cebd97d2-cf21-11e9-a979-0242ac13000a",
    "name": "Turkmenistan",
    "alpha2": "TM",
    "alpha3": "TKM"
  },
  "TUN": {
    "id": "cebda13c-cf21-11e9-8b20-0242ac13000a",
    "name": "Tunisia",
    "alpha2": "TN",
    "alpha3": "TUN"
  },
  "TON": {
    "id": "cebdaa9c-cf21-11e9-ac2a-0242ac13000a",
    "name": "Tonga",
    "alpha2": "TO",
    "alpha3": "TON"
  },
  "TUR": {
    "id": "cebdb406-cf21-11e9-a37b-0242ac13000a",
    "name": "Turkey",
    "alpha2": "TR",
    "alpha3": "TUR"
  },
  "TTO": {
    "id": "cebdbd84-cf21-11e9-98f4-0242ac13000a",
    "name": "Trinidad and Tobago",
    "alpha2": "TT",
    "alpha3": "TTO"
  },
  "TUV": {
    "id": "cebdc6ee-cf21-11e9-aa06-0242ac13000a",
    "name": "Tuvalu",
    "alpha2": "TV",
    "alpha3": "TUV"
  },
  "TWN": {
    "id": "cebdd058-cf21-11e9-b503-0242ac13000a",
    "name": "Taiwan, Province of China",
    "alpha2": "TW",
    "alpha3": "TWN"
  },
  "TZA": {
    "id": "cebdd9b8-cf21-11e9-9524-0242ac13000a",
    "name": "Tanzania, United Republic of",
    "alpha2": "TZ",
    "alpha3": "TZA"
  },
  "UKR": {
    "id": "cebde32c-cf21-11e9-aef9-0242ac13000a",
    "name": "Ukraine",
    "alpha2": "UA",
    "alpha3": "UKR"
  },
  "UGA": {
    "id": "cebdecf0-cf21-11e9-8f9b-0242ac13000a",
    "name": "Uganda",
    "alpha2": "UG",
    "alpha3": "UGA"
  },
  "UMI": {
    "id": "cebdf65a-cf21-11e9-b6c5-0242ac13000a",
    "name": "United States Minor Outlying Islands",
    "alpha2": "UM",
    "alpha3": "UMI"
  },
  "USA": {
    "id": "cebdffc4-cf21-11e9-9567-0242ac13000a",
    "name": "United States of America",
    "alpha2": "US",
    "alpha3": "USA"
  },
  "URY": {
    "id": "cebe0924-cf21-11e9-a7b5-0242ac13000a",
    "name": "Uruguay",
    "alpha2": "UY",
    "alpha3": "URY"
  },
  "UZB": {
    "id": "cebe128e-cf21-11e9-b711-0242ac13000a",
    "name": "Uzbekistan",
    "alpha2": "UZ",
    "alpha3": "UZB"
  },
  "VAT": {
    "id": "cebe1bf8-cf21-11e9-a308-0242ac13000a",
    "name": "Holy See",
    "alpha2": "VA",
    "alpha3": "VAT"
  },
  "VCT": {
    "id": "cebe25bc-cf21-11e9-8833-0242ac13000a",
    "name": "Saint Vincent and the Grenadines",
    "alpha2": "VC",
    "alpha3": "VCT"
  },
  "VEN": {
    "id": "cebe2f26-cf21-11e9-9d8f-0242ac13000a",
    "name": "Venezuela, Bolivarian Republic of",
    "alpha2": "VE",
    "alpha3": "VEN"
  },
  "VGB": {
    "id": "cebe3890-cf21-11e9-a89f-0242ac13000a",
    "name": "Virgin Islands, British",
    "alpha2": "VG",
    "alpha3": "VGB"
  },
  "VIR": {
    "id": "cebe41f0-cf21-11e9-99b1-0242ac13000a",
    "name": "Virgin Islands, U.S.",
    "alpha2": "VI",
    "alpha3": "VIR"
  },
  "VNM": {
    "id": "cebe4b5a-cf21-11e9-9cf0-0242ac13000a",
    "name": "Viet Nam",
    "alpha2": "VN",
    "alpha3": "VNM"
  },
  "VUT": {
    "id": "cebe54d8-cf21-11e9-97b0-0242ac13000a",
    "name": "Vanuatu",
    "alpha2": "VU",
    "alpha3": "VUT"
  },
  "WLF": {
    "id": "cebe5e42-cf21-11e9-9ac6-0242ac13000a",
    "name": "Wallis and Futuna",
    "alpha2": "WF",
    "alpha3": "WLF"
  },
  "WSM": {
    "id": "cebe67ac-cf21-11e9-afc8-0242ac13000a",
    "name": "Samoa",
    "alpha2": "WS",
    "alpha3": "WSM"
  },
  "YEM": {
    "id": "cebe7116-cf21-11e9-bf20-0242ac13000a",
    "name": "Yemen",
    "alpha2": "YE",
    "alpha3": "YEM"
  },
  "MYT": {
    "id": "cebe7a76-cf21-11e9-801a-0242ac13000a",
    "name": "Mayotte",
    "alpha2": "YT",
    "alpha3": "MYT"
  },
  "ZAF": {
    "id": "cebe83e0-cf21-11e9-ba89-0242ac13000a",
    "name": "South Africa",
    "alpha2": "ZA",
    "alpha3": "ZAF"
  },
  "ZMB": {
    "id": "cebe8d40-cf21-11e9-952a-0242ac13000a",
    "name": "Zambia",
    "alpha2": "ZM",
    "alpha3": "ZMB"
  },
  "ZWE": {
    "id": "cebe96aa-cf21-11e9-b186-0242ac13000a",
    "name": "Zimbabwe",
    "alpha2": "ZW",
    "alpha3": "ZWE"
  },
  "XXK": {
    "id": "ff6405d2-30d6-4127-8873-7f5fe14cea9a",
    "name": "Kosovo",
    "alpha2": "XK",
    "alpha3": "XXK"
  }
} as Record<EAlpha3Code, ICountry>;

export { countryByAlfa3Map };
