export enum EKeyCodes {
  DIGIT_0 = "Digit0",
  DIGIT_1 = "Digit1",
  DIGIT_2 = "Digit2",
  DIGIT_3 = "Digit3",
  DIGIT_4 = "Digit4",
  DIGIT_5 = "Digit5",
  DIGIT_6 = "Digit6",
  DIGIT_7 = "Digit7",
  DIGIT_8 = "Digit8",
  DIGIT_9 = "Digit9",
  ARROW_LEFT = "ArrowLeft",
  ARROW_RIGHT = "ArrowRight",
  PERIOD = "Period",
  MINUS = "Minus",
  COMMA = "Comma",
  DELETE = "Delete",
  CONTROL = "Control",
  SHIFT = "Shift",

  // todo
  alt = "AltLeft",
  backspace = "Backspace",
  ctrl = "ControlLeft",
  enter = "Enter",
  escape = "Escape",
  numpadEnter = "NumpadEnter",
  shift = "ShiftLeft",
  space = "Space",
  tab = "Tab",
  E = "KeyE",
}
