/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/generator/typescript/TypescriptEnumGenerator.kt
 * 🔨️ SOURCE CODE: com.sumstats.sportsbookui.model.SportsbookUiThemeEnum
 */
export enum ESportsbookUiTheme {
  ONWIN = "onwin",
  TIPO = "tipo",
  BAHIS = "bahis",
  SAHABET = "sahabet",
  SAHABET2 = "sahabet2",
  MATADORBET = "matadorbet",
  BETWIZ = "betwiz",
  BETTURKEY = "betturkey",
  BETORSPIN = "betorspin",
  BETVAMOS = "betvamos",
  BAYWIN = "baywin",
  BETPUBLIC = "betpublic",
  STARZBET = "starzbet",
  BYCASINO = "bycasino",
  FIXBET = "fixbet",
  ZBAHIS = "zbahis",
  ZLOT = "zlot",
  DODOBET = "dodobet",
  LUXSLOT = "luxslot",
  BANKOBET = "bankobet",
  WINOVER = "winover",
  SLOTTOTO = "slottoto",
  CASINODA = "casinoda",
  STARZBET_IN = "starzbet-in",
  OTOBET = "otobet",
  LIGOBET = "ligobet",
}
