import { EProviderCode } from "@sb/betting-core/EProviderCode";
import { capitalizeFirstLetter, reverseMap } from "@sb/utils";

const gameProviderEnum = {
  ALL_PROVIDERS: "ALL_PROVIDERS",
  [EProviderCode.EZUGI]: EProviderCode.EZUGI,
  [EProviderCode.EZUGI_EVOLUTION]: EProviderCode.EZUGI_EVOLUTION,

  [EProviderCode.EVOLUTION]: EProviderCode.EVOLUTION,
  [EProviderCode.EVOLUTION_NLC]: EProviderCode.EVOLUTION_NLC,
  [EProviderCode.EVOLUTION_REDTIGER]: EProviderCode.EVOLUTION_REDTIGER,
  [EProviderCode.EVOLUTION_NETENT]: EProviderCode.EVOLUTION_NETENT,
  [EProviderCode.EVOLUTION_BTG]: EProviderCode.EVOLUTION_BTG,

  [EProviderCode.PRAGMATIC_PLAY]: EProviderCode.PRAGMATIC_PLAY,

  [EProviderCode.ONE_TOUCH]: EProviderCode.ONE_TOUCH,

  [EProviderCode.ABSOLUTE_LIVE_GAMING]: EProviderCode.ABSOLUTE_LIVE_GAMING,
  [EProviderCode.ABSOLUTE_LIVE_GAMING_7_MOJOS]: EProviderCode.ABSOLUTE_LIVE_GAMING_7_MOJOS,

  [EProviderCode.LUCKY_STREAK]: EProviderCode.LUCKY_STREAK,
  [EProviderCode.LUCKY_STREAK_BOONGO]: EProviderCode.LUCKY_STREAK_BOONGO,
  [EProviderCode.LUCKY_STREAK_FUGASO]: EProviderCode.LUCKY_STREAK_FUGASO,
  [EProviderCode.LUCKY_STREAK_SPINOMENAL]: EProviderCode.LUCKY_STREAK_SPINOMENAL,
  [EProviderCode.LUCKY_STREAK_TOM_HORN]: EProviderCode.LUCKY_STREAK_TOM_HORN,
  [EProviderCode.LUCKY_STREAK_TURBO_GAMES]: EProviderCode.LUCKY_STREAK_TURBO_GAMES,
  [EProviderCode.LUCKY_STREAK_YGGDRASIL]: EProviderCode.LUCKY_STREAK_YGGDRASIL,

  [EProviderCode.FALCON_GAMING]: EProviderCode.FALCON_GAMING,

  [EProviderCode.ENDORPHINA]: EProviderCode.ENDORPHINA,

  [EProviderCode.LEAP_GAMING]: EProviderCode.LEAP_GAMING,

  [EProviderCode.BGAMING]: EProviderCode.BGAMING,

  [EProviderCode.THE_EAR]: EProviderCode.THE_EAR,
  [EProviderCode.THE_EAR_AMATIC]: EProviderCode.THE_EAR_AMATIC,
  [EProviderCode.THE_EAR_AINSWORTH_GAMES]: EProviderCode.THE_EAR_AINSWORTH_GAMES,
  [EProviderCode.THE_EAR_GENESIS_GAMING]: EProviderCode.THE_EAR_GENESIS_GAMING,
  [EProviderCode.THE_EAR_TRIPPLE_CHERRY]: EProviderCode.THE_EAR_TRIPPLE_CHERRY,
  [EProviderCode.THE_EAR_HABANERO]: EProviderCode.THE_EAR_HABANERO,
  [EProviderCode.THE_EAR_STORMCRAFT_STUDIOS]: EProviderCode.THE_EAR_STORMCRAFT_STUDIOS,
  [EProviderCode.THE_EAR_GAMZIX]: EProviderCode.THE_EAR_GAMZIX,
  [EProviderCode.THE_EAR_MACAW_GAMING]: EProviderCode.THE_EAR_MACAW_GAMING,
  [EProviderCode.THE_EAR_AUGUST_GAMING]: EProviderCode.THE_EAR_AUGUST_GAMING,
  [EProviderCode.THE_EAR_BELATRA]: EProviderCode.THE_EAR_BELATRA,
  [EProviderCode.THE_EAR_MR_SLOTTY]: EProviderCode.THE_EAR_MR_SLOTTY,
  [EProviderCode.THE_EAR_PLAY_PEARLS]: EProviderCode.THE_EAR_PLAY_PEARLS,
  [EProviderCode.THE_EAR_WOOHOO_GAMES]: EProviderCode.THE_EAR_WOOHOO_GAMES,
  [EProviderCode.THE_EAR_FELIX_GAMING]: EProviderCode.THE_EAR_FELIX_GAMING,
  [EProviderCode.THE_EAR_GAMES_INC]: EProviderCode.THE_EAR_GAMES_INC,
  [EProviderCode.THE_EAR_GREEN_JADE]: EProviderCode.THE_EAR_GREEN_JADE,
  [EProviderCode.THE_EAR_KA_GAMING]: EProviderCode.THE_EAR_KA_GAMING,
  [EProviderCode.THE_EAR_4THEPLAYER]: EProviderCode.THE_EAR_4THEPLAYER,
  [EProviderCode.THE_EAR_FAZI]: EProviderCode.THE_EAR_FAZI,
  [EProviderCode.THE_EAR_PARIPLAY]: EProviderCode.THE_EAR_PARIPLAY,
  [EProviderCode.THE_EAR_REEL_PLAY]: EProviderCode.THE_EAR_REEL_PLAY,
  [EProviderCode.THE_EAR_STHLMGAMING]: EProviderCode.THE_EAR_STHLMGAMING,
  [EProviderCode.THE_EAR_AWC68]: EProviderCode.THE_EAR_AWC68,
  [EProviderCode.THE_EAR_ALL41_STUDIOS]: EProviderCode.THE_EAR_ALL41_STUDIOS,
  [EProviderCode.THE_EAR_APOLLO]: EProviderCode.THE_EAR_APOLLO,
  [EProviderCode.THE_EAR_BOOMING]: EProviderCode.THE_EAR_BOOMING,
  [EProviderCode.THE_EAR_BOOONGO]: EProviderCode.THE_EAR_BOOONGO,
  [EProviderCode.THE_EAR_CONCEPT_GAMING]: EProviderCode.THE_EAR_CONCEPT_GAMING,
  [EProviderCode.THE_EAR_CRAZY_TOOTH]: EProviderCode.THE_EAR_CRAZY_TOOTH,
  [EProviderCode.THE_EAR_CT_INTERACTIVE]: EProviderCode.THE_EAR_CT_INTERACTIVE,
  [EProviderCode.THE_EAR_ELECTRIC_ELEPHANT]: EProviderCode.THE_EAR_ELECTRIC_ELEPHANT,
  [EProviderCode.THE_EAR_EYECON]: EProviderCode.THE_EAR_EYECON,
  [EProviderCode.THE_EAR_FILS_GAME]: EProviderCode.THE_EAR_FILS_GAME,
  [EProviderCode.THE_EAR_FORTUNE_FACTORY_STUDIOS]: EProviderCode.THE_EAR_FORTUNE_FACTORY_STUDIOS,
  [EProviderCode.THE_EAR_FOXIUM]: EProviderCode.THE_EAR_FOXIUM,
  [EProviderCode.THE_EAR_FUGASO]: EProviderCode.THE_EAR_FUGASO,
  [EProviderCode.THE_EAR_GAME_MEDIA_WORKS]: EProviderCode.THE_EAR_GAME_MEDIA_WORKS,
  [EProviderCode.THE_EAR_GAME_ART]: EProviderCode.THE_EAR_GAME_ART,
  [EProviderCode.THE_EAR_GAMEBURGER_STUDIOS]: EProviderCode.THE_EAR_GAMEBURGER_STUDIOS,
  [EProviderCode.THE_EAR_GAME_FISH_GLOBAL]: EProviderCode.THE_EAR_GAME_FISH_GLOBAL,
  [EProviderCode.THE_EAR_GAMEVY]: EProviderCode.THE_EAR_GAMEVY,
  [EProviderCode.THE_EAR_GOLDEN_ROCK_STUDIOS]: EProviderCode.THE_EAR_GOLDEN_ROCK_STUDIOS,
  [EProviderCode.THE_EAR_HACKSAW_GAMING]: EProviderCode.THE_EAR_HACKSAW_GAMING,
  [EProviderCode.THE_EAR_INSPIRED_GAMING]: EProviderCode.THE_EAR_INSPIRED_GAMING,
  [EProviderCode.THE_EAR_IRON_DOG_STUDIOS]: EProviderCode.THE_EAR_IRON_DOG_STUDIOS,
  [EProviderCode.THE_EAR_JFTW]: EProviderCode.THE_EAR_JFTW,
  [EProviderCode.THE_EAR_JUST_PLAY]: EProviderCode.THE_EAR_JUST_PLAY,
  [EProviderCode.THE_EAR_KALAMBA]: EProviderCode.THE_EAR_KALAMBA,
  [EProviderCode.THE_EAR_KING_MAKER]: EProviderCode.THE_EAR_KING_MAKER,
  [EProviderCode.THE_EAR_LIGHTNING_BOX]: EProviderCode.THE_EAR_LIGHTNING_BOX,
  [EProviderCode.THE_EAR_LIVE_G24]: EProviderCode.THE_EAR_LIVE_G24,
  [EProviderCode.THE_EAR_MGA]: EProviderCode.THE_EAR_MGA,
  [EProviderCode.THE_EAR_NEMESIS]: EProviderCode.THE_EAR_NEMESIS,
  [EProviderCode.THE_EAR_NEON_VALLEY_STUDIOS]: EProviderCode.THE_EAR_NEON_VALLEY_STUDIOS,
  [EProviderCode.THE_EAR_NJOY]: EProviderCode.THE_EAR_NJOY,
  [EProviderCode.THE_EAR_ONLY_PLAY]: EProviderCode.THE_EAR_ONLY_PLAY,
  [EProviderCode.THE_EAR_ORTIZ]: EProviderCode.THE_EAR_ORTIZ,
  [EProviderCode.THE_EAR_PATAGONIA]: EProviderCode.THE_EAR_PATAGONIA,
  [EProviderCode.THE_EAR_PLANK_GAMING]: EProviderCode.THE_EAR_PLANK_GAMING,
  [EProviderCode.THE_EAR_PLATIN_GAMING]: EProviderCode.THE_EAR_PLATIN_GAMING,
  [EProviderCode.THE_EAR_PROBABILITY_JONES]: EProviderCode.THE_EAR_PROBABILITY_JONES,
  [EProviderCode.THE_EAR_PULSE_8]: EProviderCode.THE_EAR_PULSE_8,
  [EProviderCode.THE_EAR_RABCAT]: EProviderCode.THE_EAR_RABCAT,
  [EProviderCode.THE_EAR_REALISTIC_GAMES]: EProviderCode.THE_EAR_REALISTIC_GAMES,
  [EProviderCode.THE_EAR_SA_GAMING]: EProviderCode.THE_EAR_SA_GAMING,
  [EProviderCode.THE_EAR_SLINGSHOT_STUDIOS]: EProviderCode.THE_EAR_SLINGSHOT_STUDIOS,
  [EProviderCode.THE_EAR_SPINOMENAL]: EProviderCode.THE_EAR_SPINOMENAL,
  [EProviderCode.THE_EAR_SPINTHON]: EProviderCode.THE_EAR_SPINTHON,
  [EProviderCode.THE_EAR_SUPERNOVA]: EProviderCode.THE_EAR_SUPERNOVA,
  [EProviderCode.THE_EAR_SWITCH_STUDIOS]: EProviderCode.THE_EAR_SWITCH_STUDIOS,
  [EProviderCode.THE_EAR_TGC]: EProviderCode.THE_EAR_TGC,
  [EProviderCode.THE_EAR_TOM_HORN]: EProviderCode.THE_EAR_TOM_HORN,
  [EProviderCode.THE_EAR_TRIPLE_EDGE]: EProviderCode.THE_EAR_TRIPLE_EDGE,
  [EProviderCode.THE_EAR_TWO_BY_TWO]: EProviderCode.THE_EAR_TWO_BY_TWO,
  [EProviderCode.THE_EAR_VIBRA_GAMING]: EProviderCode.THE_EAR_VIBRA_GAMING,
  [EProviderCode.THE_EAR_WE_ARE_CASINO]: EProviderCode.THE_EAR_WE_ARE_CASINO,
  [EProviderCode.THE_EAR_MPLAY]: EProviderCode.THE_EAR_MPLAY,
  [EProviderCode.THE_EAR_SUPER_SPADE_GAMES]: EProviderCode.THE_EAR_SUPER_SPADE_GAMES,
  [EProviderCode.THE_EAR_PLAYN_GO]: EProviderCode.THE_EAR_PLAYN_GO,

  [EProviderCode.EVOPLAY]: EProviderCode.EVOPLAY,

  [EProviderCode.BOLDPLAY]: EProviderCode.BOLDPLAY,

  [EProviderCode.SMARTSOFT]: EProviderCode.SMARTSOFT,

  [EProviderCode.RELAX_GAMING]: EProviderCode.RELAX_GAMING,
  [EProviderCode.RELAX_GAMING_BLUE_GURU_GAMES]: EProviderCode.RELAX_GAMING_BLUE_GURU_GAMES,
  [EProviderCode.RELAX_GAMING_ELECTRIC_ELEPHANT]: EProviderCode.RELAX_GAMING_ELECTRIC_ELEPHANT,
  [EProviderCode.RELAX_GAMING_FANTASMA_GAMES]: EProviderCode.RELAX_GAMING_FANTASMA_GAMES,
  [EProviderCode.RELAX_GAMING_FELT]: EProviderCode.RELAX_GAMING_FELT,
  [EProviderCode.RELAX_GAMING_4THEPLAYER]: EProviderCode.RELAX_GAMING_4THEPLAYER,
  [EProviderCode.RELAX_GAMING_FOUR_LEAF_GAMING]: EProviderCode.RELAX_GAMING_FOUR_LEAF_GAMING,
  [EProviderCode.RELAX_GAMING_KALAMBA]: EProviderCode.RELAX_GAMING_KALAMBA,
  [EProviderCode.RELAX_GAMING_MAX_WIN_GAMING]: EProviderCode.RELAX_GAMING_MAX_WIN_GAMING,
  [EProviderCode.RELAX_GAMING_NORTHERN_LIGHTS]: EProviderCode.RELAX_GAMING_NORTHERN_LIGHTS,
  [EProviderCode.RELAX_GAMING_PRINT_STUDIOS]: EProviderCode.RELAX_GAMING_PRINT_STUDIOS,
  [EProviderCode.RELAX_GAMING_STHLMGAMING]: EProviderCode.RELAX_GAMING_STHLMGAMING,
  [EProviderCode.RELAX_GAMING_SILVERBACK_GAMING]: EProviderCode.RELAX_GAMING_SILVERBACK_GAMING,
  [EProviderCode.RELAX_GAMING_STORM_GAMING]: EProviderCode.RELAX_GAMING_STORM_GAMING,
  [EProviderCode.RELAX_GAMING_HACKSAW_GAMING]: EProviderCode.RELAX_GAMING_HACKSAW_GAMING,
  [EProviderCode.RELAX_GAMING_NET_GAMING]: EProviderCode.RELAX_GAMING_NET_GAMING,
  [EProviderCode.RELAX_GAMING_BOOMING_GAMES]: EProviderCode.RELAX_GAMING_BOOMING_GAMES,
  [EProviderCode.RELAX_GAMING_APOLLO_GAMES]: EProviderCode.RELAX_GAMING_APOLLO_GAMES,
  [EProviderCode.RELAX_GAMING_LADY_LUCK]: EProviderCode.RELAX_GAMING_LADY_LUCK,
  [EProviderCode.RELAX_GAMING_HIGH5]: EProviderCode.RELAX_GAMING_HIGH5,

  [EProviderCode.VIVO_GAMING]: EProviderCode.VIVO_GAMING,

  [EProviderCode.WAZDAN]: EProviderCode.WAZDAN,

  [EProviderCode.REEVO]: EProviderCode.REEVO,

  [EProviderCode.BET_SOLUTIONS]: EProviderCode.BET_SOLUTIONS,

  [EProviderCode.BETSOFT]: EProviderCode.BETSOFT,

  [EProviderCode.RUBY_PLAY]: EProviderCode.RUBY_PLAY,

  [EProviderCode.AMUSNET]: EProviderCode.AMUSNET,

  [EProviderCode.GMAG]: EProviderCode.GMAG,
  [EProviderCode.GMAG_PLAYTECH]: EProviderCode.GMAG_PLAYTECH,
  [EProviderCode.GMAG_MICROGAMING]: EProviderCode.GMAG_MICROGAMING,
  [EProviderCode.GMAG_GAMES_GLOBAL]: EProviderCode.GMAG_GAMES_GLOBAL,
  [EProviderCode.GMAG_BLUEPRINT]: EProviderCode.GMAG_BLUEPRINT,
  [EProviderCode.GMAG_PLAY_AND_GO]: EProviderCode.GMAG_PLAY_AND_GO,
  [EProviderCode.GMAG_PLAYTECH_N]: EProviderCode.GMAG_PLAYTECH_N,

  [EProviderCode.BET_GAMES]: EProviderCode.BET_GAMES,
  [EProviderCode.BET_GAMES_TWAIN]: EProviderCode.BET_GAMES_TWAIN,

  [EProviderCode.PLAYSON]: EProviderCode.PLAYSON,

  [EProviderCode.SPRIBE]: EProviderCode.SPRIBE,

  [EProviderCode.LIVE_SPINS]: EProviderCode.LIVE_SPINS,

  [EProviderCode.NLC]: EProviderCode.NLC,

  [EProviderCode.SPADEGAMING]: EProviderCode.SPADEGAMING,

  [EProviderCode.PLATIPUS]: EProviderCode.PLATIPUS,

  [EProviderCode.ELYSIUM]: EProviderCode.ELYSIUM,

  [EProviderCode.TVBET]: EProviderCode.TVBET,
  [EProviderCode.TVBET_SPINMATIC]: EProviderCode.TVBET_SPINMATIC,
  [EProviderCode.TVBET_GOLDEN_RACE]: EProviderCode.TVBET_GOLDEN_RACE,

  [EProviderCode.RED_RAKE]: EProviderCode.RED_RAKE,

  [EProviderCode.KIRON]: EProviderCode.KIRON,

  [EProviderCode.ZEUS_GAMING]: EProviderCode.ZEUS_GAMING,

  [EProviderCode.ONE_X_TWO_NETWORK]: EProviderCode.ONE_X_TWO_NETWORK,
  [EProviderCode.ONE_X_TWO_NETWORK_PROSPECT_GAMING]: EProviderCode.ONE_X_TWO_NETWORK_PROSPECT_GAMING,
  [EProviderCode.ONE_X_TWO_NETWORK_IRON_DOG_STUDIO]: EProviderCode.ONE_X_TWO_NETWORK_IRON_DOG_STUDIO,
  [EProviderCode.ONE_X_TWO_NETWORK_AD_LUNAM]: EProviderCode.ONE_X_TWO_NETWORK_AD_LUNAM,

  [EProviderCode.SGTV]: EProviderCode.SGTV,

  [EProviderCode.BF_GAMES]: EProviderCode.BF_GAMES,

  [EProviderCode.GGAMES]: EProviderCode.GGAMES,

  [EProviderCode.SLOTMATRIX]: EProviderCode.SLOTMATRIX,
  [EProviderCode.SLOTMATRIX_RIVAL_POWERED]: EProviderCode.SLOTMATRIX_RIVAL_POWERED,

  [EProviderCode.BETFAIR]: EProviderCode.BETFAIR,

  [EProviderCode.PGSOFT]: EProviderCode.PGSOFT,

  [EProviderCode.OCTOPLAY]: EProviderCode.OCTOPLAY,

  [EProviderCode.DAINTREE_GAMING]: EProviderCode.DAINTREE_GAMING,

  [EProviderCode.YOLTED]: EProviderCode.YOLTED,

  [EProviderCode.CALETA]: EProviderCode.CALETA,

  [EProviderCode.GALAXSYS]: EProviderCode.GALAXSYS,

  [EProviderCode.QUICKSPIN]: EProviderCode.QUICKSPIN,

  [EProviderCode.COZMO_PLAY]: EProviderCode.COZMO_PLAY,

  [EProviderCode.KALAMBA]: EProviderCode.KALAMBA,

  [EProviderCode.ASPECT_GAMING]: EProviderCode.ASPECT_GAMING,

  [EProviderCode.EURASIAN_GAMING]: EProviderCode.EURASIAN_GAMING,

  [EProviderCode.INVII_PRAGMATIC_PLAY]: EProviderCode.INVII_PRAGMATIC_PLAY,

  [EProviderCode.COZMO_LIVE]: EProviderCode.COZMO_LIVE,

  [EProviderCode.EXA_GAMING]: EProviderCode.EXA_GAMING,
} as const;

type TGameProviderEnum = typeof gameProviderEnum[keyof typeof gameProviderEnum];

const isGameProvider = (
  provider: EProviderCode,
): provider is Exclude<TGameProviderEnum, typeof gameProviderEnum.ALL_PROVIDERS> => provider in gameProviderEnum;

const gameProviderTabs: Record<TGameProviderEnum, string> = { // string = TGameProviderTab
  [gameProviderEnum.ALL_PROVIDERS]: "all",
  [gameProviderEnum[EProviderCode.EZUGI]]: "ezugi",
  [gameProviderEnum[EProviderCode.EZUGI_EVOLUTION]]: "evolution_casino",
  [gameProviderEnum[EProviderCode.PRAGMATIC_PLAY]]: "pragmatic_play",
  [gameProviderEnum[EProviderCode.ONE_TOUCH]]: "one_touch",
  [gameProviderEnum[EProviderCode.ABSOLUTE_LIVE_GAMING]]: "absolute_live_gaming",
  [gameProviderEnum[EProviderCode.ABSOLUTE_LIVE_GAMING_7_MOJOS]]: "7_mojos",
  [gameProviderEnum[EProviderCode.LUCKY_STREAK]]: "lucky_streak",
  [gameProviderEnum[EProviderCode.LUCKY_STREAK_BOONGO]]: "3Oaks",
  [gameProviderEnum[EProviderCode.LUCKY_STREAK_FUGASO]]: "fugaso_casino",
  [gameProviderEnum[EProviderCode.LUCKY_STREAK_SPINOMENAL]]: "spinomenal_casino",
  [gameProviderEnum[EProviderCode.LUCKY_STREAK_TOM_HORN]]: "tom_horn_casino",
  [gameProviderEnum[EProviderCode.LUCKY_STREAK_TURBO_GAMES]]: "turbo_games",
  [gameProviderEnum[EProviderCode.LUCKY_STREAK_YGGDRASIL]]: "yggdrasil",
  [gameProviderEnum[EProviderCode.FALCON_GAMING]]: "falcon_gaming",
  [gameProviderEnum[EProviderCode.ENDORPHINA]]: "endorphina",
  [gameProviderEnum[EProviderCode.LEAP_GAMING]]: "leap_gaming",
  [gameProviderEnum[EProviderCode.EVOLUTION]]: "evolution_gaming",
  [gameProviderEnum[EProviderCode.EVOLUTION_REDTIGER]]: "redtiger",
  [gameProviderEnum[EProviderCode.EVOLUTION_NETENT]]: "netent",
  [gameProviderEnum[EProviderCode.EVOLUTION_NLC]]: "nlc_casino",
  [gameProviderEnum[EProviderCode.EVOLUTION_BTG]]: "btg",
  [gameProviderEnum[EProviderCode.BGAMING]]: "bgaming",
  [gameProviderEnum[EProviderCode.THE_EAR]]: "the_ear",
  [gameProviderEnum[EProviderCode.THE_EAR_AMATIC]]: "amatic",
  [gameProviderEnum[EProviderCode.THE_EAR_AINSWORTH_GAMES]]: "ainsworth_games",
  [gameProviderEnum[EProviderCode.THE_EAR_GENESIS_GAMING]]: "genesis_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_TRIPPLE_CHERRY]]: "tripple_cherry",
  [gameProviderEnum[EProviderCode.THE_EAR_HABANERO]]: "habanero",
  [gameProviderEnum[EProviderCode.THE_EAR_STORMCRAFT_STUDIOS]]: "stormcraft_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_GAMZIX]]: "gamzix",
  [gameProviderEnum[EProviderCode.THE_EAR_MACAW_GAMING]]: "macaw_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_AUGUST_GAMING]]: "august_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_BELATRA]]: "belatra",
  [gameProviderEnum[EProviderCode.THE_EAR_MR_SLOTTY]]: "mr_slotty",
  [gameProviderEnum[EProviderCode.THE_EAR_PLAY_PEARLS]]: "play_pearls",
  [gameProviderEnum[EProviderCode.THE_EAR_WOOHOO_GAMES]]: "woohoo_games",
  [gameProviderEnum[EProviderCode.THE_EAR_FELIX_GAMING]]: "felix_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_GAMES_INC]]: "games_inc",
  [gameProviderEnum[EProviderCode.THE_EAR_GREEN_JADE]]: "green_jade",
  [gameProviderEnum[EProviderCode.THE_EAR_KA_GAMING]]: "ka_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_4THEPLAYER]]: "4theplayer_casino",
  [gameProviderEnum[EProviderCode.THE_EAR_FAZI]]: "fazi",
  [gameProviderEnum[EProviderCode.THE_EAR_PARIPLAY]]: "pariplay",
  [gameProviderEnum[EProviderCode.THE_EAR_REEL_PLAY]]: "reel_play",
  [gameProviderEnum[EProviderCode.THE_EAR_STHLMGAMING]]: "sthlmgaming_casino",
  [gameProviderEnum[EProviderCode.THE_EAR_AWC68]]: "awc68",
  [gameProviderEnum[EProviderCode.THE_EAR_ALL41_STUDIOS]]: "all41_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_APOLLO]]: "apollo",
  [gameProviderEnum[EProviderCode.THE_EAR_BOOMING]]: "booming_games",
  [gameProviderEnum[EProviderCode.THE_EAR_BOOONGO]]: "booongo",
  [gameProviderEnum[EProviderCode.THE_EAR_CONCEPT_GAMING]]: "concept_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_CRAZY_TOOTH]]: "crazy_tooth",
  [gameProviderEnum[EProviderCode.THE_EAR_CT_INTERACTIVE]]: "ct_interactive",
  [gameProviderEnum[EProviderCode.THE_EAR_ELECTRIC_ELEPHANT]]: "electric_elephant_casino",
  [gameProviderEnum[EProviderCode.THE_EAR_EYECON]]: "eyecon",
  [gameProviderEnum[EProviderCode.THE_EAR_FILS_GAME]]: "fils",
  [gameProviderEnum[EProviderCode.THE_EAR_FORTUNE_FACTORY_STUDIOS]]: "fortune_factory_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_FOXIUM]]: "foxium",
  [gameProviderEnum[EProviderCode.THE_EAR_FUGASO]]: "fugaso",
  [gameProviderEnum[EProviderCode.THE_EAR_GAME_MEDIA_WORKS]]: "game_media_works",
  [gameProviderEnum[EProviderCode.THE_EAR_GAME_ART]]: "game_art",
  [gameProviderEnum[EProviderCode.THE_EAR_GAMEBURGER_STUDIOS]]: "gameburger_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_GAME_FISH_GLOBAL]]: "game_fish_global",
  [gameProviderEnum[EProviderCode.THE_EAR_GAMEVY]]: "gamevy",
  [gameProviderEnum[EProviderCode.THE_EAR_GOLDEN_ROCK_STUDIOS]]: "golden_rock_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_HACKSAW_GAMING]]: "hacksaw_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_INSPIRED_GAMING]]: "inspired_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_IRON_DOG_STUDIOS]]: "iron_dog_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_JFTW]]: "jftw",
  [gameProviderEnum[EProviderCode.THE_EAR_JUST_PLAY]]: "just_play",
  [gameProviderEnum[EProviderCode.THE_EAR_KALAMBA]]: "kalamba_casino",
  [gameProviderEnum[EProviderCode.THE_EAR_KING_MAKER]]: "king_maker",
  [gameProviderEnum[EProviderCode.THE_EAR_LIGHTNING_BOX]]: "lightning_box",
  [gameProviderEnum[EProviderCode.THE_EAR_LIVE_G24]]: "live_g24",
  [gameProviderEnum[EProviderCode.THE_EAR_MGA]]: "mga",
  [gameProviderEnum[EProviderCode.THE_EAR_NEMESIS]]: "nemesis",
  [gameProviderEnum[EProviderCode.THE_EAR_NEON_VALLEY_STUDIOS]]: "neon_valley_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_NJOY]]: "njoy",
  [gameProviderEnum[EProviderCode.THE_EAR_ONLY_PLAY]]: "only_play",
  [gameProviderEnum[EProviderCode.THE_EAR_ORTIZ]]: "ortiz",
  [gameProviderEnum[EProviderCode.THE_EAR_PATAGONIA]]: "patagonia",
  [gameProviderEnum[EProviderCode.THE_EAR_PLANK_GAMING]]: "plank_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_PLATIN_GAMING]]: "platin_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_PROBABILITY_JONES]]: "probability_jones",
  [gameProviderEnum[EProviderCode.THE_EAR_PULSE_8]]: "pulse_8",
  [gameProviderEnum[EProviderCode.THE_EAR_RABCAT]]: "rabcat",
  [gameProviderEnum[EProviderCode.THE_EAR_REALISTIC_GAMES]]: "realistic_games",
  [gameProviderEnum[EProviderCode.THE_EAR_SA_GAMING]]: "sagaming",
  [gameProviderEnum[EProviderCode.THE_EAR_SLINGSHOT_STUDIOS]]: "slingshot_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_SPINOMENAL]]: "spinomenal",
  [gameProviderEnum[EProviderCode.THE_EAR_SPINTHON]]: "spinthon",
  [gameProviderEnum[EProviderCode.THE_EAR_SUPERNOVA]]: "supernowa",
  [gameProviderEnum[EProviderCode.THE_EAR_SWITCH_STUDIOS]]: "switch_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_TGC]]: "tgc",
  [gameProviderEnum[EProviderCode.THE_EAR_TOM_HORN]]: "tom_horn",
  [gameProviderEnum[EProviderCode.THE_EAR_TRIPLE_EDGE]]: "triple_edge_studios",
  [gameProviderEnum[EProviderCode.THE_EAR_TWO_BY_TWO]]: "two_by_two",
  [gameProviderEnum[EProviderCode.THE_EAR_VIBRA_GAMING]]: "vibra_gaming",
  [gameProviderEnum[EProviderCode.THE_EAR_WE_ARE_CASINO]]: "we_are_casino",
  [gameProviderEnum[EProviderCode.THE_EAR_MPLAY]]: "mplay",
  [gameProviderEnum[EProviderCode.THE_EAR_SUPER_SPADE_GAMES]]: "super_spade_games",
  [gameProviderEnum[EProviderCode.THE_EAR_PLAYN_GO]]: "playn_go",
  [gameProviderEnum[EProviderCode.EVOPLAY]]: "evoplay",
  [gameProviderEnum[EProviderCode.BOLDPLAY]]: "boldplay",
  [gameProviderEnum[EProviderCode.SMARTSOFT]]: "smartsoft",
  [gameProviderEnum[EProviderCode.RELAX_GAMING]]: "relax_gaming",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_BLUE_GURU_GAMES]]: "blue_guru_games",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_ELECTRIC_ELEPHANT]]: "electric_elephant",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_FANTASMA_GAMES]]: "fantasma_games",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_FELT]]: "felt",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_4THEPLAYER]]: "4theplayer",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_FOUR_LEAF_GAMING]]: "four_leaf_gaming",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_KALAMBA]]: "kalamba_games",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_MAX_WIN_GAMING]]: "max_win_gaming",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_NORTHERN_LIGHTS]]: "northern_lights",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_PRINT_STUDIOS]]: "print_studios",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_STHLMGAMING]]: "sthlmgaming",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_SILVERBACK_GAMING]]: "silverback_gaming",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_STORM_GAMING]]: "storm_gaming",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_HACKSAW_GAMING]]: "hacksaw_gaming_casino",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_NET_GAMING]]: "net_gaming",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_BOOMING_GAMES]]: "booming_games_casino",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_APOLLO_GAMES]]: "apollo_games",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_LADY_LUCK]]: "lady_luck",
  [gameProviderEnum[EProviderCode.RELAX_GAMING_HIGH5]]: "high5",
  [gameProviderEnum[EProviderCode.VIVO_GAMING]]: "vivo_gaming",
  [gameProviderEnum[EProviderCode.WAZDAN]]: "wazdan",
  [gameProviderEnum[EProviderCode.REEVO]]: "reevo",
  [gameProviderEnum[EProviderCode.BET_SOLUTIONS]]: "bet_solutions",
  [gameProviderEnum[EProviderCode.BETSOFT]]: "betsoft",
  [gameProviderEnum[EProviderCode.RUBY_PLAY]]: "ruby_play",
  [gameProviderEnum[EProviderCode.AMUSNET]]: "amusnet",
  [gameProviderEnum[EProviderCode.GMAG]]: "gmag",
  [gameProviderEnum[EProviderCode.GMAG_PLAYTECH]]: "playtech",
  [gameProviderEnum[EProviderCode.GMAG_MICROGAMING]]: "microgaming",
  [gameProviderEnum[EProviderCode.GMAG_GAMES_GLOBAL]]: "games_global",
  [gameProviderEnum[EProviderCode.GMAG_BLUEPRINT]]: "blueprint",
  [gameProviderEnum[EProviderCode.GMAG_PLAY_AND_GO]]: "play_and_go",
  [gameProviderEnum[EProviderCode.GMAG_PLAYTECH_N]]: "playtech_n",
  [gameProviderEnum[EProviderCode.BET_GAMES]]: "bet_games",
  [gameProviderEnum[EProviderCode.BET_GAMES_TWAIN]]: "twain",
  [gameProviderEnum[EProviderCode.PLAYSON]]: "playson",
  [gameProviderEnum[EProviderCode.SPRIBE]]: "spribe",
  [gameProviderEnum[EProviderCode.LIVE_SPINS]]: "livespins",
  [gameProviderEnum[EProviderCode.NLC]]: "nlc",
  [gameProviderEnum[EProviderCode.SPADEGAMING]]: "spadegaming",
  [gameProviderEnum[EProviderCode.PLATIPUS]]: "platipus",
  [gameProviderEnum[EProviderCode.ELYSIUM]]: "elysium",
  [gameProviderEnum[EProviderCode.TVBET]]: "tvbet",
  [gameProviderEnum[EProviderCode.TVBET_SPINMATIC]]: "spinmatic",
  [gameProviderEnum[EProviderCode.TVBET_GOLDEN_RACE]]: "golden_race",
  [gameProviderEnum[EProviderCode.RED_RAKE]]: "red_rake",
  [gameProviderEnum[EProviderCode.KIRON]]: "kiron",
  [gameProviderEnum[EProviderCode.ZEUS_GAMING]]: "zeus_play",
  [gameProviderEnum[EProviderCode.ONE_X_TWO_NETWORK]]: "1x2_network",
  [gameProviderEnum[EProviderCode.ONE_X_TWO_NETWORK_PROSPECT_GAMING]]: "prospect_gaming",
  [gameProviderEnum[EProviderCode.ONE_X_TWO_NETWORK_IRON_DOG_STUDIO]]: "iron_dog_studio_casino",
  [gameProviderEnum[EProviderCode.ONE_X_TWO_NETWORK_AD_LUNAM]]: "ad_lunam",
  [gameProviderEnum[EProviderCode.SGTV]]: "sgtv",
  [gameProviderEnum[EProviderCode.BF_GAMES]]: "bf_games",
  [gameProviderEnum[EProviderCode.GGAMES]]: "ggames",
  [gameProviderEnum[EProviderCode.SLOTMATRIX]]: "slotmatrix",
  [gameProviderEnum[EProviderCode.SLOTMATRIX_RIVAL_POWERED]]: "rival_powered",
  [gameProviderEnum[EProviderCode.BETFAIR]]: "betfair",
  [gameProviderEnum[EProviderCode.PGSOFT]]: "pgsoft",
  [gameProviderEnum[EProviderCode.OCTOPLAY]]: "octoplay",
  [gameProviderEnum[EProviderCode.DAINTREE_GAMING]]: "originals",
  [gameProviderEnum[EProviderCode.YOLTED]]: "yolted",
  [gameProviderEnum[EProviderCode.CALETA]]: "caleta",
  [gameProviderEnum[EProviderCode.GALAXSYS]]: "galaxsys",
  [gameProviderEnum[EProviderCode.QUICKSPIN]]: "quickspin",
  [gameProviderEnum[EProviderCode.COZMO_PLAY]]: "cozmo_play",
  [gameProviderEnum[EProviderCode.KALAMBA]]: "kalamba",
  [gameProviderEnum[EProviderCode.ASPECT_GAMING]]: "aspect_gaming",
  [gameProviderEnum[EProviderCode.EURASIAN_GAMING]]: "eurasian_gaming",
  [gameProviderEnum[EProviderCode.INVII_PRAGMATIC_PLAY]]: "pragmatic__play",
  [gameProviderEnum[EProviderCode.COZMO_LIVE]]: "cozmo_live",
  [gameProviderEnum[EProviderCode.EXA_GAMING]]: "exa_gaming",
} as const;

type TGameProviderTab = typeof gameProviderTabs extends Record<TGameProviderEnum, infer I> ? I : never

const tabsToGameProvider: Record<TGameProviderTab, TGameProviderEnum> = reverseMap(gameProviderTabs);

const getOriginalName = () => {
  if (!process.env.THEME) {
    return "Originals";
  }

  return `${capitalizeFirstLetter(process.env.THEME)} Originals`;
};

const gameProviderName: Record<TGameProviderEnum, string> = {
  ALL_PROVIDERS: "All Providers",
  [EProviderCode.EZUGI]: "Ezugi Casino",
  [EProviderCode.EZUGI_EVOLUTION]: "Evolution Gaming",
  [EProviderCode.PRAGMATIC_PLAY]: "Pragmatic Play",
  [EProviderCode.ONE_TOUCH]: "OneTouch",
  [EProviderCode.ABSOLUTE_LIVE_GAMING]: "Absolute Live Gaming",
  [EProviderCode.ABSOLUTE_LIVE_GAMING_7_MOJOS]: "7 Mojos",
  [EProviderCode.LUCKY_STREAK]: "Lucky Streak",
  [EProviderCode.LUCKY_STREAK_BOONGO]: "3Oaks",
  [EProviderCode.LUCKY_STREAK_FUGASO]: "Fugaso",
  [EProviderCode.LUCKY_STREAK_SPINOMENAL]: "Spinomenal",
  [EProviderCode.LUCKY_STREAK_TOM_HORN]: "Tom Horn",
  [EProviderCode.LUCKY_STREAK_TURBO_GAMES]: "Turbo Games",
  [EProviderCode.LUCKY_STREAK_YGGDRASIL]: "Yggdrasil",
  [EProviderCode.FALCON_GAMING]: "Falcon Gaming",
  [EProviderCode.ENDORPHINA]: "Endorphina",
  [EProviderCode.LEAP_GAMING]: "Leap Gaming",
  [EProviderCode.EVOLUTION]: "Evolution Gaming",
  [EProviderCode.EVOLUTION_REDTIGER]: "Redtiger",
  [EProviderCode.EVOLUTION_NETENT]: "Netent",
  [EProviderCode.EVOLUTION_NLC]: "NLC",
  [EProviderCode.EVOLUTION_BTG]: "BTG",
  [EProviderCode.BGAMING]: "BGaming",
  [EProviderCode.THE_EAR]: "The Ear",
  [EProviderCode.THE_EAR_AMATIC]: "Amatic",
  [EProviderCode.THE_EAR_AINSWORTH_GAMES]: "Ainsworth Games",
  [EProviderCode.THE_EAR_GENESIS_GAMING]: "Genesis Gaming",
  [EProviderCode.THE_EAR_TRIPPLE_CHERRY]: "Tripple Cherry",
  [EProviderCode.THE_EAR_HABANERO]: "Habanero",
  [EProviderCode.THE_EAR_STORMCRAFT_STUDIOS]: "Stormcraft Studios",
  [EProviderCode.THE_EAR_GAMZIX]: "Gamzix",
  [EProviderCode.THE_EAR_MACAW_GAMING]: "Macaw Gaming",
  [EProviderCode.THE_EAR_AUGUST_GAMING]: "August Gaming",
  [EProviderCode.THE_EAR_BELATRA]: "Belatra",
  [EProviderCode.THE_EAR_MR_SLOTTY]: "Mrslotty",
  [EProviderCode.THE_EAR_PLAY_PEARLS]: "PlayPearls",
  [EProviderCode.THE_EAR_WOOHOO_GAMES]: "WooHoo Games",
  [EProviderCode.THE_EAR_FELIX_GAMING]: "Felix Gaming",
  [EProviderCode.THE_EAR_GAMES_INC]: "Games Inc",
  [EProviderCode.THE_EAR_GREEN_JADE]: "Green Jade",
  [EProviderCode.THE_EAR_KA_GAMING]: "KA Gaming",
  [EProviderCode.THE_EAR_4THEPLAYER]: "4ThePlayer",
  [EProviderCode.THE_EAR_FAZI]: "Fazi",
  [EProviderCode.THE_EAR_PARIPLAY]: "Pariplay",
  [EProviderCode.THE_EAR_REEL_PLAY]: "Reel play",
  [EProviderCode.THE_EAR_STHLMGAMING]: "STHLMGAMING",
  [EProviderCode.THE_EAR_AWC68]: "AWC68",
  [EProviderCode.THE_EAR_ALL41_STUDIOS]: "All41 Studios",
  [EProviderCode.THE_EAR_APOLLO]: "Apollo",
  [EProviderCode.THE_EAR_BOOMING]: "Booming Games",
  [EProviderCode.THE_EAR_BOOONGO]: "Booongo",
  [EProviderCode.THE_EAR_CONCEPT_GAMING]: "Concept Gaming",
  [EProviderCode.THE_EAR_CRAZY_TOOTH]: "Crazy Tooth",
  [EProviderCode.THE_EAR_CT_INTERACTIVE]: "CT Interactive",
  [EProviderCode.THE_EAR_ELECTRIC_ELEPHANT]: "Electric Elephant",
  [EProviderCode.THE_EAR_EYECON]: "Eyecon",
  [EProviderCode.THE_EAR_FILS_GAME]: "Fils",
  [EProviderCode.THE_EAR_FORTUNE_FACTORY_STUDIOS]: "Fortune Factory Studios",
  [EProviderCode.THE_EAR_FOXIUM]: "Foxium",
  [EProviderCode.THE_EAR_FUGASO]: "Fugaso",
  [EProviderCode.THE_EAR_GAME_MEDIA_WORKS]: "Game Media Works",
  [EProviderCode.THE_EAR_GAME_ART]: "Gameart",
  [EProviderCode.THE_EAR_GAMEBURGER_STUDIOS]: "Gameburger Studios",
  [EProviderCode.THE_EAR_GAME_FISH_GLOBAL]: "Game Fish Global",
  [EProviderCode.THE_EAR_GAMEVY]: "Gamevy",
  [EProviderCode.THE_EAR_GOLDEN_ROCK_STUDIOS]: "Golden Rock Studios",
  [EProviderCode.THE_EAR_HACKSAW_GAMING]: "HackSaw Gaming",
  [EProviderCode.THE_EAR_INSPIRED_GAMING]: "Inspired Gaming",
  [EProviderCode.THE_EAR_IRON_DOG_STUDIOS]: "Iron Dog Studios",
  [EProviderCode.THE_EAR_JFTW]: "JFTW",
  [EProviderCode.THE_EAR_JUST_PLAY]: "JustPlay",
  [EProviderCode.THE_EAR_KALAMBA]: "Kalamba",
  [EProviderCode.THE_EAR_KING_MAKER]: "KingMaker",
  [EProviderCode.THE_EAR_LIGHTNING_BOX]: "Lightning Box",
  [EProviderCode.THE_EAR_LIVE_G24]: "LiveG24",
  [EProviderCode.THE_EAR_MGA]: "MGA",
  [EProviderCode.THE_EAR_NEMESIS]: "Nemesis",
  [EProviderCode.THE_EAR_NEON_VALLEY_STUDIOS]: "Neon Valley Studios",
  [EProviderCode.THE_EAR_NJOY]: "Njoy",
  [EProviderCode.THE_EAR_ONLY_PLAY]: "Only Play",
  [EProviderCode.THE_EAR_ORTIZ]: "Ortiz",
  [EProviderCode.THE_EAR_PATAGONIA]: "Patagonia",
  [EProviderCode.THE_EAR_PLANK_GAMING]: "Plank Gaming",
  [EProviderCode.THE_EAR_PLATIN_GAMING]: "Platin Gaming",
  [EProviderCode.THE_EAR_PROBABILITY_JONES]: "Probability Jones",
  [EProviderCode.THE_EAR_PULSE_8]: "Pulse 8",
  [EProviderCode.THE_EAR_RABCAT]: "Rabcat",
  [EProviderCode.THE_EAR_REALISTIC_GAMES]: "Realistic Games",
  [EProviderCode.THE_EAR_SA_GAMING]: "Sagaming",
  [EProviderCode.THE_EAR_SLINGSHOT_STUDIOS]: "Slingshot Studios",
  [EProviderCode.THE_EAR_SPINOMENAL]: "Spinomenal",
  [EProviderCode.THE_EAR_SPINTHON]: "Spinthon",
  [EProviderCode.THE_EAR_SUPERNOVA]: "Supernowa",
  [EProviderCode.THE_EAR_SWITCH_STUDIOS]: "Switch Studios",
  [EProviderCode.THE_EAR_TGC]: "TGC",
  [EProviderCode.THE_EAR_TOM_HORN]: "TomHorn",
  [EProviderCode.THE_EAR_TRIPLE_EDGE]: "Triple Edge Studios",
  [EProviderCode.THE_EAR_TWO_BY_TWO]: "Two By Two",
  [EProviderCode.THE_EAR_VIBRA_GAMING]: "Vibra Gaming",
  [EProviderCode.THE_EAR_WE_ARE_CASINO]: "We Are Casino",
  [EProviderCode.THE_EAR_MPLAY]: "Mplay",
  [EProviderCode.THE_EAR_PLAYN_GO]: "PlayN Go",
  [EProviderCode.THE_EAR_SUPER_SPADE_GAMES]: "Super Spade Games",
  [EProviderCode.EVOPLAY]: "Evoplay",
  [EProviderCode.BOLDPLAY]: "Boldplay",
  [EProviderCode.SMARTSOFT]: "Smartsoft",
  [EProviderCode.RELAX_GAMING]: "Relax Gaming",
  [EProviderCode.RELAX_GAMING_BLUE_GURU_GAMES]: "Blue Guru Games",
  [EProviderCode.RELAX_GAMING_ELECTRIC_ELEPHANT]: "Electric Elephant",
  [EProviderCode.RELAX_GAMING_FANTASMA_GAMES]: "Fantasma Games",
  [EProviderCode.RELAX_GAMING_FELT]: "Felt",
  [EProviderCode.RELAX_GAMING_4THEPLAYER]: "4ThePlayer",
  [EProviderCode.RELAX_GAMING_FOUR_LEAF_GAMING]: "Four Leaf Gaming",
  [EProviderCode.RELAX_GAMING_KALAMBA]: "Kalamba",
  [EProviderCode.RELAX_GAMING_MAX_WIN_GAMING]: "Max Win Gaming",
  [EProviderCode.RELAX_GAMING_NORTHERN_LIGHTS]: "Northern Lights",
  [EProviderCode.RELAX_GAMING_PRINT_STUDIOS]: "Print Studios",
  [EProviderCode.RELAX_GAMING_STHLMGAMING]: "STHLMGAMING",
  [EProviderCode.RELAX_GAMING_SILVERBACK_GAMING]: "Silverback Gaming",
  [EProviderCode.RELAX_GAMING_STORM_GAMING]: "Storm Gaming",
  [EProviderCode.RELAX_GAMING_HACKSAW_GAMING]: "Hacksaw Gaming",
  [EProviderCode.RELAX_GAMING_NET_GAMING]: "Net Gaming",
  [EProviderCode.RELAX_GAMING_BOOMING_GAMES]: "Booming Games",
  [EProviderCode.RELAX_GAMING_APOLLO_GAMES]: "Apollo Games",
  [EProviderCode.RELAX_GAMING_LADY_LUCK]: "Lady Luck",
  [EProviderCode.RELAX_GAMING_HIGH5]: "High 5",
  [EProviderCode.VIVO_GAMING]: "Vivo Gaming",
  [EProviderCode.WAZDAN]: "Wazdan",
  [EProviderCode.REEVO]: "Reevo",
  [EProviderCode.BET_SOLUTIONS]: "Bet Solutions",
  [EProviderCode.BETSOFT]: "Betsoft",
  [EProviderCode.RUBY_PLAY]: "Ruby Play",
  [EProviderCode.AMUSNET]: "Amusnet",
  [EProviderCode.GMAG]: "GMAG",
  [EProviderCode.GMAG_PLAYTECH]: "Playtech",
  [EProviderCode.GMAG_MICROGAMING]: "Microgaming",
  [EProviderCode.GMAG_GAMES_GLOBAL]: "Games Global",
  [EProviderCode.GMAG_BLUEPRINT]: "Blueprint",
  [EProviderCode.GMAG_PLAY_AND_GO]: "Play and Go",
  [EProviderCode.GMAG_PLAYTECH_N]: "Playtech N",
  [EProviderCode.BET_GAMES]: "BetGames",
  [EProviderCode.BET_GAMES_TWAIN]: "Twain",
  [EProviderCode.PLAYSON]: "Playson",
  [EProviderCode.SPRIBE]: "Spribe",
  [EProviderCode.LIVE_SPINS]: "Livespins",
  [EProviderCode.NLC]: "Nolimit City",
  [EProviderCode.SPADEGAMING]: "Spadegaming",
  [EProviderCode.PLATIPUS]: "Platipus",
  [EProviderCode.ELYSIUM]: "Elysium",
  [EProviderCode.TVBET]: "TVBET",
  [EProviderCode.TVBET_SPINMATIC]: "Spinmatic",
  [EProviderCode.TVBET_GOLDEN_RACE]: "Golden Race",
  [EProviderCode.RED_RAKE]: "Red Rake",
  [EProviderCode.KIRON]: "Kiron",
  [EProviderCode.ZEUS_GAMING]: "ZeusPlay",
  [EProviderCode.ONE_X_TWO_NETWORK]: "1x2 Network",
  [EProviderCode.ONE_X_TWO_NETWORK_PROSPECT_GAMING]: "Prospect Gaming",
  [EProviderCode.ONE_X_TWO_NETWORK_IRON_DOG_STUDIO]: "Iron Dog Studio",
  [EProviderCode.ONE_X_TWO_NETWORK_AD_LUNAM]: "Ad Lunam",
  [EProviderCode.SGTV]: "SGTV",
  [EProviderCode.BF_GAMES]: "BF Games",
  [EProviderCode.GGAMES]: "GGames",
  [EProviderCode.SLOTMATRIX]: "Slotmatrix",
  [EProviderCode.SLOTMATRIX_RIVAL_POWERED]: "Rival Powered",
  [EProviderCode.BETFAIR]: "Betfair",
  [EProviderCode.PGSOFT]: "PG Soft",
  [EProviderCode.OCTOPLAY]: "Octoplay",
  [EProviderCode.YOLTED]: "Yolted",
  [EProviderCode.CALETA]: "Caleta",
  [EProviderCode.DAINTREE_GAMING]: getOriginalName(),
  [EProviderCode.GALAXSYS]: "Galaxsys",
  [EProviderCode.QUICKSPIN]: "Quickspin",
  [EProviderCode.COZMO_PLAY]: "Cozmo play",
  [EProviderCode.KALAMBA]: "Kalamba",
  [EProviderCode.ASPECT_GAMING]: "Aspect gaming",
  [EProviderCode.EURASIAN_GAMING]: "Eurasian gaming",
  [EProviderCode.INVII_PRAGMATIC_PLAY]: "Pragmatic Play",
  [EProviderCode.COZMO_LIVE]: "Cozmo live",
  [EProviderCode.EXA_GAMING]: "Exa gaming",
};

export {
  gameProviderEnum,
  gameProviderName,
  tabsToGameProvider,
  gameProviderTabs,
  isGameProvider,
};
export type{ TGameProviderTab, TGameProviderEnum };
