import clsx from "clsx";
import { memo } from "react";
import classes from "./PaymentMethodIcon.module.css";
import { PAYMENT_METHOD_ID_MAP, type TPaymentMethodId } from "../../Store/Banking/Models/PaymentMethodIdModel";

interface IPaymentMethodIconProps extends IWithClassName {
  paymentMethodId: TPaymentMethodId;
}

const paymentMethodMap: Partial<Record<TPaymentMethodId, string | undefined>> = {
  [PAYMENT_METHOD_ID_MAP.ASTRO_PAY_DEPOSIT_ID]: classes.astroPay,
  [PAYMENT_METHOD_ID_MAP.ASTRO_PAY_WITHDRAWAL_ID]: classes.astroPay,

  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_COMMON_ID]: classes.crypto,

  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_LTC_ID]: classes.ltc,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_DASH_ID]: classes.dash,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_BTC_ID]: classes.btc,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_DOGE_ID]: classes.doge,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_USDC_ID]: classes.usdc,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_BTT_ID]: classes.btt,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_USDT_ID]: classes.usdt,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_ETH_ID]: classes.eth,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_TRX_ID]: classes.trx,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_BCH_ID]: classes.bch,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_RVN_ID]: classes.rvn,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_TON_ID]: classes.ton,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_DEPOSIT_XMR_ID]: classes.xmr,

  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_LTC_ID]: classes.ltc,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_DASH_ID]: classes.dash,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_BTC_ID]: classes.btc,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_DOGE_ID]: classes.doge,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_USDC_ID]: classes.usdc,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_BTT_ID]: classes.btt,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_USDT_ID]: classes.usdt,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_ETH_ID]: classes.eth,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_TRX_ID]: classes.trx,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_BCH_ID]: classes.bch,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_RVN_ID]: classes.rvn,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_TON_ID]: classes.ton,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_CRYPTO_WITHDRAWAL_XMR_ID]: classes.xmr,

  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_SISTEMNAKIT_PAPARA]: classes.bankTransfer,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_SISTEMNAKIT_CREDIT_CARD]: classes.card,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_PAYFIX]: classes.payfix,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_CEPPAY]: classes.ceppay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_VEGAPAY_HAVALE]: classes.vegapay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_VEGAPAY_PAPARA]: classes.vegapay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_ANINDA_MEFETE]: classes.mefete,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_SANALPAY]: classes.sanalpay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_ULTRAPAY_HAVALE]: classes.ultrapayHavale,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_ULTRAPAY_PAPARA]: classes.ultrapayPapara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_ULTRAPAY_AUTO_PAPARA]: classes.ultrapayAutoPapara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MULTIPAY_PEP]: classes.multipayPep,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MULTIPAY_HAVALE]: classes.multipayHavale,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MULTIPAY_HAYHAY]: classes.multipayHayhay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MULTIPAY_PAYCELL]: classes.multipayPaycell,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MULTIPAY_PARAZULA]: classes.multipayParazula,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MULTIPAY_PAROLAPARA]: classes.multipayParolaPara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MULTIPAY_PAYBOL]: classes.multipayPaybol,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MULTIPAY_PAPEL]: classes.multipayPapel,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_POPYPARA]: classes.popypara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_KOLAYPAY_KREDI_KARTI]: classes.kolaypayCred,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_KOLAYPAY_PAPARA]: classes.kolaypayPapara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_KOLAYPAY_HAVALE]: classes.kolaypayHavale,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_SISTEMNAKIT_HAVALE]: classes.sistemnakitHavale,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_FASTLINE_QR]: classes.fastlineQr,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_FASTLINE_CEPBANK]: classes.fastlineCepbank,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TR_HAVALE_EFT]: classes.trHavaleEft,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_PAYQASA]: classes.payqasa,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_FINPAY_HAVALE]: classes.finpay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_VEVO_HAVALE]: classes.vevo,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_VEVO_PARAZULA]: classes.vevoParazula,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_FASTLINE_ATM_QR]: classes.atmQr,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_FIN2]: classes.fin2,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_SERIPAY1]: classes.seripay1,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_MYPAYZ]: classes.mypayz,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_PAYFUTURE]: classes.payfuture,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_PAPARA]: classes.turkpayPapara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_PAYFIX]: classes.turkpayPayfix,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_PAYCO]: classes.turkpayPayco,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_ININAL]: classes.turkpayIninal,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_BANK_TRANSFER]: classes.turkpayBankTransfer,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_VIZYONPAY]: classes.turkpayVizyonpay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_AYPARA]: classes.turkpayAypara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_SIPAY]: classes.turkpaySipay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_DEPOSIT_TURKPAY_PAYCELL]: classes.turkpayPaycell,

  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_SISTEMNAKIT_PAPARA]: classes.bankTransfer,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_PAYFIX]: classes.payfix,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_CEPPAY]: classes.ceppay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_VEGAPAY_HAVALE]: classes.vegapay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_VEGAPAY_PAPARA]: classes.vegapay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_ANINDA_MEFETE]: classes.mefete,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_SANALPAY]: classes.sanalpay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_ULTRAPAY_HAVALE]: classes.ultrapayHavale,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_ULTRAPAY_PAPARA]: classes.ultrapayPapara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_ULTRAPAY_AUTO_PAPARA]: classes.ultrapayAutoPapara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MULTIPAY_PEP]: classes.multipayPep,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MULTIPAY_HAVALE]: classes.multipayHavale,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MULTIPAY_HAYHAY]: classes.multipayHayhay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MULTIPAY_PAYCELL]: classes.multipayPaycell,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MULTIPAY_PARAZULA]: classes.multipayParazula,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MULTIPAY_PAROLAPARA]: classes.multipayParolaPara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MULTIPAY_PAYBOL]: classes.multipayPaybol,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MULTIPAY_PAPEL]: classes.multipayPapel,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_POPYPARA]: classes.popypara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_KOLAYPAY_PAPARA]: classes.kolaypayPapara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_KOLAYPAY_HAVALE]: classes.kolaypayHavale,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_SISTEMNAKIT_HAVALE]: classes.sistemnakitHavale,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TR_HAVALE_EFT]: classes.trHavaleEft,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_PAYQASA]: classes.payqasa,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_FINPAY_HAVALE]: classes.finpay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_VEVO_HAVALE]: classes.vevo,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_VEVO_PARAZULA]: classes.vevoParazula,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_FIN2]: classes.fin2,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_SERIPAY1]: classes.seripay1,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_MYPAYZ]: classes.mypayz,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_PAYFUTURE]: classes.payfuture,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_PAPARA]: classes.turkpayPapara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_PAYFIX]: classes.turkpayPayfix,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_PAYCO]: classes.turkpayPayco,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_ININAL]: classes.turkpayIninal,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_BANK_TRANSFER]: classes.turkpayBankTransfer,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_VIZYONPAY]: classes.turkpayVizyonpay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_AYPARA]: classes.turkpayAypara,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_SIPAY]: classes.turkpaySipay,
  [PAYMENT_METHOD_ID_MAP.FIX_FIN_FIAT_WITHDRAWAL_TURKPAY_PAYCELL]: classes.turkpayPaycell,

  [PAYMENT_METHOD_ID_MAP.KOLAY_PAY_PAPARA_DEPOSIT_ID]: classes.kolayPay,
  [PAYMENT_METHOD_ID_MAP.KOLAY_PAY_HAVALE_DEPOSIT_ID]: classes.kolayPay,
  [PAYMENT_METHOD_ID_MAP.KOLAY_PAY_HAVALE_WITHDRAWAL_ID]: classes.kolayPay,

  [PAYMENT_METHOD_ID_MAP.MUCH_BETTER_DEPOSIT_ID]: classes.muchBetter,
  [PAYMENT_METHOD_ID_MAP.MUCH_BETTER_WITHDRAWAL_ID]: classes.muchBetter,

  [PAYMENT_METHOD_ID_MAP.BANK_TRANSFER_DEPOSIT_ID]: classes.bankTransfer,
  [PAYMENT_METHOD_ID_MAP.BANK_TRANSFER_WITHDRAWAL_ID]: classes.bankTransfer,

  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_PIX_DEPOSIT_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_BANCO_ITAU_DEPOSIT_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_SANTANDER_BRASIL_DEPOSIT_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_BANCO_DO_BRASIL_DEPOSIT_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_BRADESCO_DEPOSIT_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_BITCOIN_DEPOSIT_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_USDT_DEPOSIT_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_BOLETO_RAPIDO_DEPOSIT_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_PIX_WITHDRAWAL_ID]: classes.payRetailers,
  [PAYMENT_METHOD_ID_MAP.PAY_RETAILERS_WITHDRAWAL_ID]: classes.payRetailers,

  [PAYMENT_METHOD_ID_MAP.VPAG_PIX_DEPOSIT_ID]: classes.vpag,
  [PAYMENT_METHOD_ID_MAP.VPAG_PIX_WITHDRAWAL_ID]: classes.vpag,

  [PAYMENT_METHOD_ID_MAP.AN_SPACE_PAY_PIX_DEPOSIT_ID]: classes.anspacepay,
  [PAYMENT_METHOD_ID_MAP.AN_SPACE_PAY_PIX_WITHDRAWAL_ID]: classes.anspacepay,

  [PAYMENT_METHOD_ID_MAP.LUXON_PAY_DEPOSIT_ID]: classes.luxonPay,
  [PAYMENT_METHOD_ID_MAP.LUXON_PAY_WITHDRAWAL_ID]: classes.luxonPay,

  [PAYMENT_METHOD_ID_MAP.SKRILL_DIGITAL_WALLET_DEPOSIT_ID]: classes.digitalWallet,
  [PAYMENT_METHOD_ID_MAP.SKRILL_NETELLER_DEPOSIT_ID]: classes.neteller,
  [PAYMENT_METHOD_ID_MAP.SKRILL_PAYSAFECARD_DEPOSIT_ID]: classes.paysafecard,
  [PAYMENT_METHOD_ID_MAP.SKRILL_DIGITAL_WALLET_WITHDRAWAL_ID]: classes.digitalWallet,
  [PAYMENT_METHOD_ID_MAP.SKRILL_NETELLER_WITHDRAWAL_ID]: classes.neteller,
  [PAYMENT_METHOD_ID_MAP.SKRILL_PAYSAFECARD_WITHDRAWAL_ID]: classes.paysafecard,

  [PAYMENT_METHOD_ID_MAP.ONE_SEPA_WITHDRAWAL_ID]: classes.sepa,
  [PAYMENT_METHOD_ID_MAP.ONE_SWIFT_WITHDRAWAL_ID]: classes.swift,

  [PAYMENT_METHOD_ID_MAP.PAYMENT_CLIP_UPI_DEPOSIT_ID]: classes.paymentClip,
  [PAYMENT_METHOD_ID_MAP.PAYMENT_CLIP_UPI_WITHDRAWAL_ID]: classes.paymentClip,

  [PAYMENT_METHOD_ID_MAP.PAYCENT_SOFORT_DEPOSIT_ID]: classes.sofort,
  [PAYMENT_METHOD_ID_MAP.PAYCENT_GIROPAY_DEPOSIT_ID]: classes.giropay,

  [PAYMENT_METHOD_ID_MAP.PAY_PORT_DEPOSIT_ID]: classes.payport,
  [PAYMENT_METHOD_ID_MAP.PAY_PORT_WITHDRAWAL_ID]: classes.payport,

  [PAYMENT_METHOD_ID_MAP.EXXOGATE_UPI_9_DEPOSIT_ID]: classes.exxogateUpi9,
  [PAYMENT_METHOD_ID_MAP.EXXOGATE_UPI_29_DEPOSIT_ID]: classes.exxogateUpi29,
  [PAYMENT_METHOD_ID_MAP.EXXOGATE_UPI_41_DEPOSIT_ID]: classes.exxogateUpi41,
  [PAYMENT_METHOD_ID_MAP.EXXOGATE_UPI_43_DEPOSIT_ID]: classes.exxogateUpi43,

  [PAYMENT_METHOD_ID_MAP.EXXOGATE_IMPS_9_WITHDRAWAL_ID]: classes.exxogateImps9,
  [PAYMENT_METHOD_ID_MAP.EXXOGATE_IMPS_29_WITHDRAWAL_ID]: classes.exxogateImps29,
  [PAYMENT_METHOD_ID_MAP.EXXOGATE_IMPS_41_WITHDRAWAL_ID]: classes.exxogateImps41,
  [PAYMENT_METHOD_ID_MAP.EXXOGATE_IMPS_43_WITHDRAWAL_ID]: classes.exxogateImps43,
};

const PaymentMethodIcon = memo<IPaymentMethodIconProps>(({ paymentMethodId, className }) => (
  <div className={clsx(classes.methodIcon, className)}>
    <div className={paymentMethodMap[paymentMethodId] ?? classes.bankTransfer} />
  </div>
));
PaymentMethodIcon.displayName = "PaymentMethodIcon";

export { PaymentMethodIcon };
