/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/sdk/typescript/TSErrorMappingGenerator.kt
 */
export enum EGetDemoGameLinkCommandErrorCode {
  gameDemoIsUnavailable = "game.demo_is_unavailable",
  gameGameIsInactive = "game.game_is_inactive",
  gameGameUrlFailedProviderNotActive = "game.game_url_failed_provider_not_active",
  gameGameWithIdsNotFound = "game.game_with_ids_not_found",
  gameGetDemoGameUrlProviderError = "game.get_demo_game_url_provider_error",
}

export interface IGameDemoIsUnavailableContext {
  gameId: string,
}

export interface IGameGameIsInactiveContext {
  gameId: string,
}

export interface IGameGameUrlFailedProviderNotActiveContext {
  id: string,
  provider: string,
}

export interface IGameGameWithIdsNotFoundContext {
  ids: string,
}

export interface IGameGetDemoGameUrlProviderErrorContext {
  gameId: string,
}

export interface IGetDemoGameLinkCommandErrorMapping {
  [EGetDemoGameLinkCommandErrorCode.gameDemoIsUnavailable]: IGameDemoIsUnavailableContext,
  [EGetDemoGameLinkCommandErrorCode.gameGameIsInactive]: IGameGameIsInactiveContext,
  [EGetDemoGameLinkCommandErrorCode.gameGameUrlFailedProviderNotActive]: IGameGameUrlFailedProviderNotActiveContext,
  [EGetDemoGameLinkCommandErrorCode.gameGameWithIdsNotFound]: IGameGameWithIdsNotFoundContext,
  [EGetDemoGameLinkCommandErrorCode.gameGetDemoGameUrlProviderError]: IGameGetDemoGameUrlProviderErrorContext,
}
