/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/sdk/typescript/TSErrorMappingGenerator.kt
 */
export enum EGetGameLinkCommandErrorCode {
  blockValidationError = "block.validation_error",
  gameGameIsInactive = "game.game_is_inactive",
  gameGameNotAvailableForBonusError = "game.game_not_available_for_bonus_error",
  gameGameUrlFailedProviderNotActive = "game.game_url_failed_provider_not_active",
  gameGameWithIdsNotFound = "game.game_with_ids_not_found",
  gameGetGameUrlProviderError = "game.get_game_url_provider_error",
  gamePlayerInsufficientBalance = "game.player_insufficient_balance",
}

export interface IBlockValidationErrorContext {
  errors: Array<string>,
}

export interface IGameGameIsInactiveContext {
  gameId: string,
}

export interface IGameGameNotAvailableForBonusErrorContext {
}

export interface IGameGameUrlFailedProviderNotActiveContext {
  id: string,
  provider: string,
}

export interface IGameGameWithIdsNotFoundContext {
  ids: string,
}

export interface IGameGetGameUrlProviderErrorContext {
  gameId: string,
}

export interface IGamePlayerInsufficientBalanceContext {
}

export interface IGetGameLinkCommandErrorMapping {
  [EGetGameLinkCommandErrorCode.blockValidationError]: IBlockValidationErrorContext,
  [EGetGameLinkCommandErrorCode.gameGameIsInactive]: IGameGameIsInactiveContext,
  [EGetGameLinkCommandErrorCode.gameGameNotAvailableForBonusError]: IGameGameNotAvailableForBonusErrorContext,
  [EGetGameLinkCommandErrorCode.gameGameUrlFailedProviderNotActive]: IGameGameUrlFailedProviderNotActiveContext,
  [EGetGameLinkCommandErrorCode.gameGameWithIdsNotFound]: IGameGameWithIdsNotFoundContext,
  [EGetGameLinkCommandErrorCode.gameGetGameUrlProviderError]: IGameGetGameUrlProviderErrorContext,
  [EGetGameLinkCommandErrorCode.gamePlayerInsufficientBalance]: IGamePlayerInsufficientBalanceContext,
}
