// @ts-nocheck

const betLimitEnum = {
  MAX_PER_BET: "MAX_PER_BET",
  MAX_BET_PER_EVENT: "MAX_BET_PER_EVENT",
  MIN_PER_BET: "MIN_PER_BET",
  MAX_WIN_PER_BET: "MAX_WIN_PER_BET",
  MAX_WIN_PER_EVENT: "MAX_WIN_PER_EVENT",
  MAX_WIN_TOTAL: "MAX_WIN_TOTAL",
  MIN_COEFFICIENT_PER_BET: "MIN_COEFFICIENT_PER_BET",
  MIN_COEFFICIENT_PER_PICK: "MIN_COEFFICIENT_PER_PICK",
};

export { betLimitEnum };
