/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/sdk/typescript/TSErrorMappingGenerator.kt
 */
export enum EBaseVerifyPhoneCommandErrorCode {
  securityPhoneAlreadyVerified = "security.phone_already_verified",
  securityVerificationTokenIsNull = "security.verification_token_is_null",
  tokenInvalidCode = "token.invalid_code",
  tokenInvalidToken = "token.invalid_token",
  tokenTokenUsed = "token.token_used",
  tokenVerificationTokenExpired = "token.verification_token_expired",
}

export interface ISecurityPhoneAlreadyVerifiedContext {
  operation: string,
  phone: string,
}

export interface ISecurityVerificationTokenIsNullContext {
  operation: string,
  tokenType: string,
  userId: string,
}

export interface ITokenInvalidCodeContext {
  hostAddress?: string,
  operation: string,
  userId: string,
  verifyCode: string,
}

export interface ITokenInvalidTokenContext {
  operation: string,
  token: string,
}

export interface ITokenTokenUsedContext {
  operation: string,
}

export interface ITokenVerificationTokenExpiredContext {
  operation: string,
}

export interface IVerifyPhoneCommandErrorMapping {
  [EBaseVerifyPhoneCommandErrorCode.securityPhoneAlreadyVerified]: ISecurityPhoneAlreadyVerifiedContext,
  [EBaseVerifyPhoneCommandErrorCode.securityVerificationTokenIsNull]: ISecurityVerificationTokenIsNullContext,
  [EBaseVerifyPhoneCommandErrorCode.tokenInvalidCode]: ITokenInvalidCodeContext,
  [EBaseVerifyPhoneCommandErrorCode.tokenInvalidToken]: ITokenInvalidTokenContext,
  [EBaseVerifyPhoneCommandErrorCode.tokenTokenUsed]: ITokenTokenUsedContext,
  [EBaseVerifyPhoneCommandErrorCode.tokenVerificationTokenExpired]: ITokenVerificationTokenExpiredContext,
}
