/**
 * ⚠️ GENERATED CODE - DO NOT MODIFY BY HAND
 *
 * 🔨️ GENERATED BY kotlin/tools/code-generator-common/src/main/kotlin/com/sumstats/codegenerator/common/sdk/typescript/TSErrorMappingGenerator.kt
 */
export enum EBaseVerifyDeviceCommandErrorCode {
  securityDeviceAlreadyVerified = "security.device_already_verified",
  securityDeviceNotFound = "security.device_not_found",
  securityDeviceVerificationAttemptsExceeded = "security.device_verification_attempts_exceeded",
  securityDeviceVerificationCodeExpired = "security.device_verification_code_expired",
  securityDeviceVerificationCodeInvalid = "security.device_verification_code_invalid",
}

export interface ISecurityDeviceAlreadyVerifiedContext {
  operation: string,
}

export interface ISecurityDeviceNotFoundContext {
  deviceId: string,
  operation: string,
}

export interface ISecurityDeviceVerificationAttemptsExceededContext {
  deviceId: string,
  hostAddress: string,
  operation: string,
}

export interface ISecurityDeviceVerificationCodeExpiredContext {
  deviceId: string,
  operation: string,
}

export interface ISecurityDeviceVerificationCodeInvalidContext {
  deviceId: string,
  hostAddress: string,
  operation: string,
  verificationCode: string,
}

export interface IVerifyDeviceCommandErrorMapping {
  [EBaseVerifyDeviceCommandErrorCode.securityDeviceAlreadyVerified]: ISecurityDeviceAlreadyVerifiedContext,
  [EBaseVerifyDeviceCommandErrorCode.securityDeviceNotFound]: ISecurityDeviceNotFoundContext,
  [EBaseVerifyDeviceCommandErrorCode.securityDeviceVerificationAttemptsExceeded]: ISecurityDeviceVerificationAttemptsExceededContext,
  [EBaseVerifyDeviceCommandErrorCode.securityDeviceVerificationCodeExpired]: ISecurityDeviceVerificationCodeExpiredContext,
  [EBaseVerifyDeviceCommandErrorCode.securityDeviceVerificationCodeInvalid]: ISecurityDeviceVerificationCodeInvalidContext,
}
